### ISSUE TITLE
`resolveId` is called before `buildStart` with enforce: 'pre'

### ISSUE THREAD

**Issue by sagargurtu** [vitest-dev/vitest#5616] opened 2024-04-24 23:59 UTC
### Describe the bug

`buildStart()` is not called for plugins with `enforce: 'pre'`.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-gdhqm5

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 1.5.1 
    vite: latest => 5.2.10 
    vitest: latest => 1.5.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment] 2024-04-25 01:09
It looks like `buildStart` is still called, but the issue is that `resolveId` is called before `buildStart` when you have `enforce: "pre"`.
I also made a repro here:
https://github.com/hi-ogawa/reproductions/tree/main/vitest-5616-plugin-build-start

```sh
> vitest

@resolveId(pre) { source: 'vitest' }
@resolveId(pre) { source: 'vitest' }
@buildStart(pre)
@buildStart(normal)

 DEV  v1.5.1 /home/projects/wmaivylmj.github
...
```

I remembered someone mentioned that `buildStart` is not working, but it looks like the same issue where `resolveId` being getting called first:
- https://github.com/vitest-dev/vitest/discussions/5479

**Comment by hi-ogawa** [comment] 2024-04-25 10:24
This `resolveId` seems to be the trigger, which is called during `configureServer` and before `buildStart`

https://github.com/vitest-dev/vitest/blob/597e0c20d044f69ab0088de79208fa52bd66bbe2/packages/vitest/src/node/core.ts#L110

Quick logging from plugin shows something like this:

```sh
@configureServer(pre)
@resolveId(pre) { source: 'vitest' }
@resolveId(pre) { source: 'vitest' }
@configureServer(normal)
@buildStart(pre)
@buildStart(normal)
```

@sagargurtu Can you explain what is your use case? The linked discussion mentioned `rollup-plugin-node-externals`. I think this is technically what Vitest shouldn't do, but I'm not sure if there is a quick way around.
Depending on the use case, there might be a workaround on plugin side.

**Comment by Septh** [comment] 2024-04-25 16:33
Hi! `rollup-plugin-node-externals` author here.

I was not aware of this and the linked discussion until @chandu filed Septh/rollup-plugin-node-externals#30 which I fixed by not relying on `buildStart` to initialize my variables. Simple enough.

However I do believe that this is a bug that should be fixed in Vitest because the order in which the hooks are called is clearly defined by Rollup's documentation and diverging from that order is wrong (and my plugin might not be the only one affected).

**Comment by sagargurtu** [comment] 2024-04-26 09:48
@hi-ogawa While I could potentially move my initialization code to `config()` or the function that returns the plugin object, I agree with @Septh as many other existing plugins could break because of this issue.

**Closed** 2024-05-02 08:15 UTC
Labels: p3-minor-bug

**Comment by Septh** [comment] 2024-05-02 15:37
Awesome! Thanks, guys. 👍
