### ISSUE TITLE
Built-in JSDoc @example block testing

### ISSUE THREAD

**Issue by aripalo** [vitest-dev/vitest#6651] opened 2024-10-06 14:46 UTC
### Clear and concise description of the problem

In JS/TS libraries, API documentation – written with JSDoc syntax – is really important:
1. It allows to communicate meaning and example usage for other (current & future) developers of the library
2. It allows creation of API reference docs (as a separate static site) for the users of the library

… this means that having up-to-date and functioning examples in the JSDoc is critical.

Without any testing for the JSDoc documentation examples, it can easily happen (especially over time as the project evolves), for those JSDoc examples to be invalid, incorrect and/or outdated.

Having the possibility to actually test the JSDoc examples would greatly lessen the possibility of invalid examples.

### Suggested solution

**Similar to Deno's [Documentation Tests](https://docs.deno.com/runtime/fundamentals/testing/#documentation-tests).**

Basically I'd like to have both CLI option and config option to enable documentation tests:
- CLI: `vitest --doc`
- config: `doc: true`

Then, in JSDoc, one could have an `@example` block of code with any test assertion (such as `expect`) and Vitest would parse the code block and execute the test:
```ts
/**
 * # Examples
 *
 * @example
 * ```ts
 * const sum = add(ONE, getTwo());
 * expect(sum).toBe(3);
 * ```
 */
export function add(a: number, b: number): number {
  return a + b;
}

export const ONE = 1;
export default function getTwo() {
  return 2;
}

```

### Alternative

There is a community plugin for Vitest ([`vite-plugin-doctest`](https://www.npmjs.com/package/vite-plugin-doctest)) and few others like it, but these plugins are not actively/well maintained and adding them as dependency feels bad as you can't be sure they will keep working in the future. For example in case of `vite-plugin-doctest`, it's already having issues with upcoming Vite versions, causing warnings like:
```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```

I believe this feature should be part of the core Vitest feature set, as it's so critical functionality.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment] 2024-10-06 15:59
Duplicate of https://github.com/vitest-dev/vitest/issues/3035.

We've discussed this feature with the team earlier and decided that this is not something we are going to support.

**Closed by AriPerkkio** 2024-10-06 15:59 UTC
Labels: enhancement: pending triage

**Comment by aripalo** [comment] 2024-10-07 09:05
Okay.

(Also, sorry about the duplicate issue, I tried searching with `JSDoc` so didn't spot that #3035.)
