### ISSUE TITLE
Errors inside describe() get swallowed when `threads: false`

### ISSUE THREAD

**Issue by EvHaus** [vitest-dev/vitest#468] opened 2022-01-07 06:29 UTC
### Describe the bug

If your test code has a syntax error inside the `describe()` block, but outside the `it()` block, it gets swallowed and is never printed -- making it hard to find out what's going wrong.

This only seems to happen if you configure `threads: false` in the configuration settings.

### Reproduction

The simple mistake I made was trying to use `beforeEach()` without `globals: true` set in configs. This makes vitest run, but it simply skips the tests. Here's the repro link:

https://stackblitz.com/edit/node-tg37es?file=vite.config.ts&view=editor

If you change `threads` to `true`, you'll see the actual error getting printed:

```
ReferenceError: afterEach is not defined
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 658.48 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.01.03.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 97.0.4692.71
    Chrome Canary: 99.0.4811.0
    Firefox: 95.0
    Safari: 15.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-01-07 08:21
Duplicate of https://github.com/vitest-dev/vitest/issues/294

**Closed** 2022-04-05 09:56 UTC
Labels: bug, duplicate
