### ISSUE TITLE
Reports to inherit include & exclude folders from test config

### ISSUE THREAD

**Issue by nader-eloshaiker** [vitest-dev/vitest#4877] opened 2024-01-05 01:56 UTC
### Clear and concise description of the problem

Currently, configuring the `test.exlude` and and `test.include` props does not propagate through to `test.coverage.exclude` and `test.coverage.include` and therefore must be copied across.

### Suggested solution

Have the `test.coverage` config object inherit the `include` and `exclude` values that were set in the root `test` config block. The developer can then choose to override them by explicitly providing these props in the `test.coverage`. This change will not break any existing configuration.

### Additional context

The reduces the amount of double handling configuration values.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment] 2024-01-05 06:12
Could you provide an example of file structure and Vitest configuration where this would make sense?

Typically users do not want to collect coverage of their test files. They are only interested in source files. The `test.include/exclude` instructs Vitest which tests to run. The `test.coverage.include/exclude` instructs Vitest which source files to include in coverage report. 

Below is example of project structure and configuration file where it would not make sense to extend `test.include/exclude` in coverage fields.

```
/project-root
├── package.json
├── vite.config.js
|
├── src
|  ├── source-file-1.js
|  ├── source-file-2.js
|  └── utils
|     └── source-file-3.js
|
└── test
   ├── test-file-1.test.js
   ├── test-file-2.test.js
   └── end-to-end
       └── test-file-3.test.js
```

```js
export default defineConfig({
  test: {
    // Run all tests in test/ directory
    include: ["./test/**"],

    // Except end-to-end tests
    exclude: ["./test/end-to-end/**"],

    coverage: [
      // Collect coverage of all files in src/ directory
      include: ["./src/**"],

      // Except utility files
      exclude: ["./src/utils/**"],
    ]
  }, 
});
```

**Comment by sheremet-va** [comment] 2024-01-05 06:13
The change will break every existing configuration because these are two non related options. `include` should reference only test files while `coverage.include` can reference any source file

**Comment by sheremet-va** [comment] 2024-01-05 06:48
> The annoyance I am trying to work around is specifically the exclude folder. I don't want to collect coverage for files that are excluded from tests. The include isn't really something I am shooting for. 

The same reasoning applies here. You most likely don’t even need to use `exclude` option, only `coverage.exclude`.

**Comment by nader-eloshaiker** [comment] 2024-01-05 06:57
I keep the test files beside the code files and I have to specify exclude in both places, otherwise the coverage report includes them.
eg. `src/generated` as an exclude in both `test` and `test.coverage`

**Comment by AriPerkkio** [comment] 2024-01-05 07:12
Without seeing the project structure and your configuration file it's difficult to instruct, but it sounds like configuration problem instead. Why do you have test files in `src/generated`? Sounds like you should only specify that in `coverage.exclude`.

And as mentioned above, we cannot inherit these options without breaking existing configurations. I don't think any other tools do it either.

**Comment by nader-eloshaiker** [comment] 2024-01-05 07:46
I don't have tests in generated, the coverage report is including the code in that folder. I have to exclude it.
The app is open source. Here is the config. 
https://github.com/nader-eloshaiker/screen-geometry-app/blob/develop/vite.config.ts

**Comment by AriPerkkio** [comment] 2024-01-05 12:31
> I don't have tests in generated, the coverage report is including the code in that folder. I have to exclude it.

If there are no tests in `src/generated`, it doesn't make sense to use `test: { exclude: ['src/generated'] }` in the first place. 😕 

I don't see any reason why `coverage.include/exclude` should extend `test.include/exclude`. Those are two different things.

**Comment by nader-eloshaiker** [comment] 2024-01-07 02:16
You seem to be missing the point and making assumptions that I am testing generated code. Go ahead and close the issue.

**Comment by AriPerkkio** [comment] 2024-01-07 08:18
Closing issue as we cannot assume `coverage.include/exclude` based on `test.include/exclude` as those are two different things. Extending coverage fields based on test fields would cause unexpected behaviour. 

By looking at the linked related project, it seems that it has `test.exclude` defined even though it doesn't need it. All it needs is to have those in `coverage.exclude`. You can remove this line completely: https://github.com/nader-eloshaiker/screen-geometry-app/blob/b75b2bff0ff8fe255524137965ff704050fe7236/vite.config.ts#L63 and prevent duplicating the configuration. Those patterns do not match any test files.

**Closed by AriPerkkio** 2024-01-07 08:18 UTC
Labels: coverage
