### ISSUE TITLE
vitest browser __vi_esm_0__.default is not a function

### ISSUE THREAD

**Issue by NicoVogel** [vitest-dev/vitest#4097] opened 2023-09-08 14:31 UTC
### Describe the bug

When executing the tests, each test fails because of `TypeError: __vi_esm_0__.default is not a function`.
After reducing it to the minimal reproducible example, I could isolate that the issue is the package `pino`.

You can find "working" tests  here `src/browser/working.spec.ts`
> The mocking does not work, but this is besides this bug

But the same code that uses `pino` is not able to load it: `src/browser/logger.spec.ts`

### Reproduction

1. `git clone https://github.com/NicoVogel/logger-wrapper`
2. `git checkout bug/vitest-browser-vi-esm-0-default-not-a-function`
3. (optional) reopen in dev container
4. `pnpm install`
5. `cd packages/logger`
6. `pnpm exec vitest -c vitest.browser.ts`

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-1340P
    Memory: 24.36 GB / 31.05 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.140
  npmPackages:
    @vitest/browser: ^0.34.1 => 0.34.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment] 2023-12-07 09:18
I think this is also CJS import issue with `browser.slowHijackESM: true` and probably considered as a duplicate of https://github.com/vitest-dev/vitest/issues/4264, https://github.com/vitest-dev/vitest/issues/4505, etc...

As I commented in https://github.com/vitest-dev/vitest/issues/4505#issuecomment-1842382572, the default became `browser.slowHijackESM: false` in Vitest v1, so either you can upgrade it or you can manually set `slowHijackESM: false` in old version.

I tested your repro with `slowHijackESM: false` and default import works but `import { pino } from "pino"` is still undefined. It looks like that was issue on Pino side and it seems to be fixed recently in https://github.com/pinojs/pino/pull/1803.
(Interestingly Pino now also exports `default.default`, so it actually allows it work with `slowHijackESM: true` as well)

**Comment by clocke3** [comment] 2024-01-04 19:05
I am seeing something similar in an application, instead with this error: **TypeError: __vi_import_0__.jsxDEVdescribe is not a function**. It looks like it is thrown when trying to use **vi.mock.**  

`
vi.mock('../../components/shared/table', () => {
	return { default: () => <div role='table'>table</div> };
});
`

**Closed** 2024-05-31 09:19 UTC
Labels: feat: browser, p3-minor-bug
