### ISSUE TITLE
vite-node doesn't kill the server on rebuilds

### ISSUE THREAD

**Issue by goldylucks** [vitest-dev/vitest#2583] opened 2022-12-31 10:58 UTC
### Describe the bug

the build works, but any rebuild will trigger
```
Error: listen EADDRINUSE: address already in use :::8001
```

Which is the port my express app runs on. This means vite-node doesn't clean up after itself?

### Reproduction

1. Create an express app with vite-node
2. run `$ vite-node my-app.ts -w`
3. Trigger a rebuild

### System Info

```shell
$ npx envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers

  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.53 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 101.0.1
    Safari: 16.1
  npmPackages:
    @vitejs/plugin-react: ^3.0.0 => 3.0.0
    vite: ^4.0.1 => 4.0.3
    vitest: ^0.25.8 => 0.25.8
```
```


### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-12-31 11:30
Duplicate of https://github.com/vitest-dev/vitest/issues/2334

**Closed by sheremet-va** 2022-12-31 11:30 UTC
