### ISSUE TITLE
Global URL doesn't comply with web standards since 0.25.1, when using happy-dom

### ISSUE THREAD

**Issue by JacksonGariety** [vitest-dev/vitest#2305] opened 2022-11-10 02:26 UTC
### Describe the bug

Mock Service Worker (`msw`) no longer handles requests after upgrading from Vitest 0.25.0 to 0.25.1 when using `happy-dom` or `jsdom` + `node-fetch@2.x.x` (the version included in `happy-dom`).

### Reproduction

1. Create a vitest test including a mock service worker.

```javascript
import { setupServer } from 'msw/node';
import { rest } from 'msw';

const server = setupServer(
  rest.get('http://foo.com/', async (req, res, ctx) => {
    console.log('intercepted request');
    return res(ctx.status(200));
  }),
);


describe('foo', () => {
  beforeAll(() => server.listen());
  
  it('makes a request to the server', async () => {
    await fetch('http://foo.com/')
  })
});
```

2. Install vitest `0.25.0` and any version of `happy-dom`. (Or use `jsdom` + `node-fetch@2.x.x`, adding `import { fetch } from 'node-fetch'` to the test script.)

3. Run `vitest --environment happy-dom` (or `jsdom`) and note that it prints `intercepted request` to the console.

4. Upgrade to vitest `0.25.1`.

5. Re-run vitest and note that it prints this:

```
[MSW] Warning: captured a request without a matching request handler:

  • GET ///
```

It no longer works.

UPDATE: Actually it works with `0.25.0`. It is `0.25.1` that causes the error. I believe the problematic commit is 922e525244d1f69ea3e8f609e88e2ba503a069d4.

UPDATE 2: If you remove `'URL'` from `LIVING_KEYS` in [packages/vitest/src/integrations/env/jsdom-keys.ts](https://github.com/vitest-dev/vitest/commit/922e525244d1f69ea3e8f609e88e2ba503a069d4#diff-73ce7c0fd4c8496962cea34e837c9fb5e1b4932a36abf3294c0970f577069cbc) then it works.

### System Info

```shell
System:
    OS: Linux 6.0 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 16.67 GB / 23.40 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/pnpm/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chromium: 107.0.5304.110
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-11-10 07:47
`fetch` is not defined in node 16. Please, provide correct reproduction

**Comment by JacksonGariety** [comment] 2022-11-10 15:56
@sheremet-va Updated the reproduction steps. One can reproduce by either using `jsdom` + `node-fetch@2.x.x` or by using `happy-dom` (which includes `node-fetch@2.x.x`).

**Comment by JacksonGariety** [comment] 2022-11-11 00:33
Actually it works with 0.25.0. It is 0.25.1 that causes the error. I believe the problematic commit is 922e525244d1f69ea3e8f609e88e2ba503a069d4. The adjustment to [integrations/env/utils.ts](https://github.com/vitest-dev/vitest/commit/922e525244d1f69ea3e8f609e88e2ba503a069d4#diff-6377c49695420a0ca3ca922da4b8cd90d929157716c3345651b0a59d60a99357) perhaps?

**Comment by sheremet-va** [comment] 2022-11-11 07:45
> If you remove `'URL'` from `LIVING_KEYS` in [packages/vitest/src/integrations/env/jsdom-keys.ts](https://github.com/vitest-dev/vitest/commit/922e525244d1f69ea3e8f609e88e2ba503a069d4#diff-73ce7c0fd4c8496962cea34e837c9fb5e1b4932a36abf3294c0970f577069cbc) then it works.

But why JSDOM URL cases an error with MSW? 🤔

**Comment by sheremet-va** [comment] 2022-11-11 08:18
Interesting 🤔 Node URL and `happy-dom` URL return different objects 🤔 

<img width="746" alt="Screenshot 2022-11-11 at 09 16 08" src="https://user-images.githubusercontent.com/16173870/201296242-4b4f5958-d6a0-4a0a-a5c6-ed9941d2cf64.png">

**Comment by sheremet-va** [comment] 2022-11-11 09:04
Ok, I found it. JSDom/Happy-dom has a bug when parsing new URL, it seems.

<img width="569" alt="Screenshot 2022-11-11 at 10 03 59" src="https://user-images.githubusercontent.com/16173870/201305355-815ddc8e-43ee-4950-a761-33bc64f79ef0.png">

I checked in Safari, and it does parse like NodeURL:

<img width="282" alt="Screenshot 2022-11-11 at 09 52 57" src="https://user-images.githubusercontent.com/16173870/201303028-17571d24-6acc-477b-8a04-0599e8c5102c.png">

JSDOM also returns correct object.

**Comment by belgattitude** [comment] 2022-11-15 11:10
Not sure about msw, but I could reproduce in a nextjs app / react as well:

https://github.com/vitest-dev/vitest/issues/2331

Regarding happy-dom, I'm a bit confused cause in my case it works with 0.25.0, but from vitest 0.25.1 seems that sometimes the URL constructor receive an `URL`rather than a `string`

**Comment by sheremet-va** [comment] 2022-11-15 11:12
> Regarding happy-dom, I'm a bit confused cause in my case it works with 0.25.0, but from vitest 0.25.1 seems that sometimes the URL constructor receive an URLrather than a string

Before 0.25.1 Vitest had a bug, where it used Node's URL instead of happy-dom's URL, when `happy-dom` was used as environment. Now the bug is fixed, and happy-dom fails, because its URL implementation is wrong.

**Comment by oliverzy** [comment] 2023-01-19 03:16
this has been fixed by upgrading happy-dom to the latest version such as 8.0

**Closed** 2023-01-19 07:10 UTC
Labels: upstream
