### ISSUE TITLE
vitest 0.34.0 introduced istanbul coverage parse failure

### ISSUE THREAD

**Issue by jandolezal71** [vitest-dev/vitest#3875] opened 2023-08-03 08:33 UTC
### Describe the bug

I run tests with coverage `--coverage` with instabul coverage reporter (for gitlab), but after update to 0.34.0, tests fail with `Parse failure: Unexpected token`.

After updating these:

- `vitest` from `0.33.0` to `0.34.1`
- `@vitest/coverage-istanbul` from `0.33.0` to `0.34.1`

```
Error: Parse failure: Unexpected token (839:2714)

At file: /src/server/lib/cache/cacheInstance.ts
Contents of line 839:       sourcesContent: ["import type { Cache, Metrics as CacheMetrics } from '@/server/lib/cache/Cache';\nimport {\n\tClusterCache,\n\tparseDbIndex as parseClusterDbIndex,\n} from '@/server/lib/cache/ClusterCache';\nimport { MemoryCache } from '@/server/lib/cache/MemoryCache';\nimport { metrics } from '@/server/lib/metrics/metricsInstance';\nimport { logger } from '@/server/utils/logger';\n\nconst globalInstance = global as unknown as {\n\tcache: Cache;\n};\n\nfunction instantiate(): Cache {\n\t// NOTE: https://github.com/prisma/prisma/discussions/4399\n\t// eslint-disable-next-line @typescript-eslint/no-unnecessary-condition\n\tif (globalInstance.cache) {\n\t\treturn globalInstance.cache;\n\t}\n\n\tconst metricsConfig: CacheMetrics = {\n\t\tonResponse: (response, key) => metrics.cacheResponseInc({ response, key }),\n\t\tonOperation: (operation, key) =>\n\t\t\tmetrics.cacheOperationInc({ operation, key }),\n\t\tparseKey: (key) => {\n\t\t\tconst [staticKey] = key.split('-');\n\n\t\t\treturn staticKey ?? key;\n\t\t},\n\t};\n\n\tconst sentinelHosts = (process.env.DNSM_CACHE_REDIS_SENTINEL_HOSTS ?? '')\n\t\t.split(',')\n\t\t.map((host) => host.trim())\n\t\t.map((hostWithPort) => {\n\t\t\tconst [host, portString = ''] = hostWithPort.split(':');\n\n\t\t\tconst port = Number.parseInt(portString, 10);\n\n\t\t\tif (!host || Number.isNaN(port)) {\n\t\t\t\treturn null;\n\t\t\t}\n\n\t\t\treturn { host, port };\n\t\t})\n\t\t.filter(Boolean);\n\n\tif (sentinelHosts.length && process.env.DNSM_CACHE_REDIS_PASSWORD) {\n\t\tconst handleError = (error: Error) => {\n\t\t\tlogger.error(error, 'Redis remote endpoint error');\n\t\t};\n\n\t\tconst cache = new ClusterCache(\n\t\t\t{\n\t\t\t\tcommandTimeout: 1000 * 5,\n\t\t\t\tconnectTimeout: 1000 * 10,\n\t\t\t\tdb: parseClusterDbIndex(process.env.DNSM_CACHE_REDIS_DB_INDEX),\n\t\t\t\t// https://www.npmjs.com/package/ioredis\n\t\t\t\tenableAutoPipelining: true,\n\t\t\t\tname: process.env.DNSM_CACHE_REDIS_SENTINEL_MASTER ?? 'master-redis',\n\t\t\t\tpassword: process.env.DNSM_CACHE_REDIS_PASSWORD,\n\t\t\t\tsentinelCommandTimeout: 1000 * 5,\n\t\t\t\tsentinels: sentinelHosts,\n\t\t\t},\n\t\t\t{ onError: handleError, metrics: metricsConfig },\n\t\t);\n\n\t\tlogger.debug(\n\t\t\t{\n\t\t\t\ttype: 'redis',\n\t\t\t\tsentinelHosts,\n\t\t\t},\n\t\t\t'Cache initialized',\n\t\t);\n\n\t\tglobalInstance.cache = cache;\n\n\t\treturn cache;\n\t}\n\n\tlogger.debug(\n\t\t{\n\t\t\ttype: 'memory',\n\t\t},\n\t\t'Cache initialized',\n\t);\n\n\tglobalInstance.cache = new MemoryCache(\n\t\t{ defaultTtl: 1000 * 60 * 60 * 24 },\n\t\t{ metrics: metricsConfig },\n\t);\n\n\treturn globalInstance.cache;\n}\n\n// NOTE: https://github.com/prisma/prisma/discussions/4399\nif ("test" !== 'production') {\n\tglobalInstance.cache = instantiate();\n}\n\nexport const cache = instantiate();\n"],

 ❯ ssrTransformScript node_modules/.pnpm/vite@4.4.8_@types+node@18.16.19/node_modules/vite/dist/node/chunks/dep-75f53616.js:55294:15
 ❯ ssrTransform node_modules/.pnpm/vite@4.4.8_@types+node@18.16.19/node_modules/vite/dist/node/chunks/dep-75f53616.js:55269:12
 ❯ Object.ssrTransform node_modules/.pnpm/vite@4.4.8_@types+node@18.16.19/node_modules/vite/dist/node/chunks/dep-75f53616.js:64943:20
```

My config:

```
import react from '@vitejs/plugin-react';
import tsconfigPaths from 'vite-tsconfig-paths';
import { defineConfig } from 'vitest/config';

/** @type {import('vite').UserConfig} */
// ts-prune-ignore-next
export default defineConfig({
	plugins: [tsconfigPaths(), react()],
	test: {
		environment: 'jsdom',
		coverage: {
			clean: true,
			provider: 'istanbul',
			reporter: ['cobertura', 'lcov'],
		},
		globals: true,
		snapshotFormat: {
			printBasicPrototype: true,
		},
	},
});
```

### Reproduction

Update vitest and @vitest/coverage-istanbul to 0.34.1 version and run `./node_modules/.bin/vitest run --coverage`

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 41.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/20068_1691049402887/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/20068_1691049402887/bin/yarn
    npm: 9.6.7 - ~/project/node_modules/.bin/npm
    pnpm: 7.28.0 - ~/Library/Caches/fnm_multishells/20068_1691049402887/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.2
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4
    @vitest/coverage-istanbul: ^0.34.1 => 0.34.1
    @vitest/ui: ^0.34.1 => 0.34.1
    vite: ^4.4.8 => 4.4.8
    vitest: ^0.34.1 => 0.34.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2023-08-03 10:09
Vitest's stackblitz is currently not working so I tested this on one of my projects. Works fine. 

<details>

```
 RUN  v0.34.1 /x/vitest-sonar-reporter
      Coverage enabled with istanbul

 ✓ test/sonar-reporter.test.ts (4)
   ✓ resolves outputFile from string
   ✓ resolves outputFile from object
   ✓ throws when outputFile is missing
   ✓ throws when outputFile object is missing entry
 ✓ test/index.test.ts (3) 1481ms
   ✓ writes a report 500ms
   ✓ report location is logged 490ms
   ✓ logging can be silenced 490ms

 Test Files  2 passed (2)
      Tests  7 passed (7)
   Start at  13:07:40
   Duration  1.85s (transform 161ms, setup 0ms, collect 389ms, tests 1.48s, environment 0ms, prepare 94ms)

 % Coverage report from istanbul
-------------------|---------|----------|---------|---------|-------------------
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------|---------|----------|---------|---------|-------------------
All files          |   29.23 |    19.44 |    12.5 |   30.64 |                   
 sonar-reporter.ts |   40.74 |    43.75 |      40 |   45.83 | 30-53,87-90       
 xml-escape.ts     |   63.63 |      100 |       0 |   63.63 | 34-49             
 xml.ts            |     3.7 |        0 |       0 |     3.7 | 28-144            
-------------------|---------|----------|---------|---------|-------------------
```

</details>

Are you sure this is coverage related? Are the tests working when coverage is disabled?

**Comment by sheremet-va** [comment] 2023-08-03 10:21
> Are you sure this is coverage related? Are the tests working when coverage is disabled?

I think this is a duplicate of https://github.com/vitest-dev/vitest/issues/3860

**Comment by jandolezal71** [comment] 2023-08-03 10:35
> > Are you sure this is coverage related? Are the tests working when coverage is disabled?
> 
> I think this is a duplicate of #3860

Ah! You are right! 

Yes, it is related to coverage, without `--coverage` it is working. 

Issue is really related to https://github.com/vitest-dev/vitest/issues/3860 (NODE_ENV usage).

Thanks, this can be close as duplicate.

**Comment by AriPerkkio** [comment] 2023-08-03 16:20
Duplicate of #3860, let's track this there.

**Closed by AriPerkkio** 2023-08-03 16:20 UTC
Labels: need reproduction
