### ISSUE TITLE
Error mounting component with Vue-Test-Utils

### ISSUE THREAD

**Issue by bernardo-zuchowski** [vitest-dev/vitest#1107] opened 2022-04-05 20:46 UTC
### Describe the bug

I was been using Vitest for test composables and it's been fine, but when I mount components with Vue-Test-Utils, the test doesn't run and return the error: `__vite_ssr_import_{someNumber}__.{someFunction}`.

I tried a few things, but I couldn't solve it.

If I have some error in my project, or some thing isn't right, please comment. I believe there is some incompatibility with Vue-Test-Utils.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-agvwae

### System Info

```shell
System:
  OS: Linux 5.15 Manjaro Linux
  CPU: (8) x64 Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz
  Memory: 6.23 GB / 15.24 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
  npm: 8.5.5 - ~/.nvm/versions/node/v16.14.2/bin/npm
Browsers:
  Firefox: 98.0.2
npmPackages:
  @vitejs/plugin-vue: ^2.3.0
  vite: ^2.9.0
  vitest: ^0.8.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-04-06 04:23
Duplicate of #553

Current solution is adding this to your config:
```
  optimizeDeps: {
    exclude: mode === 'test' ? ["vue"] : [],
  }
```

**Closed** 2022-04-06 04:23 UTC
