### ISSUE TITLE
vitest with mount from @vue/test-utils SyntaxError (0.20.3)

### ISSUE THREAD

**Issue by michaelmano** [vitest-dev/vitest#1793] opened 2022-08-05 01:42 UTC
### Describe the bug

Vitest version `0.19.1` is fine with this, However after upgrading to `0.20.3` when mount from `"@vue/test-utils": "^2.0.2",` 
causes the following error

```
 FAIL  src/components/HelloWorld.test.ts [ src/components/HelloWorld.test.ts ]
SyntaxError: Named export 'BaseTransition' not found. The requested module 'vue' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue';
const { transformVNodeArgs, Transition, BaseTransition, defineComponent, h, TransitionGroup, Teleport, nextTick, setDevtoolsHook, shallowReactive, reactive, isRef, createApp, computed } = pkg;
```

### Reproduction

Create a new vite project, install viteest 0.20.3 and @vue/test-utils any version.

Then create a new test file with the following

```
import { mount } from '@vue/test-utils';
import {
  expect, describe, it,
} from 'vitest';
import HelloWorld from './HelloWorld.vue';

describe('HelloWorld.vue', () => {
  it('should exist', async () => {
    expect(HelloWorld).toBeTruthy();
  });

  it('should display header text', async () => {
    const msg = 'HelloWorld';
    const wrapper = mount(HelloWorld, {
      props: {
        msg,
      },
    });
    expect(wrapper.find('h1').text()).toEqual(msg);
  });
});
```

This will cause the error.

Revert vitest to 0.19.1 and its working as expected.

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 977.92 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 91.0.2
    Safari: 14.1.1
  npmPackages:
    @vitejs/plugin-vue: ^3.0.0 => 3.0.1
    vite: ^3.0.0 => 3.0.4
    vitest: ^0.19.1 => 0.19.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-08-05 04:10
Duplicate of https://github.com/vitest-dev/vitest/issues/1753
See workaround there.

**Closed** 2022-08-07 11:30 UTC
Labels: duplicate
