### ISSUE TITLE
vitest fails if coverage is configured but disabled

### ISSUE THREAD

**Issue by nekrich** [vitest-dev/vitest#6444] opened 2024-09-03 08:16 UTC
### Describe the bug

If coverage is configured but disabled vitest fails and produces an error.

```
RUN  v2.0.5 /home/runner/work/pnpm_test/pnpm_test
[14](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:15)
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
[15](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:16)

[16](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:17)
Vitest caught 1 unhandled error during the test run.
[17](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:18)
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
[18](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:19)
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
[19](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:20)
TypeError: coverage.reporter.find is not a function
[20](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:21)
 ❯ node_modules/.pnpm/vitest@2.0.5/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:13975:46
[21](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:22)
 ❯ serializeConfig node_modules/.pnpm/vitest@2.0.5/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:13984:7
[22](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:23)
 ❯ WorkspaceProject.getSerializableConfig node_modules/.pnpm/vitest@2.0.5/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:14323:20
[23](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:24)
 ❯ getConfig node_modules/.pnpm/vitest@2.0.5/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:8425:33
[24](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:25)
 ❯ node_modules/.pnpm/vitest@2.0.5/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:8452:19
[25](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906#step:6:26)
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

### Reproduction

1. Create a new project.
2. Add vitest with configured coverage (checked with istanbul and v8).
3. Disable coverage.

Sample project: https://github.com/nekrich/pnpm_test .
As you can see from [commits](https://github.com/nekrich/pnpm_test/commits/main/):
1. When coverage is enabled vitest succeeded. [Workflow run](https://github.com/nekrich/pnpm_test/actions/runs/10679029603/job/29597349423).
2. Disabling action with [this commit](https://github.com/nekrich/pnpm_test/commit/3ed3081f27a5aa12cb5b34f71622c45dba51462e) leads to failure. [Failed Workflow run](https://github.com/nekrich/pnpm_test/actions/runs/10679047402/job/29597406906).

### System Info

```shell
System:
    OS: macOS 15.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 109.88 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.7.0 - ~/.local/share/mise/installs/node/22.7.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/mise/shims/yarn
    npm: 10.8.2 - ~/.local/share/mise/installs/node/22.7.0/bin/npm
    pnpm: 9.9.0 - ~/.local/share/mise/installs/pnpm/latest/bin/pnpm
  Browsers:
    Brave Browser: 128.1.69.160
    Chrome: 128.0.6613.120
    Safari: 18.0
  npmPackages:
    @vitest/coverage-istanbul: ^2.0.5 => 2.0.5
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2024-09-03 08:50
Duplicate of https://github.com/vitest-dev/vitest/issues/6260.

Use array in `reporter` until fix is released.

**Closed by AriPerkkio** 2024-09-03 08:50 UTC
Labels: pending triage
