### ISSUE TITLE
0.26.1 stops importing some packages

### ISSUE THREAD

**Issue by chetzof** [vitest-dev/vitest#2544] opened 2022-12-20 17:48 UTC
### Describe the bug

0.25.8 works well

```import { read } from 'fs-jetpack'```
Turns out to be empty when doing import destructuring. 
```import fs from 'fs-jetpack'```
Works fine.

```
[FAILED] __vite_ssr_import_2__.read is not a function
[FAILED] __vite_ssr_import_2__.read is not a function
[FAILED] __vite_ssr_import_2__.read is not a function
```

```TypeError: read is not a function```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-gv9cw4

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 333.16 MB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/Caches/fnm_multishells/25612_1671194505564/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/25612_1671194505564/bin/yarn
    npm: 8.19.3 - ~/Work/linktink/node_modules/.bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 106.0.5
    Safari: 16.1
    Safari Technology Preview: 16.4
  npmPackages:
    vitest: 0.25.8 => 0.26.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chetzof** [comment] 2022-12-20 17:54
`interopDefault: true,` from https://github.com/vitest-dev/vitest/issues/2531 fixes it, but I've assumed it was fixed in 0.26.0

**Comment by sergioalmela** [comment] 2022-12-20 18:12
Same with mkdirp: sync is not a function

**Comment by sheremet-va** [comment] 2022-12-20 19:31
This is expected behaviour since 0.26.0. `fs-jetpack` doesn't support named exports in Node environment. (you can see this by importing `import * as fs from fs-jetpack` - there are no named exports). If you have a Node bundler that fixes this, you can enable `interopDefault: true` yourself, as described in release notes: https://github.com/vitest-dev/vitest/releases/tag/v0.26.0. The error you will see when using named export:

```
file:///home/projects/vitest-dev-vitest-mjaqu6/node.mjs:1
import { read } from 'fs-jetpack';
         ^^^^
SyntaxError: Named export 'read' not found. The requested module 'fs-jetpack' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'fs-jetpack';
const { read } = pkg;

    at _instantiate (https://vitestdevvitestmjaqu6-vlyf.w-corp.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:6:986476)
    at <anonymous> (<anonymous>)
```

We can probably improve the default handling, if you have any suggestions. The decisions was made to drop auto interop in Node because this code will not actually work with native node.

**Comment by EvHaus** [comment] 2022-12-21 03:48
I'm having similar issues with `@reduxjs/toolkit` and `next-auth` packages. The following imports fail:

```ts
import {createAsyncThunk} from '@reduxjs/toolkit';

// and

import CredentialsProvider from 'next-auth/providers/credentials';
```

Vitest fails with:

```
TypeError: default is not a function
 ❯ pages/api/auth/[...nextauth].page.ts:74:3
     72|  },
     73|  providers: [
     74|   CredentialsProvider({
       |   ^
     75|    credentials: {
     76|     email: {
 ❯ utils/api/middleware/authentication.ts:1:31
 ❯ utils/api/middleware/index.ts:3:31

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/75]⎯

 FAIL  pages/api/report/[reportId]/build/GET.test.ts [ pages/api/report/[reportId]/build/GET.test.ts ]
 FAIL  pages/api/report/[reportId]/build/index.test.ts [ pages/api/report/[reportId]/build/index.test.ts ]
TypeError: createAsyncThunk is not a function
 ❯ Module.createAPIAction [as default] utils/redux/createAPIAction.ts:17:9
     15|  modifyResponse?: (response: Record<string, unknown>, payload: Input) …
     16| ) => {
     17|  return createAsyncThunk<Return, Input, {
       |         ^
     18|   dispatch: DispatchType,
     19|   rejectedMeta: ErrorReturnType,
 ❯ store/componentsActions.ts:41:23

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/75]⎯
```

I checked and both of those packages have the appropriate exports (from what I can tell). Rolling back to vitest 0.25.8 makes the problem go away.

I'm not sure what `interopDefault` is. I can't find any docs for it. Is that a `vite` setting?

**Comment by sheremet-va** [comment] 2022-12-21 06:16
> I'm not sure what `interopDefault` is. I can't find any docs for it. Is that a `vite` setting?

https://vitest.dev/config/#deps-interopdefault

**Comment by capaj** [comment] 2022-12-21 09:18
I as having this issue with lodash and this import:
```ts
import { get } from 'lodash'
```

 adding `deps: {
      interopDefault: true,
    },`

fixed it. Isn't it high time that lodash exports ESM modules @jdalton ?

**Comment by sheremet-va** [comment] 2022-12-21 10:51
> I was having this issue with lodash and this import:
> 
> ```ts
> 
> import { get } from 'lodash'
> 
> ```
> 
> 
> 
>  adding `deps: {
> 
>       interopDefault: true,
> 
>     },`
> 
> 
> 
> fixed it. Isn't it high time that lodash exports ESM modules @jdalton ?

I think there is `lodash-es` module for this?

**Comment by capaj** [comment] 2022-12-21 11:19
yes, `lodash-es` fixes it and there is no need for interopDefault: true

**Comment by paescuj** [comment] 2022-12-22 00:50
A bit confusing though that according to the [docs](https://vitest.dev/config/#deps-interopdefault) `interopDefault` defaults to `true` but this doesn't seem to be the case.

In fact, `configDefaults` doesn't contain `deps` at all...

**Comment by sheremet-va** [comment] 2022-12-22 06:37
> A bit confusing though that according to the [docs](https://vitest.dev/config/#deps-interopdefault) `interopDefault` defaults to `true` but that doesn't seem to be the case.

This is error in Docs, it will be fixed.

> In fact, configDefaults doesn't contain deps at all...

It cannot be on `configDefaults`, because default is dynamic and depends on environment.

**Closed** 2022-12-23 17:43 UTC
