### ISSUE TITLE
Vitest shows cryptic chars in Jenkins

### ISSUE THREAD

**Issue by MatthiasGwiozda** [vitest-dev/vitest#2204] opened 2022-10-24 12:59 UTC
### Describe the bug

**Current Behavior**
When running vitest in Jenkins, it looks like this:

![image](https://user-images.githubusercontent.com/22172694/197519409-ee0e4234-937a-47f0-bca4-2af6b5487fd5.png)

**Expected Behavior**
This is how it looks locally:
![image](https://user-images.githubusercontent.com/22172694/197519618-97d55459-f7e8-408b-bc42-3763e699eb2b.png)

**What i tried**
- Configure another reporter.
--> tap-flat and json is okay - but they are not nicely human readable 😐
- Configure the Jenkins Terminal to use another encoding
--> Unfortunately im still trying to figure out how to do this. It's very time - consuming

**Context**
- On StackOverflow somebody else has the same issue: https://stackoverflow.com/questions/72549751/plain-text-reporter-for-vitest

### Reproduction

- Create a test with vitest
- Create a Jenkins - Pipeline with the following Jenkinsfile
```
pipeline {
    agent any
    stages {
        stage('test') {
            agent {
                docker {
                    image 'node:16.17.0'
                    reuseNode true
                }
            }
            environment {
                 HOME = '.'
            }
            steps {
                sh 'npm install'
                sh 'npm run test'
            }
        }
    }
}
```
- Run the Jenkins - Job

### System Info

```shell
Jenkins (Taken from System Properties in the Jenkins - UI):
- OS: Linux 
- OS - Version: 5.15.0-1022-azure
- file.encoding: UTF-8



Local:

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz    
    Memory: 4.66 GB / 15.90 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 106.0.5249.103
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-vue: ^3.1.0 => 3.1.2 
    vite: ^3.1.1 => 3.1.8 
    vitest: ^0.24.0 => 0.24.3
```

### Used Package Manager

npm

**Comment by Demivan** [comment] 2022-10-24 17:18
Duplicate of https://github.com/vitest-dev/vitest/issues/841

**Closed by Demivan** 2022-10-24 17:18 UTC

**Comment by MatthiasGwiozda** [comment] 2022-10-25 05:45
@Demivan thanks! I can confirm, that NO_COLOR solved the problem.

If someone else needs more explanation on how to solve it in Jenkins, you can find it here:
https://stackoverflow.com/a/74189519/6458608
