### ISSUE TITLE
Output in browser is not escaped

### ISSUE THREAD

**Issue by Artur-** [vitest-dev/vitest#4496] opened 2023-11-14 06:45 UTC
### Describe the bug

```
expect('myscript').to.equal("<script>window.alert('hello')</script>");
```

does not cause an injection problem but in the browser UI it shows up as
```
- Expected
+ Received

- 
+ myscript
```

when the expected would be
```
- Expected
+ Received

- <script>window.alert('hello')
+ myscript
```

### Reproduction

as above

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 1004.30 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    bun: 1.0.7 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 107.1.45.123
    Chrome: 119.0.6045.123
    Chrome Canary: 121.0.6125.0
    Edge: 119.0.2151.58
    Safari: 17.0
  npmPackages:
    @vitejs/plugin-react: 4.1.1 => 4.1.1 
    @vitest/browser: ^0.34.6 => 0.34.6 
    @vitest/ui: ^0.34.6 => 0.34.6 
    vite: 4.5.0 => 4.5.0 
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-11-14 12:46
Duplicate of #1279

**Closed by sheremet-va** 2023-11-14 12:46 UTC
Labels: pending triage
