### ISSUE TITLE
File FormData Request missing file contents in body (jsdom)

### ISSUE THREAD

**Issue by LarsJK** [vitest-dev/vitest#7080] opened 2024-12-13 14:07 UTC
### Describe the bug

When creating a request with FormData containing a File, the contents of the file is missing from the Request body.

```
------formdata-undici-079763235294
Content-Disposition: form-data; name="file"; filename="hello.json"
Content-Type: application/json


------formdata-undici-079763235294--
```
 
This also seems to cause a hang on linux when trying to read the request body.

This only happens with jsdom env. Cross posting this issue here as I'm not sure if this is a jsdom issue or an issue with the way vitest sets up jsdom env.

jsdom/jsdom#3800

### Reproduction

```js
// @vitest-environment jsdom

import { test, expect } from "vitest";

test("form data file", async () => {
  const file = new File(["{}"], "hello.json", { type: "application/json" });
  const formData = new FormData();
  formData.append("file", file);

  const request = new Request("http://localhost:3000", {
    method: "POST",
    body: formData,
  });

  const text = await request.text();

  console.log(text);

  expect(formData.get("file")).toBeDefined();
});
```

I have also set up a minimal example that sets up jsdom the way vitest does it without actually using vitest which might be helpful to understand what causes the issue.

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);

async function main() {
  const fileContent = '{ "hello": "world" }';
  const file = new dom.window.File([fileContent], "hello.json", {
    type: "application/json",
  });
  const formData = new dom.window.FormData();
  formData.append("file", file);

  const request = new Request(
    "http://localhost:3000",
    {
      method: "POST",
      body: formData,
      headers: {
        "Content-Type": "multipart/form-data",
      },
    },
    {
      headers: {
        "Content-Type": "multipart/form-data",
      },
    }
  );

  const text = await request.text();

  console.log(text.includes(fileContent));  // false
}

main();
```

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 73.17 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Firefox Developer Edition: 134.0
    Safari: 18.1.1
    Safari Technology Preview: 18.2
  npmPackages:
    @vitejs/plugin-react: ^4.3.3 => 4.3.3 
    @vitest/coverage-v8: ^2.1.4 => 2.1.4 
    @vitest/ui: 2.1.4 => 2.1.4 
    vite: ^5.4.10 => 5.4.10 
    vitest: ^2.1.4 => 2.1.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment] 2024-12-14 01:09
This is a duplicate of https://github.com/vitest-dev/vitest/issues/5672

**Closed by hi-ogawa** 2024-12-14 01:09 UTC
Labels: pending triage
