### ISSUE TITLE
Wrong coverage when using isolate: false

### ISSUE THREAD

**Issue by RodrigoFerretti** [vitest-dev/vitest#6736] opened 2024-10-17 23:25 UTC
### Describe the bug

This is the same bug as mentioned in https://github.com/vitest-dev/vitest/issues/3846, but now with minimal reproduction.

I've read somewhere that vitest orders the execution by the file's size, descending.

The coverage is ignored for the smaller tests when the method being tested is called in one of the "setupFiles" configured, even though everything should be covered

### Reproduction

https://github.com/RodrigoFerretti/vitest-coverage-w-isolate

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 5.28 GB / 15.23 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.22 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 127.0.6533.72
  npmPackages:
    @vitest/coverage-v8: 2.0.3 => 2.0.3 
    vite: 5.3.4 => 5.3.4 
    vitest: 2.0.3 => 2.0.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2024-10-21 11:26
Does this happen when setup files are not importing source files?

**Comment by RodrigoFerretti** [comment] 2024-10-22 14:17
@AriPerkkio Removing the "multiply" function from the "setup.ts" file fixes the problem for this reproduction code, but it is impossible for me to do something like this in the project I am working on. I kept the isolate true option to keep the coverage, even though the tests take longer like this.

**Comment by AriPerkkio** [comment] 2024-10-22 14:35
Thanks for checking. It helps us debugging when we can narrow down the required conditions to "`setupFiles` + `isolate: false`" only.

**Comment by RodrigoFerretti** [comment] 2024-10-29 15:46
Hi! Any updates on this? Is there any way I can help? I really would like to use `isolate:false` to speed up the test run.

**Comment by AriPerkkio** [comment] 2024-10-29 15:51
On `@vitest/coverage-istanbul` the root cause is here. We shouldn't remove the files from coverage object, instead reset all counters to `0`.

https://github.com/vitest-dev/vitest/blob/8878b04dcef5d6bdcbb6a6874f944a8bc8d278e1/packages/coverage-istanbul/src/index.ts#L18-L20

On `@vitest/coverage-v8` there's something weird going on. I spent couple of hours debugging it but didn't yet find root cause or could reproduce the issue outside Vitest.

**Comment by AriPerkkio** [comment] 2024-10-30 07:08
And `@vitest/coverage-v8` works fine with `isolate: false`, as long as `setupFiles` are not imporing the source files. You could try some work-arounds there in your project, if possible. 

Need to check if we are running setupFiles outside `vite-node`'s `node:vm`, directly on NodeJS. That could confuse V8's profiler like this, as the filename remains same but executed content is different. 🤔

**Comment by AriPerkkio** [comment] 2024-11-19 15:31
Branches are merged wrong here:

https://github.com/vitest-dev/vitest/blob/3971ab7ea25142fef589723a42befa89a0cd18fe/packages/coverage-v8/src/provider.ts#L70

These reports

```
"ranges": [
   {
    "startOffset": 200,
    "endOffset": 355,
    "count": 1
   },
  {
    "startOffset": 231,
    "endOffset": 273,
    "count": 0
  }
],

"ranges": [
  {
    "startOffset": 200,
    "endOffset": 355,
    "count": 3
  }
],
```

Become 

```
"ranges": [
  {
    "startOffset": 200,
    "endOffset": 355,
    "count": 1
  },
  {
    "startOffset": 231,
    "endOffset": 273,
    "count": 0
  }
]
```

This might be just limitation of https://issues.chromium.org/issues/42200042. We should rewrite whole V8 reporting ourselves to fix this.

**Comment by AriPerkkio** [comment] 2024-11-24 09:12
@RodrigoFerretti could you try if this preview release works correctly in your project?

```json
{
  "devDependencies": {
    "@vitest/coverage-v8": "https://pkg.pr.new/@vitest/coverage-v8@6957",
    "vitest": "https://pkg.pr.new/vitest@6957"
  }
}
```

https://github.com/vitest-dev/vitest/pull/6957#issuecomment-2495878654

**Comment by Mr-Guilherme** [comment] 2024-12-03 12:52
@AriPerkkio I'm having the same issue in my project to speed up the test run. So, I installed this preview release and works very well here, the coverage up to 100% without problems.

**Comment by RodrigoFerretti** [comment] 2024-12-06 22:10
The logs on the console while the tests were running were a bit different, but I am going to assume this is ok. 

### Test 1

My current setup, with wrong coverage

```
isolate: false
"@vitest/coverage-v8": "2.0.3"
"vitest": "2.0.3"
```

![image](https://github.com/user-attachments/assets/ad534884-9f6b-41df-b8c6-0b97ed0980b9)

### Test 2

Using the previews, with right coverage

```
isolate: false
"@vitest/coverage-v8": "https://pkg.pr.new/@vitest/coverage-v8@6957"
"vitest": "https://pkg.pr.new/vitest@6957"
```

![image](https://github.com/user-attachments/assets/e90c29de-d535-453c-b0c2-ce8699a1f7d2)

**Comment by RodrigoFerretti** [comment] 2024-12-06 22:10
@AriPerkkio Sorry for the delay

**Comment by AriPerkkio** [comment] 2024-12-09 07:57
Thanks for verifying the preview release @Mr-Guilherme and @RodrigoFerretti. Let's proceed with this fix in https://github.com/vitest-dev/vitest/pull/6957.

**Closed** 2024-12-09 11:41 UTC
Labels: feat: coverage, p3-minor-bug

**Comment by RodrigoFerretti** [comment] 2024-12-16 15:11
Hello @AriPerkkio!
I see that you merged https://github.com/vitest-dev/vitest/pull/6957 into [vitest-dev:main](https://github.com/vitest-dev/vitest/tree/main).
The fix is available to install? If it is not, do you have an estimate date or something?
Thanks!
