### ISSUE TITLE
since version 0.31.0 vite-node throws "Maximum call stack size exceeded" when importing inquirer

### ISSUE THREAD

**Issue by raythurnevoid** [vitest-dev/vitest#3520] opened 2023-06-05 15:16 UTC
### Describe the bug

When importing: `import inquirer from 'inquirer';`

```
RangeError: Maximum call stack size exceeded
    at Object (<anonymous>)
    at Module.isPrimitive (file://file:///home/projects/stackblitz-starters-huwg4w/node_modules/vite-node/dist/utils.mjs:60:16)
    at Object.set (file://file:///home/projects/stackblitz-starters-huwg4w/node_modules/vite-node/dist/client.mjs:285:24)
    at Object.set (file://file:///home/projects/stackblitz-starters-huwg4w/node_modules/vite-node/dist/client.mjs:289:28)
    at Object.set (file://file:///home/projects/stackblitz-starters-huwg4w/node_modules/vite-node/dist/client.mjs:289:28)
    at Object.set (file://file:///home/projects/stackblitz-starters-huwg4w/node_modules/vite-node/dist/client.mjs:289:28)
    at Object.set (file://file:///home/projects/stackblitz-starters-huwg4w/node_modules/vite-node/dist/client.mjs:289:28)
    at Object.set (file://file:///home/projects/stackblitz-starters-huwg4w/node_modules/vite-node/dist/client.mjs:289:28)
    at Object.set (file://file:///home/projects/stackblitz-starters-huwg4w/node_modules/vite-node/dist/client.mjs:289:28)
    at Object.set (file://file:///home/projects/stackblitz-starters-huwg4w/node_modules/vite-node/dist/client.mjs:289:28)
```

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-huwg4w

`npm i && npm start`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-06-05 15:20
Duplicate of #3519

**Closed by sheremet-va** 2023-06-05 15:20 UTC
Labels: pending triage
