### ISSUE TITLE
`pool: vmThreads` breaks source maps in tests

### ISSUE THREAD

**Issue by sambev** [vitest-dev/vitest#5118] opened 2024-02-05 20:49 UTC
### Describe the bug

When using `vmThreads` instead of `threads` (or the default), source maps seem to break while running the tests.

Small repro: https://github.com/sambev/vmthread-sourcemap-repro

With `pool: 'threads'`, reporting works as expected
```
 FAIL  src/__tests__/sum.test.ts > sum
TypeError: Cannot set properties of undefined (setting 'name')
 ❯ Module.sum src/sum.ts:7:12
      5|
      6| export function sum(items: Item[]): number {
      7|   items[3].name = "break!";
       |            ^
      8|   return items.reduce((acc, item) => acc + item.count, 0);
      9| }
 ❯ src/__tests__/sum.test.ts:10:10
```

With `pool: 'vmThreads'`, reporting is wrong:
```
  FAIL  src/__tests__/sum.test.ts > sum
TypeError: Cannot set properties of undefined (setting 'name')
 ❯ Module.sum src/sum.ts:2:17
      1| interface Item {
      2|   name: string;
       |                 ^
      3|   count: number;
      4| }
 ❯ src/__tests__/sum.test.ts:10:54
```

### Reproduction

I have made a simple reproduction app based on the `vanilla-ts` vite template here:

https://github.com/sambev/vmthread-sourcemap-repro

All you should have to do is install deps (`yarn install`) and run tests (`yarn test`)

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 86.81 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/18.12.1/bin/npm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.3
  npmPackages:
    vite: ^5.0.8 => 5.0.12
    vitest: ^1.2.2 => 1.2.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment] 2024-02-05 23:27
This is expected to be fixed by https://github.com/vitest-dev/vitest/pull/5063 (it's not released yet but probably soon). The issue is previously reported in https://github.com/vitest-dev/vitest/issues/5058 as inline snapshot bugs, but the underlying issue should be same.

I just updated the previous issue's title to mention source map, so it's easier for people to find a duplicate. Sorry about the confusion.

**Closed by hi-ogawa** 2024-02-05 23:27 UTC
Labels: pending triage
