### ISSUE TITLE
Problem testing typescript application that uses piscina

### ISSUE THREAD

**Issue by RodrigoFerretti** [vitest-dev/vitest#6040] opened 2024-07-05 18:49 UTC
### Describe the bug

I'm currently trying to integrate piscina into an application and noticed that it is struggling to work while running vitest. What I understood from it is that, while running ts-node-dev, the `require(filename)` inside piscina's code work as expected, but not with vitest. Is there something I'm missing? 

Here is the piscina's reaction while running ts-node-dev:
![image](https://github.com/vitest-dev/vitest/assets/74201114/17b82e99-029b-4fab-b5cf-e9d2f9727fde)

And here is piscina's reaction while running vitest
![image](https://github.com/vitest-dev/vitest/assets/74201114/60dc87c1-edc3-4e0f-b407-4218cf136903)

### Reproduction

tsconfig.json looks like this:

```json
{
    "buildOptions": {
        "verbose": true
    },
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "alwaysStrict": true,
        "composite": false,
        "downlevelIteration": true,
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "lib": ["ESNext"],
        "moduleResolution": "Node",
        "noErrorTruncation": false,
        "noFallthroughCasesInSwitch": true,
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "outDir": "./build",
        "preserveConstEnums": true,
        "skipDefaultLibCheck": true,
        "skipLibCheck": true,
        "strict": true,
        "strictBindCallApply": true,
        "strictFunctionTypes": true,
        "strictNullChecks": true,
        "strictPropertyInitialization": true,
        "target": "ESNext",
        "module": "CommonJS",
        "types": ["vitest/globals"],
        "useUnknownInCatchVariables": true,
        "resolveJsonModule": true,
        "sourceMap": true,
        "declaration": true,
        "paths": {
            "@lib/*": ["./src/lib/*"],
            "@streams/*": ["./src/streams/*"]
        }
    },
    "include": ["./src", "./tests"],
    "files": ["src/global.d.ts"]
}
```

vitest.config.mts

```mts
import { PluginOption } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import { defineConfig } from "vitest/config";

const plugins: PluginOption[] = [tsconfigPaths()];

export default defineConfig({
  plugins,
  test: {
    logHeapUsage: true,
    allowOnly: true,
    silent: false,
    globals: true,
    mockReset: true,
    clearMocks: true,
    hookTimeout: 60_000,
    testTimeout: 10_000,
    coverage: {
      all: true,
      include: ["src/**"],
      exclude: ["src/index.ts", "src/global.d.ts", "src/openapi.ts"],
      thresholds: {
        branches: 99,
        lines: 99,
        functions: 99,
        statements: 99,
      },
    },
  },
});
```

package.json snippet

```json
{
    "scripts": {
        "dev": "ts-node-dev --respawn -r tsconfig-paths/register -r dotenv/config ./src/index.ts",
        "test": "yarn docker:up && yarn vitest run --dir ./tests --coverage"
    }
}
```

Using piscina:

```ts
import { Piscina } from "piscina";
import { Webhook } from "../webhook";

export const webhookIds = new Set();
export const webhookPool = new Piscina({ filename: Webhook.fileName });
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 4.28 GB / 15.23 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.22 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 125.0.6422.141
  npmPackages:
    @vitest/coverage-v8: 1.6.0 => 1.6.0 
    vitest: 1.6.0 => 1.6.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2024-07-06 07:28
```
├── src
│   └── worker.js
└── test
    └── piscina.test.ts
```

![image](https://github.com/vitest-dev/vitest/assets/14806298/0320b92a-8be1-44c6-9ae9-8203d0cedd7e)

**Comment by RodrigoFerretti** [comment] 2024-07-09 15:06
Here is the [repo for reproduction](https://github.com/RodrigoFerretti/vitest-piscina).
Running `yarn dev` works fine. 
Running `yarn test` breaks with the error mentioned

**Comment by JoshHiles** [comment] 2024-07-09 22:02
I have what seems to be a similar issue, different error message but i think related
[https://github.com/JoshHiles/vitest-piscina](https://github.com/JoshHiles/vitest-piscina)
I get back this
```
(node:30204) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
```
and then it hangs

**Comment by AriPerkkio** [comment] 2024-07-10 07:56
Duplicate of https://github.com/vitest-dev/vitest/issues/3234.

The reproductions are trying to load `.ts` file using `node:worker_threads` - Node does not support this. The `"dev": "ts-node-dev --respawn -r dotenv/config ./src/index.ts"` is not equivalent to your test case as it's using `ts-node-dev`.

I'm not sure how `ts-node-dev` could be used as loader, but at least with `tsx` you could use following:

```diff
export const webhookPool = new Piscina({
  filename: Webhook.fileName,
+ execArgv: process.env.VITEST ? ["--import", "tsx"] : undefined,
});
```

**Closed by AriPerkkio** 2024-07-10 07:56 UTC
Labels: pending triage

**Comment by RodrigoFerretti** [comment] 2024-07-10 19:21
It worked! I've added the line and installed tsx using `yarn add --dev tsx`. Thanks a lot!!
