### ISSUE TITLE
`src/test.ts` is picked up as a test

### ISSUE THREAD

**Issue by danielroe** [vitest-dev/vitest#3530] opened 2023-06-06 21:55 UTC
### Describe the bug

This may not be a bug but I would consider it non-intuitive.

A file named `src/test.ts` is picked up as a test. I would suggest that `test.ts` should be required as a suffix rather than directly as a file name.

**Context**:
Our CI started failing because we have a `test` command in our source code: https://github.com/nuxt/nuxt/actions/runs/5193588330/jobs/9364317315?pr=21410

Introduced in glob changes in https://github.com/vitest-dev/vitest/pull/3392.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-e9txbr?file=test.ts,test/basic.test.ts&initialPath=__vitest__/

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @vitest/ui: latest => 0.32.0 
    vite: latest => 4.3.9 
    vitest: latest => 0.32.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-06-07 06:17
Our new patterns don't actually align with Jest 100%: 🤔 

Jest:

```
**/?(*.)+(spec|test).[jt]s?(x)
```

Vitest:

```
**/?(*.)(spec|test).[jt]s?(x)
```

**Comment by Ky6uk** [comment] 2023-06-07 08:12
How to exclude files now? I had `test.exclude` in the `vite.config.ts` before `v0.32`, but it seems doesn't work anymore. I'm trying to exclude `'src/**/__tests__/*.cy.ts'` files that had been used for Cypress, but they're picked by Vitest.

**Comment by Ky6uk** [comment] 2023-06-07 08:27
Ahh, my bad. Just checked it closely and exclude was under `test.coverage`, not just `test` in the config file. All good now. 👍

**Comment by deluksic** [comment] 2023-06-09 11:18
In our codebase, switching to `v0.32.0` started running `__tests__/testHelper.ts` as a test and it fails due to `No test suite found`

**Comment by sheremet-va** [comment] 2023-06-09 11:23
> EDIT: setting `include: ["**/*.{test,spec}.?(c|m)[jt]s?(x)"]` which is the default according to the `include` docstring, helps

I don't know what documentation you are reading but in 0.32.0 the default is this:

```
'**/__tests__/**/*.?(c|m)[jt]s?(x)', '**/?(*.){test,spec}.?(c|m)[jt]s?(x)'
```

**Comment by sheremet-va** [comment] 2023-06-09 11:24
This is an expected breaking change which is described in the release notes.

**Comment by deluksic** [comment] 2023-06-09 11:26
<img width="540" alt="image" src="https://github.com/vitest-dev/vitest/assets/4405627/a922d62b-c5e0-428a-b1a5-f51d0957871f">

I understand this is not official docs, but it should probably updated here as well. This `.d.ts` file is distributed with `0.32.0`.

**Comment by nickmccurdy** [comment] 2023-06-10 04:37
> Our new patterns don't actually align with Jest 100%: 🤔
> 
> Jest:
> 
> ```
> **/?(*.)+(spec|test).[jt]s?(x)
> ```
> 
> Vitest:
> 
> ```
> **/?(*.)(spec|test).[jt]s?(x)
> ```
> 

@sheremet-va It seems like our glob parser allows `.` literals in `*` matches, as `one.two.test.js` is correctly run by both Vitest and Jest. So they should be functionally identical.

> But it is still expected change, since the same happens in Jest: https://jestjs.io/docs/configuration#testmatch-arraystring
> 
> > It will also find files called `test.js` or `spec.js`.

@sheremet-va is right, picking up files named `test` was done by me intentionally in #3392 for Jest support. You can still use the old Vitest config if you have files that aren't tests named `test`, though I'd recommend eventually fixing this in your code so other Vitest and Jest users don't get unrelated files confused with test files.

**Comment by danielroe** [comment] 2023-06-10 06:17
Honestly, when I used jest I never named or even considered naming a test file `src/test.ts`.

I still think it is counter intuitive and would advise against supporting this pattern. In general one thing I love about vitest is how zero configuration it is, which is why I raised the issue in the first place. Good defaults/conventions matter.

But it is totally up to you. I will just be adding the pattern to our exclude array. Renaming the file in our own context would be be more confusing.

**Comment by sheremet-va** [comment] 2023-06-13 13:24
> I think the fact that jest had to have a separate sentence explaining that this was the case is a sign of a non intuitive pattern. In general one thing I love about vitest is how zero configuration it is, which is why I raised the issue in the first place. Good defaults/conventions matter.

I am open to discussing the best course of action here. I do agree that the pattern seems non-intuitive. We can revert the `test.ts` change if people want to.

On the same note, I think Vitest team should reevaluate what we mean by Jest compatibility and make a paragraph in docs about this. People's requests are getting ridiculous by this point - adding features just because "they work like this in jest, makes for easier migration, and so on".

**Comment by nickmccurdy** [comment] 2023-06-14 01:46
As someone who's used Jest for years, I've often used `test.js` files to demo it in projects with just one test file, and I also think it's a useful pattern for higher level tests like e2e tests and type tests that involve an entire codebase. Several times I've created `test.js` files and wondered why Vitest wasn't running them, assuming it wasn't working properly. It's also very similar to the `*.test.js` pattern that Vitest already supported.

Can we please start by documenting this change and waiting for more feedback? While I respect the concerns of other maintainers around back compatibility, we did release this as backward incompatible, and I'd rather not revert this change for something I'd consider to be more of a project-specific compatibility issue, when it's something other Jest users would expect. In Nuxt's case, I think modifying Vitest's includes or excludes would be the best solution.

**Comment by so1ve** [comment] 2023-06-18 10:56
I really hate this change :( Using test or spec as a suffix to identify the test files is intuitive, like what `d.ts` does.

`test.ts` is too common. Sometimes we create a `test.js` file to debug locally, vitest is unhappy; If some frameworks have a `src/test.ts` file to run tests in user's workspace, vitest is unhappy. After all, `test.ts` is not special enough to identify whether a file is a spec file. I'm glad to see vitest team is open to revert this change.

**Comment by nickmccurdy** [comment] 2023-06-19 13:03
Personally as a Jest user, I find assuming a `test.ts` file is a test more intuitive. I understand that perspective though, which is why I'm still in favor of documenting it more clearly.

> If some frameworks have a `src/test.ts` file to run tests in user's workspace, vitest is unhappy.

Do you have an example of this? Specifically I'm interested in knowing if any frameworks have their own `test.js` file that wouldn't be compatible with Jest/Vitest APIs.

**Comment by so1ve** [comment] 2023-06-19 13:12
> Do you have an example of this?

I can't figure out an example right now, sorry :(
However, I think many developers create a test.js/ts file locally to test their library.

**Comment by posva** [comment] 2023-07-03 12:46
It's very common for codebases to have mocks and other test utilities within the tests folders, they shouldn't be picked up. [Right now even a file named `utils.ts`](https://stackblitz.com/edit/vitest-dev-vitest-w6dj3h?file=__tests__%2Futils.ts) is picked up, it's not just files named `test`.

Including only spec, or test files is a better default for any project, small or big because it enforces a helpful, longstanding convention that, by default, filters out non-test files. In other words, **the previous behavior was sensitive default** that encouraged better organization practices. Because of this I really think reverting this change would be beneficial for all vitest users

**Comment by so1ve** [comment] 2023-07-03 12:58
I've created a draft PR for this, you can merge it once this suggestion is accepted, or simply close it :)

**Comment by so1ve** [comment] 2023-07-03 13:06
I guess we can partially revert it because it still has quite a few parts worth keeping, such as simplified globs.

**Comment by nickmccurdy** [comment] 2023-07-04 10:40
While I'm still open to discussion on this change, can we please publish docs on these changes to explain them better before deciding to revert work and publish another breaking change? I agreed to add docs previously, and at the time I didn't realize this was being published without docs. Additionally, this issue still has the labels of a documentation fix, not a breaking change. I'm also opening #3731 to attempt to resolve the original issue with docs.

**Comment by posva** [comment] 2023-07-04 12:02
Personally (but I think I’m not the only one) my problem is not about docs, my problem is the new default is worse than the previous one for the mentioned reasons.

It’s not about labeling either, those are just organizational details. As an example: you could label this as a regression and a fix if you wanted to but what matter is not that it breaks, all software does and that’s just fine. What matter is that a sensitive default is adopted (or rather restored)

**Comment by antfu** [comment] 2023-07-04 15:23
I wasn't aware of the initial PR. Here are my thoughts:

- As most of us here agree with the fact that this default is counter-intuitive, I think we should revert it in the next breaking changes.
- As for "Jest-compactible", to me is something "good to have" rather than following everything with Jest. We do have quite a few misalignments with Jest, that we have noted in the migration guide, so, in this case, I think we should document in the migration note that our defaults are different instead of another way around. As ppl would check the docs carefully on migrations, but not day-to-day use, especially considering this is counter-intuitive.

To make a trade-off, we could introduce a preset system, or just a bare Jest-favor default object that makes for easier opt-in. Something like:

```ts
import { defaultJestConfig } from 'vitest'

export default defineConfig({
  test: {
    ...defaultJestConfig,
	// user configs
  }
}
```

**Closed** 2023-07-06 14:00 UTC
Labels: bug, documentation
