### ISSUE TITLE
FATAL ERROR: v8::FromJust Maybe value is Nothing.

### ISSUE THREAD

**Issue by sysmat** [vitest-dev/vitest#1821] opened 2022-08-08 05:55 UTC
### Describe the bug

> vitest run

 RUN  v0.21.0 C:/Users/tomaz/Projekti/Gitlab_Arnes/portal-hub/typescript-portal-libs/aris-jwt-model

 ✓ tests/profile-jwt.test.ts (4)
 ✓ tests/service-jwt.test.ts (1)
 ✓ tests/org-jwt.test.ts (1)    
 ✓ tests/jwt-token.test.ts (1)  

Test Files  4 passed (4)        
     Tests  7 passed (7)        
  Start at  07:52:13
  Duration  8.68s (setup 0ms, collect 1.36s, tests 119ms)

close timed out after 1000ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 00007FF7CB537B7F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114079
 2: 00007FF7CB4C4546 DSA_meth_get_flags+65542
 3: 00007FF7CB4C53FD node::OnFatalError+301
 4: 00007FF7CBDE5CA5 v8::V8::FromJustIsNothing+53
 5: 00007FF7CB4AD533 v8::base::CPU::has_sse+31507
 6: 00007FF7CB59AAF7 uv_timer_stop+1207
 7: 00007FF7CB59708B uv_async_send+331
 8: 00007FF7CB59681C uv_loop_init+1292
 9: 00007FF7CB5969BA uv_run+202
10: 00007FF7CB565825 node::SpinEventLoop+309
11: 00007FF7CB3FD000 v8::internal::interpreter::BytecodeLabel::bind+35776
12: 00007FF7CB3F8658 v8::internal::interpreter::BytecodeLabel::bind+16920
13: 00007FF7CB58708D uv_poll_stop+557
14: 00007FF7CC3A01D0 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
15: 00007FFA40747034 BaseThreadInitThunk+20
16: 00007FFA41662651 RtlUserThreadStart+33

### Reproduction

simple test

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.58 GB / 31.75 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.79
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitest: ^0.21.0 => 0.21.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-08-08 06:11
Duplicate of https://github.com/vitest-dev/vitest/issues/1191

**Closed by sheremet-va** 2022-08-08 06:11 UTC
