### ISSUE TITLE
Test Collection Slow

### ISSUE THREAD

**Issue by mikearnaldi** [vitest-dev/vitest#1844] opened 2022-08-12 09:48 UTC
### Describe the bug

We have a fairly large set of tests in Effect-TS, we progressively witnessed increasing slowness in tests and for a while we blindly imputed the reason to be the growing system. After taking a closer look we realized that the collection phase started to take ages and that our tests were running at the same speed as before. After rolling back to `0.14.2` we gained a speedup of about 35/40% in total test time, the perf starts to progressively deteriorate in `0.15` with a big cliff in `0.18`.

![unknown](https://user-images.githubusercontent.com/24249610/184329141-e50cc2a8-b532-44fa-8d57-c33e8141c142.png)

vs

![Screenshot 2022-08-12 104515](https://user-images.githubusercontent.com/24249610/184329312-7e0382fc-013f-4ab3-8bc9-0a66585eb91c.png)

### Reproduction

The issue gets worse as the number of tests grows, clone https://github.com/Effect-TS/core and run `yarn && yarn build-all && yarn test`

### System Info

```shell
Multiple, tested on Mac M1, Linux (github actions), Windows WSL2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jf-paradis** [comment] 2022-08-13 05:41
Very interesting. We're considering moving to Vitest but performance is still an issue.

**Comment by sheremet-va** [comment] 2022-08-16 07:11
In your case the problem is `maxConcurrency` introduced in [`0.15.0` (release)](https://github.com/vitest-dev/vitest/releases/tag/v0.15.0). Before that we didn't have a cap. Increase the value and your tests will once again run faster.

**Closed by sheremet-va** 2022-08-16 07:11 UTC
Labels: bug
