### ISSUE TITLE
jsxImportSource not work in jsdom enviroment with local files

### ISSUE THREAD

**Issue by utftu** [vitest-dev/vitest#4141] opened 2023-09-18 20:37 UTC
### Describe the bug

`jsxImportSource` option in `@vitejs/plugin-react` not work with local files with jsdom, happy-dom etc starting from version 0.34. There is error `Error: Failed to resolve import "./src/jsx/jsx-dev-runtime"`. To fix this error you can
1) install `vitest` 0.33
2) remove `// @vitest-environment jsdom`

### Reproduction

https://github.com/utftu/vitest-jsx

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
Binaries:
    Node: 20.3.0 - ~/.nvm/versions/node/v20.3.0/bin/node
    pnpm: 8.7.1 - /opt/homebrew/bin/pnpm
Browsers:
    Chrome Canary: 114
npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4 
    vite: ^4.4.9 => 4.4.9 
    vitest: ^0.34.4 => 0.34.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Codex-** [comment] 2023-09-29 03:57
Also encountering this issue, removing `jsxImportSource` works but interestingly it also works with the latest vitest if you roll back `@vitejs/plugin-react` to `4.0.4`

I think I have a fix though, working on a reproduction and a pr at the moment

**Comment by hi-ogawa** [comment] 2024-01-12 03:14
It looks like there was some change around `transformMode` in https://github.com/vitest-dev/vitest/releases/tag/v0.34.0

Probably the reason why `"remove // @vitest-environment jsdom"` works is that, the bad import `"./src/jsx/jsx-dev-runtime"` is injected by some babel transform only for "web" transform but not for "ssr" (probably related to react hmr).

Forcing `test.testTransformMode.ssr` to avoid apply such transform might be a way to go back to the previous behavior:
https://stackblitz.com/edit/github-c58amn-3cbmnq?file=vite.config.ts

---

From a different point of view, I think more robust way to mitigate this issue is to avoid relative path for custom jsx runtime since you don't know how it will be injected by babel transform. Probably this is somewhat analogical to how `alias` works https://vitest.dev/guide/common-errors.html, so I think it's better to use absolute path for this case `new URL('./src/jsx', import.meta.url).pathname`

https://stackblitz.com/edit/github-c58amn-wfeq4e?file=vite.config.ts

**Comment by sheremet-va** [comment] 2024-01-12 09:55
@hi-ogawa is correct. The plugin just injects the string without resolving it. Don't use relative paths.

**Closed by sheremet-va** 2024-01-12 09:55 UTC
Labels: pending triage
