### ISSUE TITLE
String exports aren't resolved on wildcard imports

### ISSUE THREAD

**Issue by LorisSigrist** [vitest-dev/vitest#5851] opened 2024-06-06 11:40 UTC
### Describe the bug

JS allows you to export/import as arbitrary strings. However, in vitest, wildcard imports do not import these string-exports.

```js
// file-1.js
const something = "Something"
export { something as "arbitrary string" };

// file-2.js
import * as T from "./file-1.js"
console.log(T["arbitrary string"]) // expected: log "Something"
```
If this is executed via node it works as expected. If that same code is executed via vitest `undefined` is logged instead. 

> `vite` bundles this code correctly

### Reproduction

https://github.com/LorisSigrist/vitest-string-exports-wildcard-reproduction (basically the code example above)

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 2.54 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
    pnpm: 9.1.4 - /opt/homebrew/bin/pnpm
    bun: 1.1.8 - /opt/homebrew/bin/bun
  Browsers:
    Safari: 17.4.1
  npmPackages:
    vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment] 2024-06-09 04:02
Thanks for the reproduction! This looks like an issue in Vite SSR, so I reported to there by adjusting your code
- https://github.com/vitejs/vite/issues/17426

**Comment by sheremet-va** [comment] 2024-06-23 16:00
The fix was merged in https://github.com/vitejs/vite/pull/17446 as part of 5.3.0, so if you update your Vite version manually or revalidate the lockfile, it should work.

**Closed by sheremet-va** 2024-06-23 16:00 UTC
Labels: upstream, p3-minor-bug
