### ISSUE TITLE
Using a function for test name formatting

### ISSUE THREAD

**Issue by thekevinscott** [vitest-dev/vitest#6780] opened 2024-10-23 14:53 UTC
### Clear and concise description of the problem

Hello,

I'd like to supply a function for a test name. Something like this:

```
test.for([
  [1,'a']
])(
  ([one, a]) => `${one * 2} ${a}`, // my custom function that produces a test name
  ([one, a]) => {
    // some test
  }
})

```

A specific use case might be test suites that accept strings with multiple new lines. Relying on `%s` results in hard-to-read test output. Providing a function that automatically escapes new lines would clean up said test output, and I don't believe the current formatting tools provide such a mechanism.

### Suggested solution

I'd like the ability to pass a function in as test name, that accepts the same arguments as the test function and is expected to return a string.

Alternatively, if there was a way to extend the behavior of `%s` (or other templating replacements) that could achieve the same thing.

### Alternative

It appears this same topic was brough up here, though with minimal discussion: https://github.com/vitest-dev/vitest/issues/2403

That issue references this PR: https://github.com/vitest-dev/vitest/pull/2405 which includes this comment:

> I see it still expects a function in this PR. The test name should always be a string, lets not change that.

(This PR is also linked): https://github.com/vitest-dev/vitest/pull/2405

[It appears that `formatName` is set up to accept a function](https://github.com/vitest-dev/vitest/blob/main/packages/runner/src/suite.ts#L756), but the function is never called; just the function's name is returned if a function is provided:

```
function formatName(name: string | Function) {
  return typeof name === 'string'
    ? name
    : name instanceof Function
      ? name.name || '<anonymous>'
      : String(name)
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment] 2024-10-24 00:02
I think I had a similar need before. Not sure about a proper solution, but workaround I think of is:

```ts
// manually write title as first element
test.for([
  ['1 and a', 1, 'a']
  ['2 and b', 2, 'b']
])('%s', ([_, x, y]) => {
  // ...
})

// or generate first element (probably type not inferred)
test.for(
  [
    [1, 'a']
    [2, 'b']
  ].map(([x, y]) => [`${x} and ${y}`, x, y])
)('%s', ([_, x, y]) => {
  // ...
})
```

**Comment by thekevinscott** [comment] 2024-10-24 00:08
Thanks for the suggestions @hi-ogawa. I'm doing something similar to your second example, mapping over the test cases to replace `\n` to `\\n` so that it prints nicely in the test output, and then again in the tests replacing _back_ from `\\n` to `\n`. But it adds a lot of cruft and I'm reusing this pattern all through my tests (my particular use case deals with a lot of new line inputs).

**Comment by sheremet-va** [comment] 2024-12-04 15:12
Duplicate of https://github.com/vitest-dev/vitest/issues/2093

I still think the current syntax is enough and introducing different behaviour for `test(Function)` and `test.for(Function)` is not justifiable.

If you need a different value for the title, you can add it to the `for` array like @hi-ogawa explained.

**Comment by hi-ogawa** [comment] 2024-12-05 00:16
I agree on closing this for now.

**Closed by hi-ogawa** 2024-12-05 00:16 UTC
Labels: enhancement: pending triage
