### ISSUE TITLE
Invisible text in terminal

### ISSUE THREAD

**Issue by xsrvmy** [vitest-dev/vitest#383] opened 2021-12-31 06:22 UTC
### Describe the bug

When a test fails, part of the text produced by the terminal uses ANSI black. On many terminal themes this produces invisible text.

![image](https://user-images.githubusercontent.com/7594338/147806955-32708678-835c-445b-9176-3d28dc482fa8.png)

Note that the invisible text is the darkest test in the selection, NOT the part that is barely visible.

### Reproduction

Run vitest on any test that will fail

### System Info

```shell
System:
    OS: Linux 5.15 Arch Linux
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 19.27 GB / 31.08 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.3.0 - ~/.volta/tools/image/npm/8.3.0/bin/npm
  Browsers:
    Firefox: 95.0.2
  npmPackages:
    @vitejs/plugin-react: ^1.0.7 => 1.1.3
    vite: ^2.7.2 => 2.7.10
    vitest: ^0.0.124 => 0.0.124
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Aslemammad** [comment] 2021-12-31 06:52
What terminal do you use?

**Comment by antfu** [comment] 2021-12-31 06:56
I don't think we use any black ANSI in our codebase and I didn't see it myself. Might be caused by something else?

**Comment by Aslemammad** [comment] 2021-12-31 06:57
Yea, I guess the same, that's why I'd like to see in which terminal this happens!

**Comment by xsrvmy** [comment] 2021-12-31 09:13
This was on alacritty. I'll test in KDE Konsole and report back.

**Comment by Aslemammad** [comment] 2021-12-31 09:42
@xsrvmy is right, i'm gonna send a PR for that.
![image](https://user-images.githubusercontent.com/37929992/147815937-58f1c9f0-ab5a-4e7c-b70d-c653aee1398c.png)

**Comment by sheremet-va** [comment] 2022-01-07 07:46
> This was on alacritty. I'll test in KDE Konsole and report back.

Do you have anything to report? Can we close the issue?

**Comment by xsrvmy** [comment] 2022-01-07 15:22
It looks like this is actually a issue depending on what terminal is used. In Alacritty and Konsole, setting dim gray will use the black color, which is often invisible. In kitty, dim uses transparency so this works.

**Comment by antfu** [comment] 2022-01-07 15:25
I believe this is more like a theme issue since we don't have control of the actual color rendered. Please raise the issue to your theme/terminal instead.

**Closed by antfu** 2022-01-07 15:25 UTC
