### ISSUE TITLE
Browser fail to work with pnpm

### ISSUE THREAD

**Issue by christophe-g** [vitest-dev/vitest#3380] opened 2023-05-16 14:52 UTC
### Describe the bug

running vitest in browser mode fail when dependencies are installed via pnpm

### Reproduction

cloning this [test repo](https://github.com/frank-weindel/vitest-3286-browser-typescript) and install with pnpm 
```bash
> git clone git@github.com:frank-weindel/vitest-3286-browser-typescript.git
> cd vitest-3286-browser-typescript
> pnpm i
> pnpm up -L
> pnpm test:browser
```

The browser console complains with : 
```
Uncaught (in promise) SyntaxError: The requested module '/node_modules/.pnpm/pretty-format@27.5.1/node_modules/pretty-format/build/index.js?v=968211a6' does not provide an export named '__vi_inject__' (at index.js?v=968211a6:3:10)
```
Doing the same unde nmp works (just need to remove the `optimizeDeps`  in vite.conf.js when running with latest vite and vitest) 

Potentiall linked issues: #3124

### System Info

```shell
System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 2.25 GB / 7.66 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 113.0
  npmPackages:
    @vitest/browser: ^0.31.0 => 0.31.0 
    vite: ^4.3.6 => 4.3.6 
    vitest: ^0.31.0 => 0.31.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-05-17 09:53
Duplicate of #3363

**Closed by sheremet-va** 2023-05-17 09:53 UTC
Labels: bug, pr welcome, browser
