### ISSUE TITLE
Cache implementation differs from Vite

### ISSUE THREAD

**Issue by seivan** [vitest-dev/vitest#1603] opened 2022-07-06 04:29 UTC
I see the implementation is fairly recent form  [https://github.com/vitest-dev/vitest/pull/1541](this), but could they have gotten the keys wrong? 

The cache config is `{dir: string}` while on Vite it's just a straight up `string`
Vite also calls the key `cacheDir` and not `cache`.

Because of that, this will always fail:
https://github.com/vitest-dev/vitest/blob/9c607572800a90e1b27d433239bfd05a7b4354c3/packages/vitest/src/node/config.ts#L185-L189

And the cache will default to `node_modules/.vitest` as opposed to what the user has defined. 

The workaround for this is of course, to repeat the key a second time for vitest, but that's a bit unnecessary. 

In fact, `cacheDir ` isn't even successfully omitted from the config type as the name is wrong. 
https://github.com/vitest-dev/vitest/blob/9c607572800a90e1b27d433239bfd05a7b4354c3/packages/vitest/src/types/config.ts#L418

I can do the PR if we're all on the same page. 

### Reproduction

Set `cacheDir` config on `vite.config.ts` to be `somethingElse`.
Run tests with said config. 
Notice `somethingElse` doesn't exist but `node_modules/.vitest` does. 

### System Info

```shell
-
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-07-06 05:03
Caches should be in different folders to not cause any collision. They serve different purposes.

**Comment by sheremet-va** [comment] 2022-07-06 05:21
Well, `cacheDir` is a final destination for Vite cache right now. We can't put our cache inside, because it might collide, or you might delete it with `--force` when running application.

**Comment by seivan** [comment] 2022-07-06 05:28
> Well, `cacheDir` is a final destination for Vite cache right now. 

I see, this would require both packages to alter, which is quite alright, but a slow process I am guessing. 

How would you feel about defaulting to Vites parent directory then? 


```ts
const cache =  "`${(config.cache?.dir ? 
                                  config.cache?.dir : config.cacheDir ? 
                                  path.dirName(config.cacheDir) : "node_modules")}/.vitest`"
```

**Comment by sheremet-va** [comment] 2022-07-06 05:32
It only works if parent directory is `node_modules`, because we don't really care what's inside, but if you put it somewhere else you don't expect this behaviour (for example, you might create a `cache` folder in root. with your approach we will create `.vitest` directory in root)

**Comment by seivan** [comment] 2022-07-06 05:37
Yes, that's correct, but that's an explicit choice from the user, they can already do that today.

(Pseudocode) 
So you would have `./root/.vite` and `path.dirName("root/.vite")/.vitest`.

But I am guessing you're meaning to say that they explicitly call `root` as the cacheFolder. 
In which case, wouldn't `--force ` as you mentioned earlier delete their root?

**Comment by sheremet-va** [comment] 2022-07-06 05:39
No, I am saying they put root/.cache as their cacheDir. In that case with your suggestion we will create .vitest folder in root, wich is unexpected behaviour.

**Comment by seivan** [comment] 2022-07-06 05:44
> No, I am saying they put root/.cache as their cacheDir. In that case with your suggestion we will create .vitest folder in root, wich is unexpected behaviour.


How is it unexpected? That's where their cache directory is defined to be. 

Either way you turn it, it's the same thing with an explicit choice. 
Scenario 1
```ts
cacheDir = "root/cache"
assert(vite.cache, "root/cache")
assert(vitetest.cache, "root/whatever-vitest-cache-name-is")
```

Scenario 2
```ts
cacheDir = "root/cache/vite"
assert(vite.cache, "root/cache/vite")
assert(vitetest.cache, "root/cache/whatever-vitest-cache-name-is")
```

**Comment by sheremet-va** [comment] 2022-07-06 05:47
But even in your example it's not explicit. I chose my cache folder to be `root/cache` for Vite, then why Vitest stores cache in `root`?

**Comment by sheremet-va** [comment] 2022-07-06 05:56
>  You're already storing it under node_modules

We are storing under `node_modules` because _we_ decided to, not because Vite is doing the same, there is no connection.

> So if we're going with the assumption (A) that root/cache works for vite.
> Then we can make the safe assumption that root/.vitest works for vitest.

This is just not true, we can't make that assumption.

I am closing this issue, because storing cache in other folder than Vite is desirable behaviour.

- `cacheDir` is for Vite cache
- `test.cache.dir` is for Vitest cache

It is advised to not store both caches in the same directory, because they might override each other or delete each others cache unexpectedly. For example, you might defined config such as this, if you want to store all caches inside `<root>/cache`:

```ts
{
  cacheDir: 'cache/.vite',
  test: {
    cache: {
       dir: 'cache/.vitest'
    }
  }
}
```

**Closed by sheremet-va** 2022-07-06 05:56 UTC
