### ISSUE TITLE
Coverage report is incorrect since 0.34.0

### ISSUE THREAD

**Issue by nstepien** [vitest-dev/vitest#3888] opened 2023-08-04 12:10 UTC
### Describe the bug

When multiple environments are used, it seems like this affects how coverage is computed.
I've also noticed that the coverage report is different on my machine vs CI.

Please check this branch: https://github.com/adazzle/react-data-grid/pull/3298
The coverage dropped significantly
- [CI](https://github.com/adazzle/react-data-grid/actions/runs/5755182074/job/15602627691?pr=3298):
  - ![image](https://github.com/vitest-dev/vitest/assets/567105/32924d89-69d5-4e14-a28e-a619c54b39a2)
- On my machine:
  - ![image](https://github.com/vitest-dev/vitest/assets/567105/ddedc74f-8414-4fe8-a4fb-2655d9fd8c43)
- Codecov:
  - ![image](https://github.com/vitest-dev/vitest/assets/567105/c4b95094-b11c-4507-b3d0-66a2f3da8415)

In `test/ssr.test.tsx`, if I skip the test, the coverage INCREASES:
![image](https://github.com/vitest-dev/vitest/assets/567105/bdec9eb3-1af9-4cf1-a2f1-e2cf471b0577)

Again in `test/ssr.test.tsx`, if I skip the test AND remove `// @vitest-environment node`, the coverage INCREASES further, back to normal levels:
![image](https://github.com/vitest-dev/vitest/assets/567105/315e3ec7-4feb-4888-b09a-767e6142b660)

It seems like Vitest 0.34 does not like multiple environments. 🤔 

### Reproduction

- Clone and checkout this branch https://github.com/adazzle/react-data-grid/pull/3298
- `npm i`
- `npm t -- --coverage`

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (64) x64 AMD Ryzen Threadripper 3970X 32-Core Processor
    Memory: 19.10 GB / 31.88 GB
  Binaries:
    Node: 20.5.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2070.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4
    @vitest/coverage-v8: ^0.34.1 => 0.34.1
    vite: ^4.4.8 => 4.4.8
    vitest: ^0.34.1 => 0.34.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2023-08-04 13:50
This sounds like https://github.com/vitest-dev/vitest/issues/3251.

A single file is tested in multiple environments. Vitest will pick source maps from the first result it finds.

**Comment by AriPerkkio** [comment] 2023-08-05 08:29
Any ideas how to setup a minimal reproduction for this case? Using whole `react-data-grid` for debugging is too much.

**Comment by nstepien** [comment] 2023-08-05 11:06
You can reduce `vite.config.ts` down to
```
import { defineConfig } from 'vite';

export default defineConfig({
  test: {
    environment: 'jsdom',
    globals: true,
    coverage: {
      provider: 'v8',
      enabled: true,
      include: ['src/**/*.{ts,tsx}', '!src/types.ts'],
      all: true
    },
    setupFiles: ['test/setup.ts']
  }
});
```

`ssr.test.tsx` is the only test file with the `node` environment, so you can delete most other test files, should be enough to generate different code coverage, for example:
![image](https://github.com/vitest-dev/vitest/assets/567105/434ea7f9-fa57-4e0f-a225-5f6848a85091)
Not sure what else to remove, we do need some code to cover after all 🙂

**Comment by AriPerkkio** [comment] 2023-08-05 13:09
Minimal reproduction case now at https://github.com/AriPerkkio/vitest/commit/b1301eb0179ee8b91c3bcafda5d673fb00d8d046. The custom Vite plugin transforms the source file differently depending on SSR/CSR. This intentionally causes different padding to source maps and messes the V8 results. Same should happen with Istanbul as well. 

On the left side is shown what coverage report looks like when same file is tested in Node and JSDOM. On the right side is what it looks like when it's tested only on one environment. The left one is clearly off.

<img width="480px" src="https://github.com/vitest-dev/vitest/assets/14806298/34304ef8-c75b-41bd-8633-61bd898e4b15" />

We'll need to tell coverage providers the `transformMode` here:

https://github.com/vitest-dev/vitest/blob/f4e6e99fa3a81fd7a97fb9b435da367dddba7fa4/packages/vitest/src/runtime/runners/index.ts#L63-L65

Then they can use it in provider when picking the correct source map:

https://github.com/vitest-dev/vitest/blob/f4e6e99fa3a81fd7a97fb9b435da367dddba7fa4/packages/coverage-v8/src/provider.ts#L217

This requires `vite-node` to store the `transformMode` here:

https://github.com/vitest-dev/vitest/blob/f4e6e99fa3a81fd7a97fb9b435da367dddba7fa4/packages/vite-node/src/server.ts#L23-L27

Currently `vite-node`'s `fetchCache` is using filename as key. This won't work when same filename can have different transform result. Key should contain filename and `transformMode`.

**Comment by sheremet-va** [comment] 2023-08-15 15:41
> Then they can use it in provider when picking the correct source map:

I also want to point out that it might not have it if tests were running using browser. I remember that it would throw an error before, but currently, it just runs it with empty coverage.

**Comment by AriPerkkio** [comment] 2023-10-08 13:34
I have now tested the idea described above and it works. However I'll need more time to finalize the implementation.

Here a file is transformed differently based on transform mode. On `web` it adds plenty of padding so that covered lines do not match with the SSR version. The coverage reports below are for individual test runs for each transform mode.

<img width="420px" src="https://github.com/vitest-dev/vitest/assets/14806298/33ac30ef-86eb-4278-bec3-ad207de60652" />

Here on left it's shown how the coverage is currently merged incorrectly, using the first source map Vitest finds. On right side is shown how the coverage report looks like when both coverage results are traced back using their own source maps, and then merged with Istanbul:

<img width="420px" src="https://github.com/vitest-dev/vitest/assets/14806298/95085592-b341-4f4c-9d66-15394fdf7499" />

Happy to see that this actually works in practice. 😅

**Closed** 2023-10-23 09:54 UTC
Labels: bug, coverage
