### ISSUE TITLE
The `typecheck` option not working as expected

### ISSUE THREAD

**Issue by NWYLZW** [vitest-dev/vitest#4767] opened 2023-12-17 17:43 UTC
### Describe the bug

The typecheck function does not work very well and has many problems.
* This configuration didn't work at all when I used `typecheck.include`.
* When I don't use it, it fails to detect and classify type errors in files ending with `.spec`.
* At the same time, it can only detect and classify type errors in files ending with `.spec-d`.

These phenomena describe what makes the answer to this [issue](https://github.com/vitest-dev/vitest/issues/4432#issuecomment-1791931822) seem inaccurate.

### Reproduction

https://github.com/NWYLZW/recurrent-vitest-typecheck-include

There are two script here, namely `test:a`, `test:b` and `test:c`.

* `test:a` no `typecheck.include`
* `test:b` set the `typecheck.include`
* `test:c` set the `include` and `typecheck.include`

### System Info

```shell
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 90.98 MB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.19.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 10.2.3 - /usr/local/bin/npm
  pnpm: 8.12.1 - ~/Library/pnpm/pnpm
Browsers:
  Safari: 17.1
npmPackages:
  vitest: ^1.0.4 => 1.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment] 2023-12-18 05:51
I think a part of the confusing behavior might be coming from the fact that `include` option requires `**/` prefix.
Your example uses `src/**/*.spec.ts` but I think that needs to be `**/src/**/*.spec.ts` to match something. This is confusing but  glob pattern usually works in that way in Vite ecosystem.
Here is what I changed https://stackblitz.com/edit/github-31y6zp?file=vitest.config.b.js

After changing that, I see unhandled errors which seems to be coming from typescript errors of non type test files.
That's probably not an intended behavior so it could be Vitest's bug.

**Comment by NWYLZW** [comment] 2023-12-18 07:08
When I replace `typecheck.include: src/**/*.spec.ts` to `**/src/**/*.spec.ts`, it works.\
Indeed, I also saw type errors for files that were not marked in the `include` field. This is probably another problem, but the solution you provided can solve my problem.

Thank you.

**Comment by hi-ogawa** [comment] 2023-12-18 23:15
Hey, glad you figured it out.

I suppose this issue was mainly about `typecheck.include` flag, so can you close this issue?
If other issues come up, then please feel free to create a new issue. Thanks!

**Closed** 2023-12-19 02:30 UTC
Labels: pending triage
