### ISSUE TITLE
New version of vitest (0.33.0) never completes

### ISSUE THREAD

**Issue by kaiyoma** [vitest-dev/vitest#3785] opened 2023-07-19 20:52 UTC
### Describe the bug

I work on a very large enterprise project that uses Vitest 0.31.2. We have 10,000+ unit tests and they take about 12 minutes to run. I'm trying to upgrade to the latest version of Vitest, but running into a problem - the command never completes. All the test files seem to run correctly, but the command never finishes and I'm never returned to the shell. This is happening locally as well as in our Linux-based CI environment. There are no errors; the command just hangs at the end.

When I monitor the CPU and memory usage during the test run, everything looks normal. The test run also takes about the same amount of time it did before, but it never finishes.

### Reproduction

N/A

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 4.98 GB / 15.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\Node.js\node.EXE
    npm: 9.8.0 - C:\Program Files\Node.js\npm.CMD
    pnpm: 8.6.6 - C:\Program Files\Node.js\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: 4.0.0 => 4.0.0
    vite: 4.3.8 => 4.3.8
    vitest: 0.33.0 => 0.33.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kaiyoma** [comment] 2023-07-20 01:39
We were able to narrow down to a single test file that's causing the problem, but it's unclear what the problem is or why the behavior is different across vitest versions. If we comment out a single call to `vi.mock` then the tests complete. However, vitest isn't really helping here, as it doesn't print out what file has the problem or any kind of debugging or error information.

**Comment by sheremet-va** [comment] 2023-07-20 08:17
Use vite-node DEBUG variables: https://github.com/vitest-dev/vitest/blob/main/packages/vite-node/README.md

**Comment by kaiyoma** [comment] 2023-07-20 16:16
@sheremet-va Oh nice! I'll try this out and report back.

**Comment by kaiyoma** [comment] 2023-07-21 00:47
After some digging into our code and browsing other Vitest issues, we discovered an import cycle (several, actually) inside the directory that's being mocked, which is the same issue that other Vitest users have reported. Once I started fixing the import cycles, the hanging unit test file started to pass again. 🎉 

Shout out to the [skott](https://github.com/antoine-coulon/skott) tool for helping us find the circular imports.

For sure, there are issues in our code we need to fix, but it would also be great if Vitest didn't silently hang. Up to you guys if you want to leave this issue open or close it.

**Comment by madeleineostoja** [comment] 2023-10-25 01:30
I had a completely unrelated issue (missing istanbul coverage reporter dependency in my monorepo) and vitest hung silently with the latest version. Running vite-node debug didn't help either. I only discovered the issue by reverting to vitest `0.32`, which correctly threw the error for an unresolved module. 

Definitely seems like something is up with the latest versions of vitest and error logging vs silently hanging.

**Comment by shellscape** [comment] 2023-11-29 03:26
Just ran into the same problem with 0.34.6 which also affects 1.0.0-beta.6. A lack of circular import support is a real deal breaker for an otherwise awesome testing lib.

**Comment by sheremet-va** [comment] 2023-12-05 11:18
> Just ran into the same problem with 0.34.6 which also affects 1.0.0-beta.6. A lack of circular import support is a real deal breaker for an otherwise awesome testing lib.

Circular imports are supported with the exception of one edge case that we are not able to reproduce. If you have a project you can share, please do.

**Comment by sheremet-va** [comment] 2023-12-05 11:18
I am closing this issue since the original author found a solution.

**Closed by sheremet-va** 2023-12-05 11:18 UTC
Labels: pending triage

**Comment by madeleineostoja** [comment] 2023-12-09 11:18
@sheremet-va in that case can we add another one for silent failures, which is the actual issue this issue uncovered?

**Comment by sheremet-va** [comment] 2023-12-09 11:23
> @sheremet-va in that case can we add another one for silent failures, which is the actual issue this issue uncovered?

Feel free to open a new issue with a reproduction 👍🏻
