### ISSUE TITLE
Implicit branches are not considered in coverage

### ISSUE THREAD

**Issue by bencelang** [vitest-dev/vitest#2239] opened 2022-10-30 20:53 UTC
### Describe the bug

Code with implicit branches is not detected in coverage. Consider the following code:

```javascript
function fn(param) {
  if (param) {
	// If param is falsy, this if never runs
  }
}
```

If test code is only executing `fn` with a truthy parameter the implicit else branch is never tested, thus should not count towards covered branches. Interestingly enough, coverage still reports 100% for branch coverage.

This impacts both coverage providers but in case of c8 it is a known issue. With istanbul it is expected to report the correct 50% branch coverage metric, yet running under vitest the problem persists. Read reproduction for details.

### Reproduction

Consider the following code ([origin](https://gist.github.com/mikeal/60aea513165c35ac438f6a35f0727a75)):
```javascript
// cov.js
export const fn = y => {
  if (typeof y !== 'object') {
    y = 'yup'
  }
  console.log(y)
}
```
```javascript
// cov.spec.js
import { fn } from "cov"

test("implicit branch coverage bug", () => {
  const x = 'asdf'
  fn(x)
});
```

The coverage report using `@vitest/coverage-c8` reports this as 100% branch coverage, due to a known issue with v8 (bcoe/c8#227 and [this](https://bugs.chromium.org/p/v8/issues/detail?id=10627) v8 ticket). However, running a sligthly different version of this code [from the gist I linked above](https://gist.github.com/mikeal/60aea513165c35ac438f6a35f0727a75) in commonjs syntax through `nyc node cov.cjs` prints 50%, correctly. (ESM code causes `nyc` to have a blank output but that is also already a known issue).

Interestingly, switching the coverage provider to `@vitest/coverage-istanbul` is still impacted, showing full coverage mistakenly.

```
% Coverage report from istanbul
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                  
 cov.js   |     100 |      100 |     100 |     100 |                  
----------|---------|----------|---------|---------|-------------------
```

### System Info

```shell
system: Windows 11 Build 10.0.22621
node: v19.0.0
pnpm: v6.32.9
nyc: v15.1.0
vitest: v0.24.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2022-11-02 15:13
This is duplicate of https://github.com/vitest-dev/vitest/issues/1887.

@bencelang so even though there is no `else` branch, it is expected that the branch count includes it? It should not match with the source code's branch count?

```js
// Source code
export const fn = y => {
    if (true) {
        console.log('#1')
    }
    console.log('#2')
}

// Instrumented
coverageMap.s[0]++;
export const fn = y => {
  coverageMap.f[0]++;
  coverageMap.s[1]++;

  if (true) {
    coverageMap.b[0][0]++;
    coverageMap.s[2]++;
    console.log('#1');
  } else {
    coverageMap.b[0][1]++;
  }

  coverageMap.s[3]++;
  console.log('#2');
}

// Coverage map
"s": {
  "0": 1,
  "1": 1,
  "2": 1,
  "3": 1
},
"f": {
  "0": 1
},
"b": {
  "0": [
    1,
    0 // <-- else-branch
  ]
}
```

Now that we map the coverage back to sources, the `else` branch is dropped since it is not found in sourcemaps - it does not exist in sources:

```js
"s": {
  "0": 1,
  "1": 1,
  "2": 1,
  "3": 1
},
"f": {
  "0": 1
},
"b": { // Notice how branch count drops
  "0": [
    1
  ]
}
```

Two more test cases to demonstrate this.

#### 100% branch coverage since all lines are covered

```js
1 | export const fn = () => {
2 |     if (true) {
3 |         console.log('#1')
4 |     }
5 |     console.log('#2')
6 | }

/*
  % Coverage report from istanbul
 ----------|---------|----------|---------|---------|-------------------
 File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
 ----------|---------|----------|---------|---------|-------------------
 All files |     100 |      100 |     100 |     100 |                   
  cov.js   |     100 |      100 |     100 |     100 |                   
 ----------|---------|----------|---------|---------|-------------------
*/
```

#### 75% coverage, unreached lines are not covered:

```js
1 | export const fn = () => {
2 |     if (false) {
3 |         console.log('#1')
4 |     }
5 |     console.log('#2')
6 | }

/*
 % Coverage report from istanbul
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |      75 |        0 |     100 |      75 |                   
 cov.js   |      75 |        0 |     100 |      75 | 3                 
----------|---------|----------|---------|---------|-------------------
*/
```

**Comment by AriPerkkio** [comment] 2022-11-02 20:13
I debugged this a bit further and found out why `nyc` is able to show these implicit `else` branches. Looks like a bug/missing feature in `istanbul-lib-source-maps`.

In vitest codebase we can apply a work-around this. I'll set up PR later and write a bit more about the root case.

```
 % Coverage report from istanbul
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |       50 |     100 |     100 |                   
 cov.js   |     100 |       50 |     100 |     100 | 2                 
----------|---------|----------|---------|---------|-------------------
```

**Comment by bencelang** [comment] 2022-11-05 00:20
@AriPerkkio I see why you indicated this as a duplicate and I'm sorry for not catching it earlier. This example is the other way around though - always reaching the branch body - and I think better represents why this is misleading.

> It should not match with the source code's branch count?

Depends on what you say branch count is. My point of view (as seem to align with the `nyc` command line's reasoning) is that a simple if statement convolves two possible ways of execution, whether you count the `if` statements or the real number of execution paths possible. In other words, every presence of a branch convolves at least two paths of execution. I would expect the branch coverage metric to help identify uncovered code paths due to branching, and not having covered a case where the above example condition is not met is definitely one of these areas.  For full theoretical coverage, every branch should be tested for both possibilities: taking the branch or not. In some cases, this involves an explicit `else` statement but the mentioned code example _has_ two paths of execution without it.

I think it makes more sense to count the actual paths of execution (a standalone if statement as 2) instead of the blocks present.

**Comment by AriPerkkio** [comment] 2022-11-05 07:58
@bencelang you are completely right. I read this thread to understand the implicit `else` case better: https://github.com/gotwarlost/istanbul/issues/35.

I think example below highlights the importance of branch coverage. It has 100% **line coverage** but only 50% **branch coverage**.

```js
function get(condition) {
  let output;
  
  if(condition) {
    output = 'text';
  }
  
  return condition;
}

// Test
expect(get(true)).toBe('text');

// Production code
get(usuallyTruthyCondition).toString()
```

Now the untested branch may actually cause NPE in production code. It's not covered by tests due to partial branch coverage.

```js
const usuallyTruthyCondition = false;

get(usuallyTruthyCondition).toString()
                        // ^^^^^^^^^^^ NPE
```

**Closed** 2022-11-05 13:17 UTC
Labels: duplicate, coverage

**Comment by AriPerkkio** [comment] 2025-04-02 06:02
Linking here discussion about V8 coverage and implicit-else detection at https://github.com/vitest-dev/vitest/discussions/7587.
