### ISSUE TITLE
vitest 0.34.3 is twice as slow as 0.33.0

### ISSUE THREAD

**Issue by kaiyoma** [vitest-dev/vitest#4059] opened 2023-08-31 20:19 UTC
### Describe the bug

I tried upgrading from 0.33.0 to 0.34.3 and now my tests are taking twice as long. No other changes were made.

Before the upgrade (from our CI):

```
12:37:58  test... PASS (600s)
```

After the upgrade:

```
13:16:55  test... FAIL (1265s)
```

These results are very repeatable.

### Reproduction

Upgrade from 0.33.0 to 0.34.3 and run tests.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 2.76 GB / 15.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\Node.js\node.EXE
    npm: 9.8.0 - C:\Program Files\Node.js\npm.CMD
    pnpm: 8.6.10 - C:\Program Files\Node.js\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2215.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: 4.0.4 => 4.0.4
    vite: 4.4.9 => 4.4.9
    vitest: 0.34.3 => 0.34.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-08-31 21:05
Duplicate of https://github.com/vitest-dev/vitest/issues/3967

**Closed by sheremet-va** 2023-08-31 21:05 UTC
Labels: pending triage
