### ISSUE TITLE
vite-node uses a stale update in watch mode

### ISSUE THREAD

**Issue by andrew-w-ross** [vitest-dev/vitest#1622] opened 2022-07-09 16:39 UTC
### Describe the bug

When using `vite-node` in watch mode only the first change is used. Subsequent changes will still cause it to update but only the first update will actually be used.

I've created a reproduction that more clearly demonstrates the issue.

### Reproduction

I've created a reproduction [here](https://github.com/andrew-w-ross/vite-node-watch-bug). I've included a dev container to make it easier to replicate the environment I ran it on.

### System Info

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) arm64 unknown
    Memory: 10.23 GB / 11.67 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm

I've also encountered this issue on my host machine.

System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 485.77 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.5.0 - ~/.nvm/versions/node/v18.5.0/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v18.5.0/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.5.0/bin/npm
    Watchman: 2022.06.13.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-react: ^1.3.2 => 1.3.2 
    vite: ^2.9.14 => 2.9.14
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by togami2864** [comment] 2022-07-10 13:37
I got a familiar situation and I found that upgrading `vite` to `v3` solves this bug.
Please check the version of the `vite`. It can be v2 because Dependencies specify ["^2.9.12 || ^3.0.0-0"](https://github.com/togami2864/vitest/blob/e910f81097f9a8fbeb27db4c6015fb171faaacf4/packages/vite-node/package.json#L68).
In my local machine, `vite@3.0.0-beta.4` works well, however, `vite@2.9.4` makes the same bug.

**Comment by andrew-w-ross** [comment] 2022-07-10 17:57
@togami2864 Yeah my reproduction was on `vite@2.9.14` when I changed the version to the beta it works just fine. Considering there are only [two tickets left on the 3.0 milestone](https://github.com/vitejs/vite/milestone/5) it might be a wasted effort to fix it. I'll leave it up to you all if you want to close the ticket or not seeing I don't know if support for vite 2.0 is a long term goal for the project.

**Comment by sheremet-va** [comment] 2022-10-28 16:26
Yeah, Vitest doesn't support Vite 2 anymore, so I guess we can close this issue. If it's still reproducible, feel free to ping me

**Closed by sheremet-va** 2022-10-28 16:26 UTC
Labels: bug
