### ISSUE TITLE
vite-node --watch doesn't close process before restarting

### ISSUE THREAD

**Issue by KyleAMathews** [vitest-dev/vitest#2334] opened 2022-11-15 15:46 UTC
### Describe the bug

I created a simple Typescript Express app that I wanted to try vite-node with. It runs fine but when I edit the src code, I get this error:

```
[vite-node] Failed to execute file:                       
Error: listen EADDRINUSE: address already in use :::4000
```

Which shows that vite-node isn't closing the previous process when in watch mode.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-7yrhdv?file=package.json,server.ts&initialPath=__vitest__

changing what is logged out starts to accumulate multiple log entries.

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-11-15 16:40
Not sure if it's `vite-node` responsibility? You can use `import.meta.hot` for this:

```ts
if (import.meta.hot) {
  import.meta.hot.accept(() => {
    server.close()
  })
}
```

**Comment by KyleAMathews** [comment] 2022-11-15 18:02
HMR doesn't work for node processes — vite-node is creating new node process on changes and leaving the old ones running. I just expect the old one to be killed before the new one starts.

**Comment by KyleAMathews** [comment] 2022-11-15 18:43
I'm using vite-node in a cli. Killing the old node process there is standard behavior for `--watch` e.g. node's new --watch or nodemon.

**Comment by sheremet-va** [comment] 2022-11-15 19:04
> I'm using vite-node directly in an npm script. Killing the old node process there is standard behavior for `--watch` e.g. node's new --watch or nodemon.

`vite-node` doesn't start new process on file change, so there is no such thing as "old node process", it reevaluates module graph on file change. To react to changes in watch mode you need to hook up into its lifecycle.

**Comment by sheremet-va** [comment] 2022-11-15 19:07
I'm also not sure what do you expect to happen in a reproduction?

![image](https://user-images.githubusercontent.com/16173870/202004411-852e5ccd-ea1c-4aa7-935b-e0274cac0c89.png)

This looks expected to me

**Comment by david-plugge** [comment] 2022-11-19 19:54
I ran into the same issue with a fastify server.

By storing the server in globalThis and if present stop it before creating a new one i was able to make it work.
```ts
declare global {
	// eslint-disable-next-line no-var
	var __app: FastifyInstance;
}

if (globalThis.__app) {
	await globalThis.__app.close();
}

const app = (globalThis.__app = fastify({
	logger: true
}));
```

**Comment by KyleAMathews** [comment] 2022-11-19 22:02
Can someone tell me what I'm doing wrong here then?

```typescript
const http = require('http');

const requestListener = function (req, res) {
  res.writeHead(200);
  res.end('Hello, World!');
}

const server = http.createServer(requestListener);
server.listen(8080, () => {
  console.log(`listening2`)
});

if (import.meta.hot) {
  import.meta.hot.accept(() => {
    server.close()
  })
}
```

I started the server with `npx vite-node --watch index.ts` and it outputted `listening`. I then changed that to output `listening2` and there was the immediate "address already in use" error.

<img width="744" alt="Screen Shot 2022-11-19 at 2 00 40 PM" src="https://user-images.githubusercontent.com/71047/202873124-1738938c-0939-4697-8f7b-ba68872cbf9c.png">

**Comment by david-plugge** [comment] 2022-11-19 23:55
Alright, i have to revert what i´ve said. The error still appears, i just didn´t fully tested it.

Using vite-node for running servers in development doesnt seems to work at the moment.
What could eventually solve it would be an option to completely get rid of the current node process that runs the code and spawn a new process with the latest code (basically rebuild the whole app and run it like nodemon). I´ve tried disabling hmr but that just disables all reload capabilities.

I´d love to use vite for this due to the speed and plugin ecosystem but i wonder if this kind of usage is in the scope of vite-node or if we should rather use something else to run our server (something like nodemon/ts-node-dev).

**Comment by sheremet-va** [comment] 2022-11-21 14:50
So, Vite considers editing the main entry here as a full reload type of HMR, so it won't call `dispose`, and it calls `accept` too late. But I found a way to close server before ViteNode reevaluates file:

```ts
if (import.meta.hot) {
  import.meta.hot.on("vite:beforeFullReload", () => {
    server.close();
  });
}
```

Maybe it's a good idea to also add `dispose` just in case:

```ts
import.meta.hot.dispose(() => {
  server.close()
});
```

It will be called only if HMR is triggered not as a full reload. According to [Vite docs](https://vitejs.dev/guide/api-hmr.html) it's meant to clear all side effects.

We should probably add this information to docs.

**Comment by GuskiS** [comment] 2023-01-20 16:30
@sheremet-va Seems like it is working, however if I do something like this:
```ts
if (import.meta.hot) {
  import.meta.hot.on("vite:beforeFullReload", () => {
    console.log("Reload");
  });
}
```
it keeps adding listeners and it prints `Reload` multiple times on single file save. Any ideas?

**Comment by jgoux** [comment] 2023-02-02 08:46
@GuskiS I had the same issue! https://github.com/vitest-dev/vitest/pull/2792 should fix it. 😄

**Comment by GuskiS** [comment] 2023-02-03 12:45
@jgoux  That seems to have fixed the issue, but it seems there is another one - if you quickly double save file, I can still get port in use error which crashes server. It seems that if callback is async, vite-node doesn't wait for it to finish 😞

**Comment by ducan-ne** [comment] 2023-04-17 16:49
> @jgoux That seems to have fixed the issue, but it seems there is another one - if you quickly double save file, I can still get port in use error which crashes server. It seems that if callback is async, vite-node doesn't wait for it to finish 😞
I faced this issue today, don't think there is someone faced it already 😄

The temporary solution could be ... setTimeout

**Comment by scarf005** [comment] 2023-07-30 14:42
been having same issues, looks like #3834 resolved it.
however, each save accumulates callback, which may cause issues:
![image](https://github.com/vitest-dev/vitest/assets/54838975/15b921fb-6353-45dc-bcf3-174431155629)

<details><summary>Callback used</summary>

```ts
const httpTerminator = createHttpTerminator({ server, gracefulTerminationTimeout });

const releaseResources = async () => {
  if (dataSource.isInitialized) {
    try {
      await dataSource.destroy();
      logger.warn('successfuly closed typeorm connection to database');
    } catch (error) {
      logger.error('error when closing database connection', error);
    }
  }
  await httpTerminator.terminate();
  logger.warn('closed http server');
};

const attemptGracefulShutdown = async (signal: string) => {
  logger.warn(`Attempting to gracefully shutdown for ${signal}`);
  await releaseResources();
  process.exit(0);
};

const signals = ['SIGTERM', 'SIGINT', 'SIGUSR2'];
signals.forEach((signal) => process.on(signal, () => attemptGracefulShutdown(signal)));

if (import.meta.hot) {
  import.meta.hot.on('vite:beforeFullReload', releaseResources);
  import.meta.hot.dispose(releaseResources);
}
```

</details>

**Comment by sheremet-va** [comment] 2023-08-14 08:36
#3834 is released as part of 0.34.0. vite-node now waits until callback is resolved before reloading.

**Closed by sheremet-va** 2023-08-14 08:36 UTC
Labels: documentation

**Comment by GuskiS** [comment] 2023-08-14 08:40
@sheremet-va Is the issue that @scarf005 mentioned also fixed? Looking at his screenshot it seems that event callback is not being removed from events map. 🤔

**Comment by scarf005** [comment] 2023-08-14 08:43
@sheremet-va i've updated to v0.34.1, however the error seems to persist even without `process.on` hooks.

https://github.com/vitest-dev/vitest/assets/54838975/f17b212a-d345-4ce1-ac38-60e36b838fd2

**Comment by sheremet-va** [comment] 2023-08-14 09:00
Please, create a new issue with reproduction

**Comment by xuxucode** [comment] 2023-08-14 13:33
problem still exists
