### ISSUE TITLE
Dual package hazard in cjs monorepo

### ISSUE THREAD

**Issue by sukovanej** [vitest-dev/vitest#4365] opened 2023-10-24 12:29 UTC
### Describe the bug

Related issue: https://github.com/Effect-TS/effect/issues/1548

In the setup (check the repro), vitest loads both the esm and cjs versions of the `effect` package.

cc @Andarist

### Reproduction

https://github.com/sukovanej/effect-cjs-yarn-monorepo-repro

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 79.05 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.8.1 - /opt/homebrew/bin/node
    Yarn: 4.0.0 - /usr/local/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 17.0
  npmPackages:
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Andarist** [comment] 2023-10-24 12:49
> Once the module is externalized, it cannot be intercepted in any way by Vitest,

It makes sense *but* I strongly believe that a *dependency* loaded by a source file should *also* be externalized and loaded through node module resolution mechanism. Otherwise the same dependency is sometimes loaded through Vite and sometimes loaded through node and that leads to very obscure bugs.

**Comment by sheremet-va** [comment] 2023-10-24 12:52
> However, I strongly believe that a _dependency_ loaded by a source file should _also_ be externalized and loaded through node module resolution mechanism. Otherwise, the same dependency is sometimes loaded through Vite and sometimes loaded through node and that leads to very obscure bugs.

That is harder to achieve. All imports inside the source code are resolved with Vite resolution algorithm first, and then we decide if this particular file should be externalized.

There are already options to configure the behavior manually in the meantime: https://vitest.dev/config/#server-deps-external

**Comment by Andarist** [comment] 2023-10-24 13:00
Sure, I'm just saying that I think that the current default behavior is not exactly intuitive and that it can lead to obscure bugs. So, if only possible, I'm asking the Vite team to reconsider this default behavior. I'm quite familiar with a lot of existing JS tools and their resolution algorithms etc and what happens here deviates from what I'd call a "quasi-standard". I haven't found this behavior in any other tool. Since this diverges from a common path it makes it harder for me to reason about how my packages might be treated by tooling since it adds yet another column to the matrix of possibilities and knobs (and that matrix already ain't small 😢 )

**Comment by sheremet-va** [comment] 2023-10-24 20:12
> Sure, I'm just saying that I think that the current default behavior is not exactly intuitive and that it can lead to obscure bugs. So, if only possible, I'm asking the Vite team to reconsider this default behavior. I'm quite familiar with a lot of existing JS tools and their resolution algorithms etc and what happens here deviates from what I'd call a "quasi-standard". I haven't found this behavior in any other tool. Since this diverges from a common path it makes it harder for me to reason about how my packages might be treated by tooling since it adds yet another column to the matrix of possibilities and knobs (and that matrix already ain't small 😢 )

Fully agree that it should work like that 👍🏻

**Comment by sheremet-va** [comment] 2024-02-16 15:31
We cannot override Vite's behavior here because it will create more inconsistencies between dev and tests. If the file was processed by Vite, it will go through all plugins, so it can be transformed in a different way. If you find yourself importing different dependencies, try [aliasing](https://vitest.dev/config/#alias) the dependency to the externalized version.

**Closed by sheremet-va** 2024-02-16 15:31 UTC
Labels: pending triage

**Comment by sheremet-va** [comment] 2024-02-19 14:38
> I fully understand the concern but is there any test case that would showcase that actual risk here? I'd love to learn more about specifics related to this particular problem here.

This is more of a general concern. There are a lot of ways in Vite to change how the import is resolved (`alias`, `resolveId`/`transform`/`load` hooks), so overriding this behavior brings more harm than good in my opinion, - I don't think we can tell the intention to safely change the resolved path of an external module.

**Comment by hi-ogawa** [comment] 2024-02-21 06:42
> I fully understand the concern but is there any test case that would showcase that actual risk here? I'd love to learn more about specifics related to this particular problem here.

I'm not sure what you exactly mean by "test case" or "actual risk", but I've seen a similar issue happens on Vite SSR, for example with `preact` https://github.com/vitejs/vite/issues/15503#issuecomment-1897888202

While fiddling with reproduction (hopefully what your imagine as "test case"), I found that `import` vs `require` dual package issue can be simply demonstrated on plain NodeJS regardless of whether your main package is esm or commonjs:

https://stackblitz.com/edit/github-ukmpzp?file=repro.cjs
https://stackblitz.com/edit/github-ukmpzp?file=repro.mjs

What actually happens with Vitest (or Vite SSR) is that, your source code's import will all converted to dynamic import (such as `await import("effect")`), but your cjs dependency doing `require("effect")` is kept as is, so if your have `exports` entries, which redirect to a different module, then it will lead to dual package just like the simple reproduction above.

What I found interesting while investigating preact issue is that `react` doesn't have this issue because both `import("react")` and `require("react")` will reach the same cjs module for an obvious reason since react is cjs-only package.
