### ISSUE TITLE
Coverage report does not include .vue files

### ISSUE THREAD

**Issue by kouts** [vitest-dev/vitest#680] opened 2022-02-04 16:40 UTC
### Describe the bug

The coverage seems to only cover `.vue` files that are currently tested, giving wrong coverage reports since files without tests are not covered.
Possible related issues/PRs
https://github.com/vitest-dev/vitest/issues/559
https://github.com/vitest-dev/vitest/pull/518

### Reproduction

https://github.com/kouts/vitest-coverage

running `npm run coverage` gives us the following
![image](https://user-images.githubusercontent.com/2233663/152567368-ea8a724e-4194-49be-a1c7-e0666454c40f.png)
while it should include the **uncovered** `src/Hello.vue` component

### System Info

```shell
System:
    OS: macOS 11.6.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 192.20 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.2
    Firefox Developer Edition: 97.0
    Safari: 15.2
    Safari Technology Preview: 15.4
  npmPackages:
    @vitejs/plugin-vue: ^2.1.0 => 2.1.0 
    vitest: latest => 0.2.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment] 2022-02-05 13:07
https://github.com/bcoe/c8#checking-for-full-source-coverage-using---all

`c8` by default only collects coverage for files that have been tested. You can pass `all: true` option to Vitest `coverage` config to report coverage for all files. You will probably need to adjust `coverage.include` option too, to not receive coverage for files that you don't want.

```js
export default defineConfig({
  test: {
    coverage: {
      all: true
    }
  },
})

```

**Comment by kouts** [comment] 2022-02-05 13:28
Thank you @Demivan I think I've already done that
https://github.com/kouts/vitest-coverage/blob/main/vitest.config.ts
is the issue reproducible on your side too?
https://github.com/kouts/vitest-coverage

**Comment by Demivan** [comment] 2022-02-05 13:34
Your repository page returns 404. Is it private?

**Comment by kouts** [comment] 2022-02-05 13:36
Sorry, my bad, should be public now.

**Comment by Demivan** [comment] 2022-02-05 13:43
https://github.com/bcoe/c8/blob/ff01cd832a155494892b24c30c5a1c8f0169fd8e/lib/report.js#L197

Looks like `all` option in `c8` only works with '.js', '.ts' and '.mjs' files. This is the issue on their side. They should be using `include`/`exclude` options to determine whether to include a file.
You can create issue in their repo or I can.

**Comment by kouts** [comment] 2022-02-05 14:01
Thanks @Demivan, opened an issue here:
https://github.com/bcoe/c8/issues/355

**Comment by brzezinskimarcin** [comment] 2022-02-14 22:57
I experience the same issue. Does anyone have a workaround until it gets fixed?

**Comment by victorlmneves** [comment] 2022-02-22 18:59
@kouts @brzezinskimarcin @Demivan for me it's working
![image](https://user-images.githubusercontent.com/17341789/155200369-13ac927d-838d-4c07-81d8-ec75e21a571e.png)

**Comment by victorlmneves** [comment] 2022-02-22 19:18
@kouts @brzezinskimarcin @Demivan
Sorry, but I didn't pay real attention to the results.
The **.vue files aren't included on the list 😞

**Comment by victorlmneves** [comment] 2022-02-22 19:40
Looking to Peeky code it's using `coverageOptions` key instead of coverage
```
export default defineConfig({
  coverageOptions: {
    reportsDirectory: './coverage',
    excludeNodeModules: true,
    exclude: [
      'coverage/**',
      'packages/*/test{,s}/**',
      '**/*.d.ts',
      'cypress/**',
      'test{,s}/**',
      'test{,-*}.{js,cjs,mjs,ts,tsx,jsx}',
      '**/*{.,-}test.{js,cjs,mjs,ts,tsx,jsx}',
      '**/__tests__/**',
      '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc}.config.{js,cjs,mjs,ts}',
      '**/.{eslint,mocha}rc.{js,cjs}',
    ],
    reporter: ['text', 'html'],
    extension: ['.js', '.cjs', '.mjs', '.ts', '.tsx', '.jsx', '.vue', 'svelte'],
  },
})
```
I tried it but it also doesn't work as expected and he also uses C8

Unfortunately for me, Peeky it's not generating the HTML report
But on the console, I see a reference to `App.vue`
![image](https://user-images.githubusercontent.com/17341789/155205948-ba001498-448c-469f-8550-d30f4a738315.png)

**Comment by Akryum** [comment] 2022-02-22 22:47
Peeky had custom code before but it was too much work to implement istanbul and I just switched to c8 for the coverage report.

**Comment by jagoncalves14** [comment] 2022-05-12 16:13
I created a Stackblitz demo that reproduces this.

https://stackblitz.com/edit/vue-vitest-demo

**Comment by DannyFeliz** [comment] 2022-05-16 14:28
C8 already merged the PR that will make this possible.

**Comment by DaveSanders** [comment] 2022-05-18 18:36
I'm using vitest@0.12.6 and have c8@7.11.3 installed.  It seems now that my coverage does show all of the .vue files that I don't have tests for in the coverage report, but almost all are showing 100%. Weirdly there are a couple files that are still at zero.

We made some major App changes yesterday so maybe that's affecting it, since I'm pretty sure yesterday we were seeing the files but they were listed at 0% covered.  But... seems weird that today they would go to 100%, unless coverage just isn't being calculated correctly in .vue files?

I'm kind of lost here, so I'm curious what others are seeing.

**Comment by mahmost** [comment] 2022-05-22 21:36
For me, the coverage of .vue files is also inaccurate. For some files it shows 100%, for others it shows low value while the file is just a static component with no script section or any conditionals/looping in template section, few cases show accurate coverage.

This is a repo that shows some success/failure cases of coverage :
https://github.com/mahmost/vitest-vue-coverage

Coverage html report on replit :
https://vitest-vue-coverage.mahmost.repl.co/src/components/HelloWorld.vue.html

**Comment by mervynyang** [comment] 2022-07-11 02:55
> reproduces

Are you solve it? I have the same issue.

**Comment by TheFlyer1983** [comment] 2022-08-12 09:22
I think I have a similar issue here.

Using:
- Vitest: 0.21.1
- Vite: 3.0.5
- c8: 7.12.0
- Vue: 3.2.25
- Node 16.15.1

Current config:
![image](https://user-images.githubusercontent.com/36920884/184324839-1a5ac142-d46e-4c7c-9815-f4b2c1245a9a.png)

Current Report:
![image](https://user-images.githubusercontent.com/36920884/184324935-6ab4d6d2-e49d-4dfc-b407-13d02f85f966.png)

I'm not sure if I'm doing something wrong or if it is part of this bug?

**Comment by jvanhees** [comment] 2022-09-08 13:01
So after a bit of researching, it seems that the template is not taken into account when calculating the coverage. This means that only the script is counted as coverage and if your component only has logic in the template (with `v-if`), the SFC would get 100% coverage although it's clearly not the case. The Istanbul coverage reporter does seem to take the templates into account.

**Comment by AriPerkkio** [comment] 2023-01-02 12:39
@kouts is this issue still valid? The reproduction case seems to work as expected:

```
 ✓ test/async.test.ts (1)

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  14:30:29
   Duration  1.25s (transform 719ms, setup 0ms, collect 146ms, tests 9ms)

 % Coverage report from c8
------------------|---------|----------|---------|---------|-------------------
File              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------|---------|----------|---------|---------|-------------------
All files         |    57.5 |    66.66 |       0 |    57.5 |                   
 AsyncComp.vue    |     100 |      100 |     100 |     100 |                   
 AsyncWrapper.vue |     100 |      100 |     100 |     100 |                   
 Hello.vue        |       0 |        0 |       0 |       0 | 1-17              
------------------|---------|----------|---------|---------|-------------------
```

> For me, the coverage of .vue files is also inaccurate. For some files it shows 100%,

@mahmost your reproduction case seems to work fine with changes of on-going PR #2591. It's having the same issue as #2539. 

```
------------------------|---------|----------|---------|---------|----------------------
File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s    
------------------------|---------|----------|---------|---------|----------------------
All files               |   29.29 |     6.66 |       0 |   29.29 |                      
 src                    |       0 |        0 |       0 |       0 |                      
  App.vue               |       0 |        0 |       0 |       0 | 1-81                 
  main.js               |       0 |        0 |       0 |       0 | 1-4                  
 src/components         |   41.96 |     12.5 |       0 |   41.96 |                      
  HelloWorld.vue        |   94.81 |    16.66 |       0 |   94.81 | 20,38,43-44,56-57,59 
  TheWelcome.vue        |       0 |        0 |       0 |       0 | 1-84                 
  WelcomeItem.vue       |       0 |        0 |       0 |       0 | 1-86                 
 src/components/icons   |       0 |        0 |       0 |       0 |                      
  IconCommunity.vue     |       0 |        0 |       0 |       0 | 1-7                  
  IconDocumentation.vue |       0 |        0 |       0 |       0 | 1-7                  
  IconEcosystem.vue     |       0 |        0 |       0 |       0 | 1-7                  
  IconSupport.vue       |       0 |        0 |       0 |       0 | 1-7                  
  IconTooling.vue       |       0 |        0 |       0 |       0 | 1-19                 
------------------------|---------|----------|---------|---------|----------------------
```

Maybe it's time to close this issue and open new ones if there are still existing problems.

**Closed** 2023-01-02 13:09 UTC
Labels: upstream, coverage

**Comment by tw-eugeneoei** [comment] 2023-02-16 07:18
Hi @AriPerkkio, unfortunately, i am still experiencing this issue and have opened a new issue [here](https://github.com/vitest-dev/vitest/issues/2879). i have tried using both `c8` and `istanbul` and they both yield the same result.
