### ISSUE TITLE
latest version depends on "takeCoverage" from "V8"

### ISSUE THREAD

**Issue by JoDo-dev** [vitest-dev/vitest#673] opened 2022-02-03 13:47 UTC
### Describe the bug

I´m having issues to get vitest running in a newProjekt (Vue3, Vite, TS, Vitest) using the latest Version 0.2.6.
The Vue example is broken too. So I guess it´s not a misscofiguration.

This is the Error from the console.

```
(node:12936) UnhandledPromiseRejectionWarning: file:///C:/git/command-center-vue3/node_modules/vitest/dist/create-a1bc541a.js:13
import { takeCoverage } from 'v8';
         ^^^^^^^^^^^^
SyntaxError: The requested module 'v8' does not provide an export named 'takeCoverage'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:104:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:149:5)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

 

### Reproduction

Open the Vue Example https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/vue and run `npm run test`.
See the Error in the terminal

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 8.88 GB / 15.90 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @vitejs/plugin-vue: ^2.0.0 => 2.1.0
    vite: ^2.7.10 => 2.7.13
    vitest: ^0.2.6 => 0.2.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment] 2022-02-03 13:48
Duplicate of #670

**Closed by Demivan** 2022-02-03 13:48 UTC
Labels: duplicate
