### ISSUE TITLE
import.meta.resolve is missing

### ISSUE THREAD

**Issue by Mister-Hope** [vitest-dev/vitest#7039] opened 2024-12-06 09:13 UTC
### Describe the bug

The bug is similar to https://github.com/vitest-dev/vitest/issues/5010.

It seems that vite is using vite-node to mock the import.meta object.

Ref: https://nodejs.org/api/esm.html#importmetaresolvespecifier

It's already in RC stage, and available in v18.19.0+ and v20.6.0+, with a higher support range then import.meta.filename and import.meta.dirname.

Since the above 2 are supported, it seems that it should be supported too like https://github.com/vitest-dev/vitest/pull/5011

### Reproduction

```md
TypeError: __vite_ssr_import_meta__.resolve is not a function
    at resolve (/home/mister-hope/projects/vuepress/ecosystem/tools/helper/tests/node/getInstalledStatus.spec.ts:29:19)
    at /home/mister-hope/projects/vuepress/ecosystem/tools/helper/tests/node/getInstalledStatus.spec.ts:39:12
    at file:///home/mister-hope/projects/vuepress/ecosystem/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:146:14
    at file:///home/mister-hope/projects/vuepress/ecosystem/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:533:11
    at runWithTimeout (file:///home/mister-hope/projects/vuepress/ecosystem/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:39:7)
    at runTest (file:///home/mister-hope/projects/vuepress/ecosystem/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1056:17)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at runSuite (file:///home/mister-hope/projects/vuepress/ecosystem/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1205:15)
    at runSuite (file:///home/mister-hope/projects/vuepress/ecosystem/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1205:15)
    at runFiles (file:///home/mister-hope/projects/vuepress/ecosystem/node_modules/.pnpm/@vitest+runner@2.1.8/node_modules/@vitest/runner/dist/index.js:1262:5)
```

### System Info

```shell
Not needed
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2024-12-06 09:16
Duplicate of  #6953

**Closed by sheremet-va** 2024-12-06 09:16 UTC
Labels: pending triage
