### ISSUE TITLE
Add global setting `retry`

### ISSUE THREAD

**Issue by giovannivocale-molar** [vitest-dev/vitest#3599] opened 2023-06-16 23:01 UTC
### Clear and concise description of the problem

I would like to set a global `retry` value for all tests, so that `vitest` can retry each test multiple times. This will be helpful in CI in case of flaky tests.

### Suggested solution

Add a global `retry` setting on `vitest/config`'s `defineConfig`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment] 2023-06-17 06:31
Duplicate of #3598

**Closed** 2023-06-17 06:31 UTC
