### ISSUE TITLE
Better output in UI mode for screen.debug()

### ISSUE THREAD

**Issue by innerdaze** [vitest-dev/vitest#5758] opened 2024-05-22 12:00 UTC
### Clear and concise description of the problem

Currently when in UI mode, the output of screen.debug() is sent to the console tab with the following formatting issues:
  - the first line of html tags are replaced with whitespace
  - extra whitespace appear after text nodes
  
See attached screenshot to example

### Suggested solution

- A separate tab that captures the debug output and renders it correctly
- [optional] ability to collapse nodes in the UI

### Alternative

Fix the output inside the existing console tab

### Additional context

<img width="1216" alt="Screenshot 2024-05-22 at 12 56 32" src="https://github.com/vitest-dev/vitest/assets/738492/7d5fdad4-9532-4ec3-bd5d-1e547dd9a08c">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment] 2024-05-22 13:56
Vitest doesn't have `screen.debug()` method - are you referencing [`@testing-library`](https://github.com/testing-library)'s APIs?

I would recommend to check custom reporters, and build integration on top of @testinb-library's APIs for that: https://vitest.dev/guide/reporters.html#custom-reporters

**Comment by sheremet-va** [comment] 2024-05-22 19:26
Duplicate of https://github.com/vitest-dev/vitest/issues/1279

**Closed as not planned by sheremet-va** 2024-05-22 19:26 UTC
Labels: enhancement: pending triage
