### ISSUE TITLE
Allow `test.concurrent` and `test.each` to compose (or, ban the API in the TS types / at runtime)

### ISSUE THREAD

**Issue by jakebailey** [vitest-dev/vitest#4963] opened 2024-01-15 06:32 UTC
### Clear and concise description of the problem

Right now, the API allows one to write `test.concurrent.each`. `vitest` will happily create the tests, but the the function passed to `each` only gives you access to the args, not the context. This means that you can't `expect` because there's no test context, and things break. vitest either fails with `Snapshot cannot be used outside of test`, passes (if the order just so happens to work out), or even freezes entirely (if you swap the test from non-concurrent to concurrent while the watcher runs, and then hit a key).

### Suggested solution

The API should allow the two to be mixed. Something like providing the args on the context object instead as a property (along side expect) would work.

### Alternative

The API could simply ban this pattern by disallowing chaining of `test.concurrent.each`. Arguably, this should be true now given it has bad behavior.

A workaround is to generate the tests dynamically instead, without the use of `each`, but then you can't make use of the pretty test naming and so on.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment] 2024-01-15 13:18
This is a duplicate of #4642

**Closed by sheremet-va** 2024-01-15 13:18 UTC

**Comment by jakebailey** [comment] 2024-01-15 16:34
I can't say I fully agree. Sure, both are missing the context, but if you write `test.concurrent.each`, there's no indication that this isn't going to work, and it can quite literally freeze node so badly you need to SIGKILL it and restart the terminal.

**Comment by sheremet-va** [comment] 2024-01-15 16:42
> I can't say I fully agree. Sure, both are missing the context, but if you write `test.concurrent.each`, there's no indication that this isn't going to work, and it can quite literally freeze node so badly you need to SIGKILL it and restart the terminal.

There is nothing to indicate it's not possible to run these two together. `each` just calls "test" in a for loop - are you sure the freeze is the problem of a test runner and not user code?

**Comment by jakebailey** [comment] 2024-01-15 16:46
I would be utterly shocked if that were the case; I just had one `each` test which runs a program with `execa` and snapshots its output. There was no other code in play (I am adding initial tests to https://github.com/microsoft/typescript-benchmarking).

**Comment by sheremet-va** [comment] 2024-01-15 16:49
> I would be utterly shocked if that were the case; I just had one `each` test which runs a program with `execa` and snapshots its output. There was no other code in play (I am adding initial tests to [microsoft/typescript-benchmarking](https://github.com/microsoft/typescript-benchmarking)).

Well, prepare to be shocked:

https://github.com/vitest-dev/vitest/blob/6bfdb5f4fc8ffca33633c6f347c1ee6894a1b411/packages/runner/src/suite.ts#L260-L266

I would say that calling `execa` concurrently might cause issues that you had.

**Comment by jakebailey** [comment] 2024-01-15 16:54
I read the code before I filed the issue. I'll try and produce a test. Perhaps the freeze was due to watch mode and would have happened without `each`.

**Comment by sheremet-va** [comment] 2024-01-15 18:48
Yes, possibly. By default the first Ctrl+C stops all tests but waits until they are completed naturally. The next Ctrl+C forcefully stops the process.

**Comment by jakebailey** [comment] 2024-01-15 18:49
In my case, my entire terminal froze and forced me to send SIGKILL to both node and the shell 😅
