### ISSUE TITLE
Incorrect code coverage for Vue watchers with c8

### ISSUE THREAD

**Issue by Xeyos88** [vitest-dev/vitest#2785] opened 2023-02-01 08:01 UTC
### Describe the bug

I created a test to cover the following lines of code of my in one of my Vue components (im using <script setup lang="ts">):
```javascript
const length = ref(sizes.value[0] ? sizes.value[0].value : 0)
watch(
  () => length.value,
  (newLength: number) => {
    current.value = 1
    emits('update:length', newLength)
  }
)
```

Template part:
```html
<select name="length" v-model="length">
  <option v-for="opt in sizes" :key="opt.value" :value="opt.value">
    {{ opt.label }}
  </option>
</select>
```

This is the test:
```javascript
it('should pagination emits events', async () => {
 await wrapper.vm.setCurrent(5)
    wrapper.vm.$emit('update:current', 5)
    expect(wrapper.emitted()['update:current']).toBeTruthy()
    expect(wrapper.vm.currentBlock).toBe(4)
    wrapper.vm.length = 20
    wrapper.vm.$emit('update:length', 20)
    expect(wrapper.emitted()['update:length']).toBeTruthy()
})
```
The problem is that in the code coverage report all watch content is considered covered except the watch line itself. 

![Test](https://user-images.githubusercontent.com/16436299/215984467-bed92340-5407-4937-8f56-a1a07325667c.png)

### Reproduction

Create a simple Vue component with the code above .

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz
    Memory: 19.25 GB / 24.85 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    @vitest/coverage-c8: 0.27.1 => 0.27.1 
    vite: ^4.0.0 => 4.0.4 
    vitest: ^0.25.6 => 0.25.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2023-02-01 08:31
@Xeyos88 could you create a reproduction repository that I can run. There are many blanks in this report and as I have no experience with Vue I'm unable to run this.

**Comment by Xeyos88** [comment] 2023-02-01 09:04
Hi, i have create a minimal repository to recreate the problem:
[Repo](https://github.com/Xeyos88/vitest-coverage-bug-repo).

To reproduce:
```
npm run install
npm run test:unit
```
and check the coverage report generated.

**Comment by AriPerkkio** [comment] 2023-02-01 11:04
> ### System Info
> 
> ```
>   npmPackages:
>     @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
>     @vitest/coverage-c8: 0.27.1 => 0.27.1 
>     vite: ^4.0.0 => 4.0.4 
>     vitest: ^0.25.6 => 0.25.8
> ```
>

Start by updating your `@vitest/coverage-c8` and `vitest` to latest versions. Is the issue still present?

<img src="https://user-images.githubusercontent.com/14806298/216025368-30df1e91-81a3-499c-9ad5-d116d915a0b7.png" height="120px" />

**Comment by Xeyos88** [comment] 2023-02-01 11:43
Yes, switching to version 0.28.3 in the example repo everything works.
I can't test it in the project because having many more tests the process stops before generating the report (which is why I fixed the version of vitest/c8 at 0.27.1)

![C8](https://user-images.githubusercontent.com/16436299/216033378-1a886f0b-6263-4e70-8713-e764c55e074c.JPG)

**Comment by Xeyos88** [comment] 2023-02-01 13:02
Ok trying to replicate the problem in the test repo, I realized that it does not depend on the number of tests, but to a new component introduced.
The problem might stem from the fact that this component is recursive, i.e., it calls itself.

I have updated the test repo to give you a look at it.
Without this component the report generation for which I opened this issue seems to work perfectly.

**Comment by AriPerkkio** [comment] 2023-02-02 09:40
> I have updated the test repo to give you a look at it.
> Without this component the report generation for which I opened this issue seems to work perfectly.

I'm unable to reproduce the issue. 

As the originally reported problem seems to be fixed in latest version I would suggest to close this issue. Once you can reproduce the "process stops before generating the report" -bug, open a new issue with complete reproduction steps. I'm happy to help once the issue can be reproduced.

**Closed** 2023-02-02 09:41 UTC
Labels: coverage

**Comment by AriPerkkio** [comment] 2023-02-25 08:50
> having many more tests the process stops before generating the report

@Xeyos88 Please test if `vitest@0.29.0` and `@vitest/coverage-c8@0.29.0` fixes this "process stopping" issue. In earlier versions the C8 provider wrote a lot of JSON files into the file system, and reading these may have seemed like a process being stopped. In the latest release these results are much smaller and kept in memory.
