### ISSUE TITLE
Coverage generated uncovered lines for import and export rule

### ISSUE THREAD

**Issue by schirrel** [vitest-dev/vitest#3087] opened 2023-03-27 16:32 UTC
### Describe the bug

Hi i am having trouxe with generating coverage using vitest, it shows that import and export lines ar uncovered.
I follow all the docs and all the tutorials i found that explained why it happens, but no success.

I am also having proble with vue SFC files that show no coverage for `<template>` and `<style>` also:
<img width="1084" alt="Captura de Tela 2023-03-27 às 13 31 03" src="https://user-images.githubusercontent.com/6757777/228005202-2615f604-59d0-4d9f-9adc-8d459327af39.png">
<img width="1091" alt="Captura de Tela 2023-03-27 às 13 31 16" src="https://user-images.githubusercontent.com/6757777/228005209-49e28be0-a9d2-4b64-9645-22ade9ddcdb7.png">

Even add a sample defaault spec for .vue files, it not cover 100% and show missing coverage for html things like closing  ` </div>`??
<img width="1135" alt="Captura de Tela 2023-03-27 às 13 58 23" src="https://user-images.githubusercontent.com/6757777/228012467-3969a9a5-e495-486e-a72c-e6e8d84681fa.png">

Other vue files (helloword.vue) points no covered for import line, look https://sonarcloud.io/code?id=vue-vitest-ts&selected=vue-vitest-ts%3Asrc%2Fcomponents%2FHelloWorld.vue
<img width="741" alt="Captura de Tela 2023-03-27 às 13 59 14" src="https://user-images.githubusercontent.com/6757777/228012662-dff8ab9b-a298-40cb-8e87-33e06fcd1e28.png">

### Reproduction

Repository https://github.com/schirrel/vue-vitest-ts-coverage-problems
Sonar Cloude project analysis https://sonarcloud.io/code?id=vue-vitest-ts

Now can be seen the export file being take in consideration https://sonarcloud.io/code?id=vue-vitest-ts&selected=vue-vitest-ts%3Asrc%2Fhelpers%2Findex.ts

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 1.19 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 111.0.1
    Safari: 16.2
  npmPackages:
    @vitest/coverage-c8: ^0.29.2 => 0.29.2 
    vitest: ^0.29.2 => 0.29.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2023-03-28 08:12
@schirrel does the default branch in [a5fa05bca49a3d14679335babdf593511b4dcf98](https://github.com/schirrel/vue-vitest-ts-coverage-problems/tree/a5fa05bca49a3d14679335babdf593511b4dcf98) reproduce this?

In the HTML and lcov reports the line 4 of `src/App.vue` is covered. There are no uncovered `import` statements.

![image](https://user-images.githubusercontent.com/14806298/228171887-07ace2a3-9f77-46a9-be09-9de66fe2960b.png)

```
// coverage/lcov.info, used by Sonar
SF:src/App.vue
DA:1,1
DA:2,1
DA:3,1
DA:4,1
DA:5,1
DA:6,1
DA:7,1
DA:8,1
DA:9,1
DA:10,1
DA:11,1
DA:12,1
DA:13,1
DA:14,1
DA:15,1
DA:16,1
DA:17,1
DA:18,1
DA:19,1
DA:20,1
DA:21,1
DA:22,1
DA:23,1
DA:24,1
```

Could you write a step-by-step instructions how to reproduce this issue?

**Comment by AriPerkkio** [comment] 2023-03-29 12:12
> Also you can look at src/main.ts that shows the import as uncovered https://sonarcloud.io/code?id=vue-vitest-ts&selected=vue-vitest-ts%3Asrc%2Fmain.ts

None of the tests load `src/main.ts` so it is included by the `all: true` option. The `c8` will then mark all lines as uncovered as the whole file was not loaded. This is just how `c8` / V8 coverage works. The `@vitest/coverage-istanbul` does not have this issue.

I can reproduce the `src/components/HelloWorld.vue` issue now and see the uncovered import statement there. Debugging the root cause of this is not easy task. It would help if you could try and update all your dependencies to latest versions - especially the `vite-plugin-vue`.

**Comment by schirrel** [comment] 2023-03-29 18:05
Thanks for the response @AriPerkkio 
> I can reproduce the src/components/HelloWorld.vue issue now and see the uncovered import statement there. Debugging the root cause of this is not easy task. It would help if you could try and update all your dependencies to latest versions - especially the vite-plugin-vue.  

Only updating the dependencies causes no effects

About what you said here
>None of the tests load src/main.ts so it is included by the all: true option. The c8 will then mark all lines as uncovered as the whole file was not loaded. This is just how c8 / V8 coverage works. The @vitest/coverage-istanbul does not have this issue.   

 i've using `all: true` because if i don't files that has no tests are being ignored and i want to force to validate to files have tests. Is there a other configuration? if i remove it i get more trouble, i mean this on my real project

For the record i've update dependencies, remove the all like you said @AriPerkkio, it stops to show import as uncoverage, but show a lot of closing htmls tags as uncoverage.
look https://sonarcloud.io/component_measures?metric=coverage&selected=vue-vitest-ts-update-without-all%3Asrc%2Fcomponents%2FHelloWorld.vue&view=list&id=vue-vitest-ts-update-without-all

**Comment by schirrel** [comment] 2023-03-30 13:23
@AriPerkkio indeed change from c8 to istanbul quite solve a bunch of problems, imports and html tags. Maybe is a problem with c8?

**Comment by AriPerkkio** [comment] 2023-03-30 13:38
> Maybe is a problem with c8?

The _"import statements marked as uncovered when `all:true` is used"_ is not really a problem - that's just the way it works. It's not a bug either. When `all: true` is enabled and an untested file is loaded, `c8` will simply mark whole file as uncovered. It does not check what code each line contains. Even comments are marked uncovered. More similar issues of `c8` are described here: https://github.com/vitest-dev/vitest/issues/1252.

But the uncovered ending HTML tags of tested files sounds like a real issue in source maps. The Vue compiler has had these issues before - that's why I'm not really eager to start debugging [`vite-plugin-vue2`](https://github.com/schirrel/vue-vitest-ts-coverage-problems/blob/a5fa05bca49a3d14679335babdf593511b4dcf98/package.json#L32) that is even marked as [end-of-life](https://github.com/underfin/vite-plugin-vue2/blob/f11af68c85f4844631ab7ac9507f1454a7655000/README.MD?plain=1#L5) at this point. Debugging source maps and coverage results is a slow task.

I would recommend to use the `@vitest/coverage-istanbul` when these kind of issues come up with `c8`.

**Closed** 2023-05-12 20:16 UTC
Labels: coverage
