### ISSUE TITLE
[Vitest 3] "`Intl.Collator` is not a constructor" when using fake timers

### ISSUE THREAD

**Issue by spaceemotion** [vitest-dev/vitest#7142] opened 2024-12-28 15:52 UTC
### Describe the bug

I am trying to upgrade to the latest Vitest 3 Beta. Our project does not use Vite for the build-pipeline (only a simple esbuild config, in fact), and we didn't need to do anything so far to get our tests running (we don't even have a vitest config).

However, after the upgrade, we suddenly see the following error in the console:
```
Intl.Collator is not a constructor

TypeError: Intl.Collator is not a constructor
 ❯ src/services/xxxxx.ts:96:24
     94| };
     95|
     96| const nameComparator = new Intl.Collator('en', {
       |                        ^
     97|   sensitivity: 'base',
     98|   numeric: true,
```

I thought it might have to do with the Vite 6 module resolution changes, but even tinkering with that one broke more than i liked. The project runs on Node v22, and Vitest v2 has worked without an issue so far.

The error also happens when I run vitest in isolation mode.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-ptkpew1o?file=test%2Fbasic.test.ts

Once the async import gets resolved, Vitest doesn't know what `Intl.` is.

### System Info

```shell
System:
  OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  CPU: (16) x64 AMD Ryzen 9 7950X 16-Core Processor
  Memory: 25.82 GB / 35.24 GB
  Container: Yes
  Shell: 3.6.1 - /usr/bin/fish
Binaries:
  Node: 22.2.0 - /mnt/wslg/runtime-dir/fnm_multishells/40485_1735384937185/bin/node
  npm: 10.7.0 - /mnt/wslg/runtime-dir/fnm_multishells/40485_1735384937185/bin/npm
  pnpm: 8.15.5 - /mnt/wslg/runtime-dir/fnm_multishells/40485_1735384937185/bin/pnpm
  bun: 1.1.8 - ~/.bun/bin/bun
npmPackages:
  vitest: 3.0.0-beta.3 => 3.0.0-beta.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment] 2024-12-29 03:36
This looks like due to fake timers. Here is a simplified repro https://stackblitz.com/edit/vitest-dev-vitest-96ajsug5?file=test%2Fbasic.test.ts

In v3, we changed the behavior of `toFake` to fake everything globally available https://github.com/vitest-dev/vitest/pull/6288, which also includes `Intl`. There is a bug which breaks some `Intl.xxx` in `@sinonjs/fake-timers` and it's been fixed on upstream by https://github.com/sinonjs/fake-timers/pull/479, but we are still using fairly old version `11.1.0` (latest is 14.0.0), which is before the fix.

There's a PR https://github.com/vitest-dev/vitest/pull/7097 but probably we haven't reviewed yet.

In the mean time, you can explicitly set `toFake` to be same as v2 like

```js
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    fakeTimers: {
      toFake: [
        'setTimeout',
        'clearTimeout',
        'setInterval',
        'clearInterval',
        'setImmediate',
        'clearImmediate',
        'Date',
      ],
    },
  },
});
```

**Comment by spaceemotion** [comment] 2024-12-29 14:43
Thanks! that did the trick. I updated the title for this issue accordingly.

**Comment by hi-ogawa** [comment] 2024-12-30 07:12
@spaceemotion feel free to try it out pre-release of the PR https://github.com/vitest-dev/vitest/pull/7097#issuecomment-2565101092 I confirmed the repro is fixed with this https://stackblitz.com/edit/vitest-dev-vitest-52wgjnc6?file=package.json

**Closed** 2024-12-31 10:15 UTC
Labels: p3-minor-bug
