### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by Protagonistss** [vitest-dev/vitest#320] opened 2021-12-26 11:49 UTC
### Describe the bug

An reference error while the component of vue was unit testing.

### Reproduction

/// <reference types="vitest/global.d.ts" />

import { mount } from '@vue/test-utils'
import Button from '../src/index.vue'

test('mount component', async () => {
  const wrapper = mount(Button, {
    props: {
      type: 'default'
    }
  })
  expect(wrapper.html()).toContain('default')
})

### System Info
  System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 58.55 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.1
```


### Used Package Manager

pnpm

### Logs

```shell
FAIL  packages/components/button/__tests__/button.spec.ts > mount component
ReferenceError: document is not defined
 ❯ Object.mount node_modules/.pnpm/@vue+test-utils@2.0.0-rc.18_vue@3.2.26/node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.js:7817:14
    7815|     addToDoNotStubComponents(component);
    7816|     registerStub({ source: originalComponent, stub: component });
    7817|     var el = document.createElement('div');
       |              ^
    7818|     if (options === null || options === void 0 ? void 0 : options.…
    7819|         var to = void 0;
 ❯ packages/components/button/__tests__/button.spec.ts:7:18
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2021-12-26 14:27
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

> Have you enable the jsdom env?

**Closed** 2021-12-26 14:27 UTC

**Comment by Protagonistss** [comment] 2021-12-27 04:28
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > Have you enabled the jsdom env?

nope! 
but i created a demo project, can u take a look at it for me?
[demo project](https://stackblitz.com/edit/node-1yzcrz?file=vitest.config.ts)
