### ISSUE TITLE
Broken stack trace

### ISSUE THREAD

**Issue by vlechemin** [vitest-dev/vitest#1054] opened 2022-03-30 02:01 UTC
### Describe the bug

The stack trace is incorrect because of this line:
https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/error.ts#L15

It is fixed with this:
`return join(stack.file, stack.sourcePos.source)`

### Reproduction

I'm sorry I couldn't reproduce it outside of my project, im not sure when it goes through this test.

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 142.72 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - ~/.nvm/versions/node/v17.2.0/bin/node
    npm: 8.1.4 - ~/.nvm/versions/node/v17.2.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Edge: 99.0.1150.55
    Safari: 15.4
  npmPackages:
    @vitejs/plugin-react: ^1.2.0 => 1.2.0 
    @vitejs/plugin-vue: ^2.1.0 => 2.1.0 
    vite: ^2.9.0-beta.0 => 2.9.0-beta.0 
    vitest: 0.8.0 => 0.8.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2022-04-10 06:26
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-04-10 06:26 UTC
Labels: needs reproduction
