### ISSUE TITLE
"Can't find stylesheet to import" when using --threads=false

### ISSUE THREAD

**Issue by oneillsp96** [vitest-dev/vitest#1230] opened 2022-05-03 16:21 UTC
### Describe the bug

"vitest run" works fine, tests pass
"vitest run --threads=false" errors out with "can't find stylesheet to import"

in my repro, styles.scss is imported into App.tsx, and it in turn imports a stylesheet called "colors.scss"

I was only using threads=false to try to get around a Node [issue ](https://github.com/vitest-dev/vitest/issues/1191)in my CI build, but it doesn't work.

### Reproduction

[https://github.com/oneillsp96/vitest-error-2](https://github.com/oneillsp96/vitest-error-2)

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 16.54 GB / 31.83 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 100.0.4896.127
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.32)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^1.3.0 => 1.3.1
    vite: ^2.9.5 => 2.9.5
    vitest: ^0.9.3 => 0.9.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Crevitus** [comment] 2022-05-11 08:41
I can confirm I am also encountering this issue on the latest version of vitest with threading turned off:

```
Error: Can't find stylesheet to import.
  ╷
2 │ @import "bootstrap/scss/bootstrap";
...
```

This is imported into my `index.scss` file. The main Vite build works.

Versions:

 ```
npmPackages:
    @vitejs/plugin-react: 1.3.2
    vite: 2.9.8 
    vitest: 0.12.4
```

**Comment by nathanchicken** [comment] 2022-05-16 09:24
I'm getting this too, but doesn't matter if I'm using threads=false or not. 

`vite build` runs fine though.

I have in my main config this

```
css: {
      preprocessorOptions: {
        scss: {
          additionalData: `
            @use "sass:math";
            @import "@/styles/_variables.scss";
            @import "@/styles/_mixins.scss";
          `,
        },
      },
```

And `npx vitest run` gives me this:

```
Error: Can't find stylesheet to import.
 @import "@/styles/_variables.scss";
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I"ve tried a few combinations of filenames with and without aliases but to no avail.

**Comment by ChenYCL** [comment] 2022-05-19 10:44
Hello,get same issue. lerna project , i need some scss file import from theme pkg.
<img width="826" alt="image" src="https://user-images.githubusercontent.com/25706676/169275606-9e260263-63cd-4199-bb76-351bbf53e993.png">
Have any solution solve this? thx

**Comment by tansin** [comment] 2022-05-19 13:48
I have the same issue. I have found that the actual error occurs even though the resolution may have worked properly.

1. The style is imported in the vue component like this:
```vue
<style lang="scss" scoped>
@import "../../../variables";
// ...
```
2. When I start vitest I've got this error, as we all:
```
Can't find stylesheet to import.
  ╷
2 │ @import "../../../variables";
  │         ^^^^^^^^^^^^^^^^^^^^
  ╵
```
3. Then I've __deleted__ the style file and got the same error. (restored the file afterwards).
4. Then I've added following resolve config to the `vitest.config.ts`. It just replaces the relative path string found in import directive by the actual absolute path. (I've tested also various regex patterns and file names getting same result, but this config here is the simplest one):
```javascript
export default defineConfig({
  // ...
  resolve: {
    alias: [
      {
        find: "../../../variables",
        replacement: "/Users/user/git/project/_variables.scss",
      },
    ],
  },
})
```
5. Run vitest and still got the same error. Wait, what? I've provided the correct absolute path as replacement. Hmm.
6. But then I've __deleted__ the style file again and got a new error:
```
Error: ENOENT: no such file or directory, open '/Users/user/git/project/_variables.scss'
```
It means, that even after resolving to absolute path manually the resolved path seems to not be consumed properly.

**Comment by nathanchicken** [comment] 2022-05-19 15:08
The only real place I get this being an issue is in the `preprocessorOptions` part.

So to circumvent the issue for now I'm doing this to basically ensure that it's an absolute path. I'm basically duplicating the alias and it seems to be working. Within the SCSS files in the repo that a test they are using relative paths. 

```javascript
{
resolve: {
  {
      find: /^@\//,
      replacement: `${path.resolve(__dirname, 'src')}/`,
    },
},
// ...
css: {
      preprocessorOptions: {
        scss: {
          additionalData: `
            @use "sass:math";
            @import "${path.resolve(__dirname, 'src')}/styles/_variables.scss";
            @import "${path.resolve(__dirname, 'src')}/styles/_mixins.scss";
            
          `,
        },
      },
    },
 }
```

**Comment by ChenYCL** [comment] 2022-05-20 02:32
// vite.config.ts  it works
  
  resolve: {
    alias: [
      {
        find: /^~@lui/,
        replacement: `${path.resolve(__dirname, 'packages')}/`,
      },
    ],
  },

**Comment by yichengsong318** [comment] 2022-05-27 17:51
I am getting the same issue.
Vue3 + quasar

// vite.config.js 
quasar({
  sassVariables: 'src/styles/quasar.variables.scss'
})

**Comment by nicolas-camacho** [comment] 2022-06-05 21:41
Since it works with absolute routes, I ended up creating an alias for my variables file

## Project info
`Framework: Next JS`


## vitest.config.ts
```ts
export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
  },
  resolve: {
      alias: [
          {
              find: 'variables',
              replacement: `${path.resolve(__dirname)}/styles/variables.scss`
          }
      ]
  }
})
```

## {file}.scss

`@import 'variables';`

It is working for me right now but it is not an optimal solution

**Comment by Lyokolux** [comment] 2022-06-27 11:55
Ok it seems that relative import are broken.
I have the same issue as https://github.com/vitest-dev/vitest/issues/1230#issuecomment-1131716834

If the main scss files import other files, then the paths have to be absolute, else it will return the error `Can't find stylesheet to import.`.

**Comment by alexmccabe** [comment] 2022-09-28 15:12
None of the above suggestions seem to be working for me

**Comment by alexmccabe** [comment] 2022-09-29 09:40
The workaround I got to behave was:

```js
test: {
 minThreads: 0,
 maxThreads: 1,
}
```

This seems silly since this is effectively doing the same thing? 🤔

**Closed** 2022-11-29 09:03 UTC
Labels: bug, help wanted
