### ISSUE TITLE
Insufficient documentation for migration to 0.31

### ISSUE THREAD

**Issue by golergka** [vitest-dev/vitest#3332] opened 2023-05-09 12:30 UTC
### Describe the bug

I have this mocking code in my codebase:

```Typescript
const mockedGoogleLogin = vi.fn();

vi.mock("@react-oauth/google", async () => {
  const Google = await vi.importActual<typeof import("@react-oauth/google")>(
    "@react-oauth/google"
  );
  return {
    ...Google,
    useGoogleLogin: vi.fn(() => mockedGoogleLogin),
  };
});
```

And this check later on:

```Typescript
    expect(mockedGoogleLogin).toHaveBeenCalledOnce();
```

In 0.30 version, this check passed, but in 0.31, it does not. I think it's connected to [`vi.hoisted` change](https://github.com/vitest-dev/vitest/pull/3258).

Now, **I don't think it's a bug in vitest code**. However, I think that there's **insufficient documentation** on the way to properly migrate — so this bug is about documentation quality, not code.

I don't understand how exactly did behaviour of the above code change. I would assume that if `mockedGoogleLogin` didn't exist at hoist time, it should have thrown something trying to access it. And I don't understand exact steps needed to rewrite it for 0.31 — some examples and migration guide would be helpful.

### Reproduction

1. Decrease IQ to my level
2. Try to port working code to 0.31 using only release notes
3. Get confused

### System Info

```shell
I'm not really smart
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by golergka** [comment] 2023-05-09 13:32
@sheremet-va this is an issue about documentation, not code. The only steps needed to reproduce is are already explained in the issue:

1. Decrease IQ to my level
2. Try to port working code to 0.31 using only release notes
3. Get confused

**Comment by donalmurtagh** [comment] 2023-05-09 13:37
> I don't understand the problem that needs documenting. The changes to mocks API were not breaking

@sheremet-va Then why is it described in the [release notes](https://github.com/vitest-dev/vitest/releases/tag/v0.31.0) as a breaking change?

In my project, some tests are failing after upgrading from v0.30.1 to v0.31.0, so it is a breaking change for me.

**Comment by sheremet-va** [comment] 2023-05-09 13:39
> In my project, some tests are failing after upgrading from v0.30.1 to v0.31.0, so it is a breaking change for me.

It's breaking if Vitest is used with public API, the usage did not change. If you have any problems, create a reproduction and we will fix it.

**Comment by donalmurtagh** [comment] 2023-05-09 13:43
> It's breaking if Vitest is used with public API, the usage did not change.

Do you mean it's a change to the API because `hoisted` didn't exist in the previous version, but all of the functions that existed in the previous version should behave the same in v0.31.0?

**Comment by sheremet-va** [comment] 2023-05-09 13:47
> Do you mean it's a change to the API because hoisted didn't exist in the previous version, but all of the functions that existed in the previous version should behave the same in v0.31.0?

By public API I mean `startVitest` from `vitest/node` entry point (although it's still quite hard to break). But the main reason why it's breaking is that you cannot use `browser` in `poolMatchGlobs`. Since it was removed in the same commit, it got marked together. I can move the mocking change out of the "breaking changes" section manually, I guess.

**Comment by golergka** [comment] 2023-05-09 14:02
Thanks for clarifying. Yes, removing the "Breaking change" in changelogs would solve this issue — right now it looks like it needs migrating.

This means my issues are actually a bug with vitest code and not me being stupid. I'll create a separate issue for this.

**Comment by sheremet-va** [comment] 2023-05-10 14:31
I changed the release notes. I also suspect that you might've had the same issue described in https://github.com/vitest-dev/vitest/issues/3340 If so, it should be fixed in the next version.

Please, feel free to create an issue with reproduction if you have any unexpected changes that were caused with the latest release.

**Closed by sheremet-va** 2023-05-10 14:31 UTC
Labels: need reproduction
