### ISSUE TITLE
expose the vite-node bin

### ISSUE THREAD

**Issue by goldylucks** [vitest-dev/vitest#2580] opened 2022-12-30 12:38 UTC
### Clear and concise description of the problem

I'd like to run vite-node locally instead of `pnpx vite-node`, which pnpm has to resolve in runtime

### Suggested solution

expose the bin file vite-node

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment] 2022-12-30 12:40
Duplicate of https://github.com/vitest-dev/vitest/issues/2554?

**Comment by goldylucks** [comment] 2022-12-30 13:18
I've seen that, and it is true that solving #2554 might end up closing this as well, but just exposing the bin, AFAIK is pretty cheap, and it anyway it pushes #2554 forward.

Thoughts?

**Comment by sheremet-va** [comment] 2023-05-30 18:29
Bin was always exposed.

**Closed by sheremet-va** 2023-05-30 18:29 UTC
