### ISSUE TITLE
`resolve.alias` does not resolve correctly when been resolved as soft links in `node_modules`

### ISSUE THREAD

**Issue by JounQin** [vitest-dev/vitest#4842] opened 2024-01-01 15:22 UTC
### Describe the bug

----------------------------------|---------|----------|---------|---------|-------------------
File                              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------------------------------|---------|----------|---------|---------|-------------------
All files                         |    0.84 |        0 |       0 |    1.18 |                   
 eslint-mdx/lib                   |       0 |        0 |       0 |       0 |                   
  index.es2015.mjs                |       0 |        0 |       0 |       0 | 5-196             
 eslint-mdx/src                   |    0.73 |        0 |       0 |    1.17 |                   
  helpers.ts                      |       0 |        0 |       0 |       0 | 1-140             
  index.ts                        |     100 |      100 |     100 |     100 |                   
  meta.ts                         |       0 |      100 |     100 |       0 | 1-3               
  parser.ts                       |       0 |        0 |       0 |       0 | 1-100             
  sync.ts                         |       0 |      100 |     100 |       0 | 1-11              
  tokens.ts                       |       0 |        0 |       0 |       0 | 6-272             
  worker.ts                       |       0 |        0 |       0 |       0 | 3-775             
 eslint-plugin-mdx/lib            |       0 |        0 |       0 |       0 |                   
  index.es2015.mjs                |       0 |        0 |       0 |       0 | 7-508             
 eslint-plugin-mdx/src            |   33.33 |        0 |       0 |   45.45 |                   
  helpers.ts                      |       0 |        0 |       0 |       0 | 1-15              
  index.ts                        |     100 |      100 |     100 |     100 |                   
  meta.ts                         |       0 |      100 |     100 |       0 | 1-3               
 eslint-plugin-mdx/src/configs    |       0 |        0 |       0 |       0 |                   
  base.ts                         |       0 |      100 |     100 |       0 | 3                 
  code-blocks.ts                  |       0 |      100 |     100 |       0 | 3                 
  flat.ts                         |       0 |      100 |     100 |       0 | 2-30              
  index.ts                        |       0 |      100 |       0 |       0 | 3-11              
  overrides.ts                    |       0 |        0 |     100 |       0 | 2-13              
  recommended.ts                  |       0 |        0 |       0 |       0 | 1-95              
 eslint-plugin-mdx/src/processors |       0 |        0 |       0 |       0 |                   
  helpers.ts                      |       0 |        0 |       0 |       0 | 1-23              
  index.ts                        |       0 |      100 |       0 |       0 | 1-8               
  options.ts                      |       0 |        0 |       0 |       0 | 9-55              
  remark.ts                       |       0 |        0 |       0 |       0 | 2-67              
 eslint-plugin-mdx/src/rules      |       0 |        0 |       0 |       0 |                   
  index.ts                        |       0 |      100 |       0 |       0 | 2-8               
  remark.ts                       |       0 |        0 |       0 |       0 | 1-115             
----------------------------------|---------|----------|---------|---------|-------------------

I'd expect no `eslint-mdx/lib` and `eslint-plugin-mdx/lib` files here.

### Reproduction

https://github.com/mdx-js/eslint-mdx/actions/runs/7378227896/job/20073106362?pr=508#step:6:27

https://github.com/mdx-js/eslint-mdx/tree/build/yarn_v4

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 11.77 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/89034_1703864877615/bin/node
    Yarn: 4.0.2 - ~/Library/Caches/fnm_multishells/89034_1703864877615/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/89034_1703864877615/bin/npm
    bun: 1.0.20 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 120.1.61.109
    Chrome: 120.0.6099.129
    Safari: 17.2.1
  npmPackages:
    @vitest/coverage-istanbul: ^1.1.1 => 1.1.1 
    vitest: ^1.1.1 => 1.1.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2024-01-02 11:03
> I'd expect no eslint-mdx/lib and eslint-plugin-mdx/lib files here.

Why you don't expect them?

**Comment by JounQin** [comment] 2024-01-02 11:10
Because I have `resolve.alias` settings with `eslint-mdx`/`eslint-plugin-mdx`? `eslint-mdx/src/index.ts` should be resolved.

**Comment by sheremet-va** [comment] 2024-01-02 11:18
And how is `node_modules` involved here? This is hardly a minimal reproduction.

**Comment by JounQin** [comment] 2024-01-02 12:29
I'm using `eslint-plugin-mdx@link:packages/eslint-plugin-mdx`.

See also https://github.com/mdx-js/eslint-mdx/blob/cf077e5e0e6d85ccb4dbeca142cb6e30e67dde8d/package.json#L60

**Comment by sheremet-va** [comment] 2024-01-02 13:07
`resolve.alias` is used only for:

- static/dynamic imports using ESM syntax (`await import` or `import * from`)
- the file that does the import is processed (inlined) by Vitest. Libraries by default are not inlined if Node.js can process them without Vite (file is correct CJS/ESM file)

So, try adding the library to [`server.deps.inline`](https://vitest.dev/config/#server-deps-inline) first.

**Comment by JounQin** [comment] 2024-01-04 13:39
<img width="1240" alt="image" src="https://github.com/vitest-dev/vitest/assets/8336744/2fdcf860-b33a-4da8-b2aa-b31815ea898b">

@sheremet-va Seems not working neither.

**Comment by sheremet-va** [comment] 2024-01-04 17:30
Inlining your own package doesn't do anything - your source code is already inlined. The option is located inside `deps` name because it is meant to list dependencies that need inlining.

**Comment by JounQin** [comment] 2024-01-04 17:36
So what should I do then? I can not inline eslint because I have to use setup file which includes a specific eslint subpath to preload it for testing. This approach works well with jest.

See also  https://github.com/mdx-js/eslint-mdx/blob/master/package.json#L86-L88

**Comment by sheremet-va** [comment] 2024-01-04 17:42
I don't know how `linter.js` file works, so I cannot give any recommendations. All I can say is that supporting aliases and transformations in `require` is out of scope for Vitest. For aliases to apply, the file should be processed by Vitest. By default, all files outside of `node_modules` are processed. You have `./lib` in your coverage because it was included somehow.

**Comment by sheremet-va** [comment] 2024-01-04 17:48
Also, it's possible that you have this file in your coverage because coverage includes all files by default. You can disable it with this config:

```ts
export default {
  test: {
    coverage: {
      all: false
    }
  }
}
```

Or you can also include only required files:

```ts
export default {
  test: {
    coverage: {
      include: ['./packages/*/src/**/*.ts']
    }
  }
}
```

**Comment by JounQin** [comment] 2024-01-04 23:43
The main issue is eslint will load the eslint-plugin-mdx and run some test cases, but if lib folder is resolved, the coverage reported will be totally unexpected, eslint related test cases will not increase the coverage because of the lib folder.

**Comment by sheremet-va** [comment] 2024-01-05 08:04
The issue with the coverage has nothing to do with `resolve.alias`. I checked that adding `all: false` to coverage options doesn't show any files that were not running during tests. I am closing the issue now.

**Closed by sheremet-va** 2024-01-05 08:04 UTC
Labels: pending triage

**Comment by sheremet-va** [comment] 2024-01-05 09:49
> @sheremet-va I don't quite understand what's your meaning.

Use this config options for coverage:

```ts
export default defineConfig({
  test: {
    coverage: {
      provider: 'istanbul',
      all: false,
    }
  }
})
```

It will only include files that you import in your tests.

**Comment by JounQin** [comment] 2024-01-05 10:57
<img width="783" alt="image" src="https://github.com/vitest-dev/vitest/assets/8336744/64816d9d-f2ae-4723-908d-ff8c70960dbc">

@sheremet-va Is that really working as expected? Only the `index.ts` files are covered...

**Comment by sheremet-va** [comment] 2024-01-05 10:58
cc @AriPerkkio

**Comment by AriPerkkio** [comment] 2024-01-05 12:26
Files that were loaded through Vite are present on coverage report. I guess ESLint loads your files using `require`?

**Comment by JounQin** [comment] 2024-01-05 12:32
> I guess ESLint loads your files using `require`?

Yes.

---

OK, I'll try to provide a minimal reproduction.

**Comment by AriPerkkio** [comment] 2024-01-05 12:38
There's some discussion about coverage and `require` here: 

- https://github.com/vitest-dev/vitest/discussions/3851
- https://github.com/vitest-dev/vitest/discussions/2911

But the main thing is that Vite intercepts only `import` and `import()`. Code that is run using `require`, `child_process` or `worker_threads` is not transformed. Vitest features like coverage and mocks won't work there.

**Comment by JounQin** [comment] 2024-01-05 12:41
Thanks for your references, I think I have to stick on jest for now.
