### ISSUE TITLE
Auto-mocking classes doesn't work in browser mode

### ISSUE THREAD

**Issue by scottohara** [vitest-dev/vitest#6563] opened 2024-09-25 04:13 UTC
### Describe the bug

Apologies if this is by design, but I couldn't find anywhere that confirms this.

When mocking a module that exports a Class, the expectation is that without passing a factory, that all exports (including the exported Class are automocked).

This seems to work as expected with `--environment=jsdom`, but when used in `--browser=chrome` it fails with:

```
TypeError: Class constructor <name of class> cannot be invoked without 'new'
```

The error in browser mode can be avoided by supplying a factory to the mock function, e.g. instead of:

```js
vi.mock("./foo.js");
```

we can pass:

```js
vi.mock("./foo.js", () => {
  return {
    Foo: vi.fn()
  };
});
```

But it is unclear why this additional boilerplate is only needed in browser mode?

### Reproduction

https://github.com/scottohara/vitest-browser-automock-class

### System Info

```shell
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1
    Memory: 88.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.asdf/installs/nodejs/20.11.1/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/20.11.1/bin/yarn
    npm: 10.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 9.9.0 - ~/.asdf/installs/nodejs/20.11.1/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.59
    Chrome Canary: 131.0.6737.0
    Safari: 18.0
  npmPackages:
    @vitest/browser: 2.1.1 => 2.1.1 
    vitest: 2.1.1 => 2.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2024-09-25 08:42
Spying on classes doesn't work at all: https://github.com/vitest-dev/vitest/pull/6160

Closing this as a duplicate of https://github.com/vitest-dev/vitest/issues/6104

**Closed by sheremet-va** 2024-09-25 08:42 UTC
Labels: pending triage
