### ISSUE TITLE
Runner panics with latest `vitest`, `jsdom` and `module-from-string`

### ISSUE THREAD

**Issue by vekunz** [vitest-dev/vitest#4175] opened 2023-09-25 11:01 UTC
### Describe the bug

After updating from Vitest `0.34.2` to `0.34.3` (or any later version) we get a panic error in the unit tests:

```
Error: panic: interface conversion: interface {} is map[string]interface {}, not []uint8

debug.Stack (runtime/debug/stack.go:24)
helpers.PrettyPrintedStack (internal/helpers/stack.go:9)
main.(*serviceType).handleIncomingPacket.func1 (cmd/esbuild/service.go:269)
panic (runtime/panic.go:884)
main.(*serviceType).handleTransformRequest (cmd/esbuild/service.go:980)
main.(*serviceType).handleIncomingPacket (cmd/esbuild/service.go:285)
main.runService.func4 (cmd/esbuild/service.go:192)
created by main.runService (cmd/esbuild/service.go:191)
 ❯ node_modules/esbuild/lib/main.js:801:29
 ❯ responseCallbacks.<computed> node_modules/esbuild/lib/main.js:680:9
 ❯ handleIncomingPacket node_modules/esbuild/lib/main.js:733:9
 ❯ Socket.readFromStdout node_modules/esbuild/lib/main.js:656:7
 ❯ Socket.emit node:events:514:28
```

### Reproduction

It seems to be a combination from the latest version of Vitest, and `jsdom` and the package `module-from-string`. I created a minimal reproduction repo with the error.

https://github.com/vekunz/vitest-panic-reproduction

Just run the tests with `npm run test`. If you either remove `jsdom` as the environment or downgrade to Vitest `0.34.2`, the error disappears.

### System Info

```shell
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M2 Pro
    Memory: 66.47 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6
  npmPackages:
    vitest: 0.34.5 => 0.34.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-09-28 09:44
Looks like this is happening because of the Buffer Uint8Array mismatch. jsdom overrides these Node.js globals now, which causes this issue. More info: #4043

**Comment by sheremet-va** [comment] 2024-02-16 15:40
Closing this as it is a duplicate of #4043

**Closed by sheremet-va** 2024-02-16 15:40 UTC
Labels: pending triage
