### ISSUE TITLE
vitest/browser fails to run when the dependent package has chai v5

### ISSUE THREAD

**Issue by odanado** [vitest-dev/vitest#5332] opened 2024-03-04 14:10 UTC
### Describe the bug

If a project has chai v5 as a dependency, tests that used to succeed will now fail.

Test case:
```ts
import { test, expect } from "vitest";

test("sample", () => {
  expect(1 + 1).toBe(2);
});
```

Error message:
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Preload Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Vitest failed to load its runner after 30 seconds.
 ❯ tryCall ../../../../../../__vitest_browser__/tester-uNa8VWMH.js:313:36
 ❯ Object.runTests ../../../../../../__vitest_browser__/tester-uNa8VWMH.js:404:20

Caused by: SyntaxError: The requested module '/node_modules/@vitest/expect/node_modules/chai/index.js?v=eec8ee4f' does not provide an export named 'default'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  no tests
      Tests  no tests
     Errors  1 error
   Start at  23:07:45
   Duration  33.66s (transform 0ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)
```

### Reproduction

https://github.com/odan-sandbox/vitest-browser-issue-with-chai-v5

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 121.56 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.local/share/asdf/installs/nodejs/18.12.1/bin/node
    Yarn: 1.22.19 - ~/.local/share/asdf/installs/nodejs/18.12.1/bin/yarn
    npm: 8.19.2 - ~/.local/share/asdf/plugins/nodejs/shims/npm
    pnpm: 8.10.5 - ~/.local/share/asdf/installs/nodejs/18.12.1/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.1
  npmPackages:
    @vitest/browser: 1.3.1 => 1.3.1 
    vitest: 1.3.1 => 1.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2024-03-04 14:15
Chai 5 is not supported at the moment.

**Comment by hi-ogawa** [comment] 2024-03-05 01:38
I think this is yet another case of missing `optimizeDeps` of Vitest cjs dependencies though I'm not really why this manifests on when there are multiple chai versions.

In your reproduction, adding this should should help for the time being.

```ts
import { defineConfig } from "vitest/config";

export default defineConfig({
  optimizeDeps: {
    include: ["vitest > @vitest/expect > chai"]
  },
  test: {
    browser: {
      enabled: true,
      name: "chromium",
      provider: "playwright",
    },
  },
});
```

**Comment by hi-ogawa** [comment] 2024-03-05 02:08
Hmm, maybe this might be tricky since `loupe` is in `optimizeDeps.exclude` https://github.com/vitest-dev/vitest/pull/5082 and this is happening when I add `vitest > @vitest/expect > chai` in `optimizeDeps.include` and run `test/browser`:

```
[vite] Internal server error: Failed to resolve import "loupe" from "node_modules/.vite/deps/chunk-R6V3PAXC.js?v=d4c039b0". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/hiroshi/code/others/vitest/test/browser/node_modules/.vite/deps/chunk-R6V3PAXC.js?v=d4c039b0:3:48
  1  |  const __vi_inject__ = { [Symbol.toStringTag]: "Module" };
  2  |  import { __vi_inject__ as __vi_esm_0__ } from './chunk-5YJXGM4D.js'
  3  |  import { __vi_inject__ as __vi_esm_1__ } from 'loupe'
```

Maybe original reproduction works only because of flat node modules, so `loupe` is always visible from `node_modules/.vite/deps`.

**Comment by zacharyvoase** [comment] 2024-07-23 23:05
I'm a little confused. `import { expect } from 'vitest'` imports Chai, and then that Chai import fails when running in the browser. How is anyone actually writing tests and running them in a browser right now without experiencing this issue? Just by not using `expect` from vitest entirely?

**Comment by sheremet-va** [comment] 2024-07-24 08:44
This should be fixed with Vitest 2

**Closed by sheremet-va** 2024-07-24 08:44 UTC
Labels: feat: browser, p3-minor-bug
