### ISSUE TITLE
Compatible with Jest Snapshots

### ISSUE THREAD

**Issue by holtwick** [vitest-dev/vitest#483] opened 2022-01-08 06:55 UTC
### Describe the bug

The format of the snapshots (inline and external) is not compatible with Jest. 

### Reproduction

Run a snapshot test with objects as result using `describe`/`it` pattern. Use it once with vitest and then with Jest or vice versa.

- Inline snapshots indentation is different
 
<img width="283" alt="20220108-075225-capture-holtwick@2x" src="https://user-images.githubusercontent.com/49557/148634902-bc1cca92-c62a-4f53-a975-5bbcdcf558fc.png">
 
(It also used to have different key names for external snapshots, but I cannot reproduce any more)

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 86.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /opt/homebrew/bin/node    
  Browsers:
    Edge: 96.0.1054.43
    Firefox: 95.0.2
    Safari: 15.2
    Safari Technology Preview: 15.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-01-08 07:05
Please give a code reproduction.

**Comment by holtwick** [comment] 2022-01-08 07:10
```js
describe("test", () => {
  it("should inline", () => {
    const sample = { data: [1, 2, 3, 4, 5, 6] }
    expect(sample).toMatchInlineSnapshot(`
      Object {
        "data": Array [
          1,
          2,
          3,
          4,
          5,
          6,
        ],
      }
    `)
  })
})
```

<img width="507" alt="20220108-080954-capture-holtwick@2x" src="https://user-images.githubusercontent.com/49557/148635373-3f1b7d19-b046-4961-8ca2-32cc682c2496.png">

**Comment by sheremet-va** [comment] 2022-01-08 07:12
@holtwick the code inside is what `Jest` generated?

I think we discussed some format differences when implementing it and ended up like we ended up. Maybe we can add `shapshotOptions` to be compatible with Jest.

**Comment by sheremet-va** [comment] 2022-01-08 07:15
^ I may be wrong on this. I'll investigate.

**Comment by holtwick** [comment] 2022-01-08 07:15
Yes, generated by Jest.

My use case is, that I use Jest to run single tests inside Visual Code but would like to run the whole suite using vitest. It is just that minor difference, otherwise it works fine. If the defaults could match those of Jest, this would be a win. 

Thanks for looking into it!

**Comment by sheremet-va** [comment] 2022-01-08 07:16
Why whouldn't you run a single test using Vitest tho?

**Comment by holtwick** [comment] 2022-01-08 07:32
Of course I could. But don't you think it would have a positive effect on Jest users migrating to vitest if everything would work out of the box for them? Some have large test suites and want to touch as least lines as possible when migrating. I personally liked that migration was so easy from Jest and wouldn't have invested more than 15 minutes for migration with  an uncertain outcome ;)

**Comment by sheremet-va** [comment] 2022-01-08 07:35
Yes, I think It would have a positive effect. I am just interested in the usecase you provided :)

You can run a single test with `-t <patter>` option. Also I beleave disabling isolation (`--no-isolation`) and threads 
 (`--no-threads`) when running only one test, boosts performance to the skies 👀

**Comment by holtwick** [comment] 2022-01-08 07:48
I see. So I'm using https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner

You're right, changing it is super easy. In VSCode's `settings.json` I now use this:

```json
 "jestrunner.jestCommand": "pnpx vitest --global"
```

Performance is fine even with all lights on, that's what I love at vitest so much :) 

Thanks for the hints @sheremet-va

**Comment by sheremet-va** [comment] 2022-01-08 09:03
Indentation should be fixed in the next release.
By default we don't show types like jest does (Object, Array). To enable it, add this config:

```ts
// vitest.config.ts
{
   test: {
     snapshotOptions: {
        snapshotFormat: {
           printBasicPrototype: true
        }
     }
   }
}
```

**Comment by sheremet-va** [comment] 2022-01-11 07:19
Fixed in 0.0.140

**Comment by holtwick** [comment] 2022-01-11 08:04
Well, I don't get the config part with `printBasicPrototype` running. See my demo here: https://stackblitz.com/edit/node-st72sq?file=test/suite.test.js

It also fails due to another bug related to `--global` option causing `-u` to fail. Tru by running `npm run vitestu`:

<img width="899" alt="20220111-090328-capture-holtwick@2x" src="https://user-images.githubusercontent.com/49557/148903822-58f327ba-b1ac-453c-b0f1-7d402fb9051c.png">

**Comment by sheremet-va** [comment] 2022-01-11 08:57
Turns out it wasnt a public type :)

Made it public as:

```ts
// vitest.config.ts
{
   test: {
      snapshotFormat: {
         printBasicPrototype: true
      }
   }
}
```

Cannot reproduce error with `-u` on main. Can you confirm it is fixed? https://vitest.dev/guide/#using-unreleased-commits

**Comment by holtwick** [comment] 2022-01-11 09:37
Sorry, I currently do not have the time to test, but I'm confident you fixed it ;) Thanks.

**Comment by antfu** [comment] 2022-01-11 17:24
This is an intentional default as we think it provides better readability and is more concise (jest guys also thinking about flipping this default in the future)

If you want the jest format, you can configure it back as @sheremet-va already mentioned. 
Refer https://jestjs.io/docs/configuration#snapshotformat-object

**Closed by antfu** 2022-01-11 17:24 UTC
Labels: enhancement

**Comment by scalvert** [comment] 2022-01-13 00:15
Thanks for fixing this. I was encountering the same formatting issue - now this is just a drop in replacement :)
