### ISSUE TITLE
Test coverage html output has wrong links

### ISSUE THREAD

**Issue by Hurtak** [vitest-dev/vitest#2355] opened 2022-11-20 17:53 UTC
### Describe the bug

When running the HTML coverage output files in nested directories return 404. Eg when there is `/folder/component.ts` and I am in `/folder` and click on the `component.ts` the link leads to `/component.ts` instead of `/folder/component.ts`

https://user-images.githubusercontent.com/6587821/202914634-0211f897-0983-4211-bd73-0c22e7c369d4.mov

### Reproduction

https://github.com/Hurtak/vitest-coverage-bug

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 188.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.1
    Safari: 16.1
    Safari Technology Preview: 16.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2022-11-21 04:40
@Hurtak could you try if `live-server` works for you? So instead of `serve coverage`, use `npx live-server coverage`. 

This has been a known issue in `serve` and I don't think there are plans to fix it.

**Comment by Hurtak** [comment] 2022-11-21 09:08
@AriPerkkio yea it works with that one.

The difference seems to be that the html output is using relative paths and `serve` makes from url `/folder/index.html` -> `/folder` which then when we add the relative path leads to `/something` instead of `/folder/something`.

Is there some way to force the HTML coverage output to use absolute paths everywhere?

**Comment by AriPerkkio** [comment] 2022-11-21 10:01
I'm not sure if Vitest itself should do any magic here. According to similar reports, Jest is having the same issue.

I think the `istanbul-reports` does allow some configurations for html reporter, but still this sounds like something `serve` should handle better. 

See reported issues from `serve` package:
- https://github.com/vercel/serve/issues/513
- https://github.com/vercel/serve-handler/issues/79

**Comment by Hurtak** [comment] 2022-11-21 11:54
Yea definitely no magic on Vitest side :). I think Vitest is passing some default params to the c8, so maybe someone can investigate if there is some param that could fix this, otherwise lets close this and hope this will get fixed upstream.

**Comment by Hurtak** [comment] 2022-11-21 11:57
@AriPerkkio Maybe we could do some mention in the docs to warn against using `serve` with the coverage html output? I can prepare PR for that, if you don't think this is too niche edge case to mention it in the docs.

**Comment by AriPerkkio** [comment] 2022-11-22 07:36
Just to mention here: there is some on-going progress on #2364 that will provide an out-of-the-box setup for viewing Vitest's coverage reports. The UI should not have the same URL resolving issues as `serve` has.

**Comment by sheremet-va** [comment] 2023-10-04 10:05
Looks like the problem is not with Vitest itself. Vitest can also now provide coverage inside its UI, so I think the issue can be considered resolved.

**Closed by sheremet-va** 2023-10-04 10:05 UTC
Labels: upstream
