### ISSUE TITLE
V8 coverage fails, looks like it loosing actual node

### ISSUE THREAD

**Issue by ejexxeffer** [vitest-dev/vitest#5558] opened 2024-04-17 09:24 UTC
### Describe the bug

```bash
> datepickertest@0.0.0 coverage
> vitest run --coverage


 RUN  v1.5.0 /home/ejexxeffer/datepickertest
      Coverage enabled with v8

stdout | src/components/__tests__/Datepicker.spec.ts > Datepicker > renders properly
day 4

 ✓ src/components/__tests__/Datepicker.spec.ts (1)
   ✓ Datepicker (1)
     ✓ renders properly

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  14:08:49
   Duration  1.95s (transform 195ms, setup 0ms, collect 361ms, tests 43ms, environment 344ms, prepare 302ms)

 % @vitest/coverage-v8 does not work on Stackblitz. Report will be empty.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: requires Node.js >=10.12.0
 ❯ eval node_modules/@vitest/coverage-v8/dist/provider.js:1818:21
 ❯ _0x2a5654.run ../../../blitz.7dbe22a9.js:352:372415
 ❯ _0x30f943._evaluate ../../../blitz.7dbe22a9.js:352:378046
 ❯ ModuleJob.run node:internal/modules/esm/module_job:181:2372
```

### Reproduction

https://stackblitz.com/~/github.com/ejexxeffer/datepickertest

### System Info

```shell
I'm found a problem. Inside my components, I have empty .vue SFC files. When i remove it or describe it as needed, the coverage is working.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2024-04-17 11:03
Duplicate of https://github.com/vitest-dev/vitest/issues/5532

**Closed by AriPerkkio** 2024-04-17 11:03 UTC
Labels: pending triage
