### ISSUE TITLE
Performance regression between 0.33.0 and 0.34.X

### ISSUE THREAD

**Issue by SergioMorchon** [vitest-dev/vitest#3967] opened 2023-08-16 13:02 UTC
### Describe the bug

The same test suite:
* With version `0.33.0`: `yarn test  202.70s user 31.13s system 634% cpu 36.857 total`
* With version `0.34.0`: `yarn test  293.07s user 42.05s system 311% cpu 1:47.58 total`
* With version `0.34.1`: `yarn test  291.66s user 43.37s system 306% cpu 1:49.16 total`

Keywords: performance, time

### Reproduction

I can't publish all the test we have in the private project, but this is the configuration we use:

```typescript
/// <reference types="vitest" />

import path from 'path';
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';

import tsconfigPaths from 'vite-tsconfig-paths';
import pkg from './package.json';

export default defineConfig({
    plugins: [
        react(),
        vanillaExtractPlugin(),
        tsconfigPaths(),
        dts({
            entryRoot: './src',
            exclude: [
                'node_modules',
                'dist',
                '**/*.stories.*',
                '**/*.test.*',
                '**/*.test-acceptance.*',
            ],
        }),
        {
            name: 'remove-ensure-watch-plugin',
            enforce: 'post',
            configResolved: config => {
                // https://github.com/vitejs/vite/issues/13342
                (config as any).plugins = config.plugins.filter(
                    p => p?.name !== 'vite:ensure-watch'
                );
            },
        },
    ],
    build: {
        emptyOutDir: false,
        lib: {
            entry: 'src/index.ts',
            formats: ['es'],
            fileName: 'index',
        },
        sourcemap: true,
        rollupOptions: {
            external: [/@private/, 'classnames', 'react', 'react-dom'],
            output: {
                manualChunks: Object.fromEntries(
                    Object.keys(pkg.dependencies)
                        .filter(
                            dependency => !dependency.startsWith('@private')
                        )
                        .map(dependency => [dependency, [dependency]])
                ),
            },
        },
    },
    test: {
        globals: true,
        environment: 'jsdom',
        include: ['src/**/*.test.{ts,tsx}'],
        setupFiles: './src/setupTests.tsx',
        alias: [
            {
                find: '@private-app/api',
                replacement: path.resolve(__dirname, '../api/src'),
            },
            {
                find: /@private-app\/core\/(.+)/,
                replacement: path.resolve(__dirname, '../core/src/$1'),
            },
        ],
    },
});
```

With the exact same sourcecode, just upgrading the vitest dependency from 0.33.0 to 0.34.1, the test time grows significantly
This is one of the runs inside the CI Linux agent:
<img width="1151" alt="image" src="https://github.com/vitest-dev/vitest/assets/4521712/bba87bed-e5dc-4d07-87b4-c9d77c2c902c">

### System Info

```shell
Reproduced in:
* MacBook Pro with macOS 13.1.
* Linux virtual machine inside TeamCity CI agent.
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-08-16 13:14
If you add `test.testTransformMode.ssr: ['**/*']` does it return to the previous speed?

**Comment by sheremet-va** [comment] 2023-08-16 13:22
Can you send your resolved config that is printed with `DEBUG=vite:config vitest`?

**Comment by SergioMorchon** [comment] 2023-08-16 13:26
> DEBUG=vite:config vitest

```
  vite:config bundled config file loaded in 474.18ms +0ms
  vite:config using resolved config: {
  vite:config   plugins: [
  vite:config     'vite:optimized-deps',
  vite:config     'vite:watch-package-data',
  vite:config     'vite:pre-alias',
  vite:config     'alias',
  vite:config     'vite:react-babel',
  vite:config     'vite:react-refresh',
  vite:config     'vanilla-extract',
  vite:config     'vite-tsconfig-paths',
  vite:config     'vitest',
  vite:config     'vitest:env-replacer',
  vite:config     'vitest:global-setup-plugin',
  vite:config     'vitest:css-disable',
  vite:config     'vitest:resolve-root',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vitest:coverage-transform',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'remove-ensure-watch-plugin',
  vite:config     'vitest:css-empty-post',
  vite:config     'vite:mocks',
  vite:config     'vite:client-inject',
  vite:config     'vite:import-analysis'
  vite:config   ],
  vite:config   build: {
  vite:config     target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: false,
  vite:config     sourcemap: true,
  vite:config     rollupOptions: { external: [Array], output: [Object], onwarn: [Function: onwarn] },
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: false,
  vite:config     copyPublicDir: true,
  vite:config     manifest: false,
  vite:config     lib: { entry: 'src/index.ts', formats: [Array], fileName: 'index' },
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     ssrEmitAssets: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] },
  vite:config     modulePreload: { polyfill: true },
  vite:config     cssMinify: true
  vite:config   },
  vite:config   test: {
  vite:config     globals: true,
  vite:config     environment: 'jsdom',
  vite:config     include: [ 'src/**/*.test.{ts,tsx}' ],
  vite:config     setupFiles: './src/setupTests.tsx',
  vite:config     testTransformMode: { ssr: [Array] }
  vite:config   },
  vite:config   logLevel: 'error',
  vite:config   configFile: '/Users/<user>/dev/private-app/packages/ui/vite.config.ts',
  vite:config   mode: 'test',
  vite:config   esbuild: {
  vite:config     jsxDev: true,
  vite:config     jsx: 'automatic',
  vite:config     jsxImportSource: undefined,
  vite:config     sourcemap: 'external',
  vite:config     legalComments: 'inline'
  vite:config   },
  vite:config   optimizeDeps: {
  vite:config     disabled: false,
  vite:config     include: [
  vite:config       'react',
  vite:config       'react/jsx-dev-runtime',
  vite:config       '@vanilla-extract/css/injectStyles',
  vite:config       'react',
  vite:config       'react/jsx-dev-runtime',
  vite:config       '@vanilla-extract/css/injectStyles'
  vite:config     ],
  vite:config     enabled: true,
  vite:config     noDiscovery: true,
  vite:config     entries: [],
  vite:config     exclude: [
  vite:config       'vitest',           '_http_agent',         '_http_client',
  vite:config       '_http_common',     '_http_incoming',      '_http_outgoing',
  vite:config       '_http_server',     '_stream_duplex',      '_stream_passthrough',
  vite:config       '_stream_readable', '_stream_transform',   '_stream_wrap',
  vite:config       '_stream_writable', '_tls_common',         '_tls_wrap',
  vite:config       'assert',           'assert/strict',       'async_hooks',
  vite:config       'buffer',           'child_process',       'cluster',
  vite:config       'console',          'constants',           'crypto',
  vite:config       'dgram',            'diagnostics_channel', 'dns',
  vite:config       'dns/promises',     'domain',              'events',
  vite:config       'fs',               'fs/promises',         'http',
  vite:config       'http2',            'https',               'inspector',
  vite:config       'module',           'net',                 'os',
  vite:config       'path',             'path/posix',          'path/win32',
  vite:config       'perf_hooks',       'process',             'punycode',
  vite:config       'querystring',      'readline',            'readline/promises',
  vite:config       'repl',             'stream',              'stream/consumers',
  vite:config       'stream/promises',  'stream/web',          'string_decoder',
  vite:config       'sys',              'timers',              'timers/promises',
  vite:config       'tls',              'trace_events',        'tty',
  vite:config       'url',              'util',                'util/types',
  vite:config       'v8',               'vm',                  'worker_threads',
  vite:config       'zlib'
  vite:config     ],
  vite:config     esbuildOptions: { preserveSymlinks: false }
  vite:config   },
  vite:config   resolve: {
  vite:config     mainFields: [],
  vite:config     browserField: false,
  vite:config     conditions: [ 'node' ],
  vite:config     extensions: [
  vite:config       '.mjs',  '.js',
  vite:config       '.mts',  '.ts',
  vite:config       '.jsx',  '.tsx',
  vite:config       '.json'
  vite:config     ],
  vite:config     dedupe: [ 'react', 'react-dom' ],
  vite:config     preserveSymlinks: false,
  vite:config     alias: [ [Object], [Object], [Object], [Object] ]
  vite:config   },
  vite:config   ssr: {
  vite:config     format: 'esm',
  vite:config     target: 'node',
  vite:config     external: [
  vite:config       '@vanilla-extract/css',
  vite:config       '@vanilla-extract/css/fileScope',
  vite:config       '@vanilla-extract/css/adapter'
  vite:config     ],
  vite:config     optimizeDeps: {
  vite:config       disabled: false,
  vite:config       enabled: true,
  vite:config       noDiscovery: true,
  vite:config       entries: [],
  vite:config       exclude: [Array],
  vite:config       include: [],
  vite:config       esbuildOptions: [Object]
  vite:config     }
  vite:config   },
  vite:config   server: {
  vite:config     preTransformRequests: false,
  vite:config     watch: { persistent: false, depth: 0, ignored: [Array] },
  vite:config     open: undefined,
  vite:config     hmr: false,
  vite:config     sourcemapIgnoreList: [Function: isInNodeModules],
  vite:config     middlewareMode: false,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] }
  vite:config   },
  vite:config   css: { modules: { generateScopedName: [Function (anonymous)] } },
  vite:config   cacheDir: '/Users/<user>/dev/private-app/packages/ui/node_modules/.vitest',
  vite:config   configFileDependencies: [
  vite:config     '/Users/<user>/dev/private-app/packages/ui/package.json',
  vite:config     '/Users/<user>/dev/private-app/packages/ui/vite.config.ts'
  vite:config   ],
  vite:config   inlineConfig: {
  vite:config     logLevel: 'error',
  vite:config     configFile: '/Users/<user>/dev/private-app/packages/ui/vite.config.ts',
  vite:config     mode: 'test',
  vite:config     plugins: [
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object], [Object]
  vite:config     ]
  vite:config   },
  vite:config   root: '/Users/<user>/dev/private-app/packages/ui',
  vite:config   base: '/',
  vite:config   rawBase: '/',
  vite:config   publicDir: '/Users/<user>/dev/private-app/packages/ui/public',
  vite:config   command: 'serve',
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   isProduction: false,
  vite:config   preview: {
  vite:config     port: undefined,
  vite:config     strictPort: undefined,
  vite:config     host: undefined,
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   envDir: '/Users/<user>/dev/private-app/packages/ui',
  vite:config   env: { BASE_URL: '/', MODE: 'test', DEV: true, PROD: false },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(1) {
  vite:config     'fnpd_/Users/<user>/dev/private-app/packages/ui' => {
  vite:config       dir: '/Users/<user>/dev/private-app/packages/ui',
  vite:config       data: [Object],
  vite:config       hasSideEffects: [Function: hasSideEffects],
  vite:config       webResolvedImports: {},
  vite:config       nodeResolvedImports: {},
  vite:config       setResolvedCache: [Function: setResolvedCache],
  vite:config       getResolvedCache: [Function: getResolvedCache]
  vite:config     },
  vite:config     set: [Function (anonymous)]
  vite:config   },
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       'vite:optimized-deps',
  vite:config       'vite:watch-package-data',
  vite:config       'vite:pre-alias',
  vite:config       'alias',
  vite:config       'vite:modulepreload-polyfill',
  vite:config       'vite:resolve',
  vite:config       'vite:html-inline-proxy',
  vite:config       'vite:css',
  vite:config       'vite:esbuild',
  vite:config       'vite:json',
  vite:config       'vite:wasm-helper',
  vite:config       'vite:worker',
  vite:config       'vite:asset',
  vite:config       'vite:wasm-fallback',
  vite:config       'vite:define',
  vite:config       'vite:css-post',
  vite:config       'vite:worker-import-meta-url',
  vite:config       'vite:asset-import-meta-url',
  vite:config       'vite:dynamic-import-vars',
  vite:config       'vite:import-glob',
  vite:config       'vite:client-inject',
  vite:config       'vite:import-analysis'
  vite:config     ],
  vite:config     rollupOptions: {},
  vite:config     getSortedPlugins: [Function: getSortedPlugins],
  vite:config     getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config   },
  vite:config   appType: 'spa',
  vite:config   experimental: { importGlobRestoreExtension: false, hmrPartialAccept: false },
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config } +209ms
  ```

**Comment by dom-zhu** [comment] 2023-09-23 10:22
Any update here? still experiencing this

**Comment by matt-smarsh** [comment] 2023-09-29 18:36
With `vitest@0.33.0`:
![image](https://github.com/vitest-dev/vitest/assets/89040187/19262823-b314-4632-8796-56d2e7b0e8d4)

With `vitest@0.34.5`:
![image](https://github.com/vitest-dev/vitest/assets/89040187/cb50bdef-dfd4-47c1-96ed-dd46c5866d63)

With v0.34.5 and `test.testTransformMode.ssr` set:
![image](https://github.com/vitest-dev/vitest/assets/89040187/6d1823d9-bec9-4fe1-af34-3a1d15b7e7f7)

**Comment by sheremet-va** [comment] 2023-10-03 07:28
If someone can point to an open-source project that experiences this regression, I would greatly appreciate it 🙏🏻

**Comment by sheremet-va** [comment] 2023-10-03 15:33
I found that using `react` plugin slows down transformation _significantly_. I was able to fix it by updating it to the latest version (where it accounts for `server.hmr` setting). It's also recommended to not use `jsxRuntime: "classic"` for jsx files.

I wasn't able to return to previous test numbers yet, but it helped somewhat.

**Comment by dom-zhu** [comment] 2023-10-05 00:26
Incase it can be of any help:
0.32.4
![image](https://github.com/vitest-dev/vitest/assets/44078427/0f5cf82e-41ff-47d5-a5e8-dd1952fc288d)
0.34.6 (no SSR - default)
![image](https://github.com/vitest-dev/vitest/assets/44078427/2f7fc454-6428-46cd-b370-093925b53939)
0.34.6 (SSR)
![image](https://github.com/vitest-dev/vitest/assets/44078427/7b057831-72cd-4556-89cf-b1a2b512dc1a)

**Comment by sheremet-va** [comment] 2023-10-05 06:04
> Incase it can be of any help:
> 
> 0.32.4
> 
> ![image](https://github.com/vitest-dev/vitest/assets/44078427/0f5cf82e-41ff-47d5-a5e8-dd1952fc288d)
> 
> 0.34.6 (no SSR - default)
> 
> ![image](https://github.com/vitest-dev/vitest/assets/44078427/2f7fc454-6428-46cd-b370-093925b53939)
> 
> 0.34.6 (SSR)
> 
> ![image](https://github.com/vitest-dev/vitest/assets/44078427/7b057831-72cd-4556-89cf-b1a2b512dc1a)
> 
> 
> 
> 

Not helpful since I don't see the code and config.

**Comment by kaiyoma** [comment] 2023-12-15 02:59
I had filed a bug about this problem as well (#4059) and wanted to report that the `ssr` setting is working for me too. Is this the official guidance from Vitest moving forward?

Here are the numbers from our repo (350 test files, ~8,900 tests):

```
0.33.0: ~675 seconds
0.34.6: 2009 seconds (3x slower)
 + ssr: ~660 seconds (back to normal)
```

I can't share any of our code, but here's our resolved config:

<details>
  <summary>Resolved config</summary>

  ```
  vite:config bundled config file loaded in 1073.93ms +0ms
  vite:config using resolved config: {
  vite:config   base: '/',
  vite:config   build: {
  vite:config     target: [ 'chrome115', 'edge115', 'firefox115' ],
  vite:config     cssTarget: [ 'chrome115', 'edge115', 'firefox115' ],
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: true,
  vite:config     sourcemap: true,
  vite:config     rollupOptions: { onwarn: [Function: onwarn], output: [Object] },
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     copyPublicDir: true,
  vite:config     manifest: false,
  vite:config     lib: false,
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     ssrEmitAssets: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 14000,
  vite:config     watch: null,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] },
  vite:config     modulePreload: { polyfill: true },
  vite:config     cssMinify: true
  vite:config   },
  vite:config   css: {
  vite:config     preprocessorOptions: { less: [Object] },
  vite:config     modules: { generateScopedName: [Function (anonymous)] }
  vite:config   },
  vite:config   define: {},
  vite:config   optimizeDeps: {
  vite:config     disabled: false,
  vite:config     entries: [],
  vite:config     include: [ 'react/jsx-runtime' ],
  vite:config     enabled: true,
  vite:config     noDiscovery: true,
  vite:config     exclude: [ 'vitest', 'react', 'react/jsx-dev-runtime' ],
  vite:config     esbuildOptions: { preserveSymlinks: false }
  vite:config   },
  vite:config   plugins: [
  vite:config     'vite:optimized-deps',
  vite:config     'vite:watch-package-data',
  vite:config     'vite:pre-alias',
  vite:config     'alias',
  vite:config     'vite:react-babel',
  vite:config     'vite:react-refresh',
  vite:config     'vitest',
  vite:config     'vitest:ssr-replacer',
  vite:config     'vitest:global-setup-plugin',
  vite:config     'vitest:css-disable',
  vite:config     'vitest:resolve-root',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vitest:coverage-transform',
  vite:config     'vitest:normalize-optimizer',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vitest:css-empty-post',
  vite:config     'vitest:mocks',
  vite:config     'vite:client-inject',
  vite:config     'vite:import-analysis'
  vite:config   ],
  vite:config   resolve: {
  vite:config     mainFields: [],
  vite:config     browserField: false,
  vite:config     conditions: [ 'node' ],
  vite:config     extensions: [
  vite:config       '.mjs',  '.js',
  vite:config       '.mts',  '.ts',
  vite:config       '.jsx',  '.tsx',
  vite:config       '.json'
  vite:config     ],
  vite:config     dedupe: [ 'react', 'react-dom' ],
  vite:config     preserveSymlinks: false,
  vite:config     alias: [
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object]
  vite:config     ]
  vite:config   },
  vite:config   root: 'C:/Users/kgetz/Work/event-viewer/src',
  vite:config   server: {
  vite:config     preTransformRequests: false,
  vite:config     port: 3001,
  vite:config     middlewareMode: true,
  vite:config     watch: { ignored: [Array] },
  vite:config     open: false,
  vite:config     hmr: false,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] },
  vite:config     sourcemapIgnoreList: [Function: isInNodeModules]
  vite:config   },
  vite:config   test: {
  vite:config     maxThreads: 4,
  vite:config     minThreads: 1,
  vite:config     testTimeout: 30000,
  vite:config     testTransformMode: { ssr: [Array] },
  vite:config     environment: 'jsdom',
  vite:config     setupFiles: 'vitest.setup.ts'
  vite:config   },
  vite:config   logLevel: 'error',
  vite:config   configFile: 'C:/Users/kgetz/Work/event-viewer/vite.config.ts',
  vite:config   mode: 'test',
  vite:config   esbuild: {
  vite:config     jsxDev: true,
  vite:config     jsx: 'automatic',
  vite:config     jsxImportSource: undefined,
  vite:config     sourcemap: 'external',
  vite:config     legalComments: 'inline'
  vite:config   },
  vite:config   cacheDir: 'C:/Users/kgetz/Work/event-viewer/node_modules/.vitest',
  vite:config   ssr: {
  vite:config     format: 'esm',
  vite:config     target: 'node',
  vite:config     optimizeDeps: {
  vite:config       disabled: false,
  vite:config       enabled: true,
  vite:config       noDiscovery: true,
  vite:config       entries: [],
  vite:config       exclude: [Array],
  vite:config       include: [],
  vite:config       esbuildOptions: [Object]
  vite:config     }
  vite:config   },
  vite:config   configFileDependencies: [ 'C:/Users/kgetz/Work/event-viewer/vite.config.ts' ],
  vite:config   inlineConfig: {
  vite:config     logLevel: 'error',
  vite:config     configFile: 'C:\\Users\\kgetz\\Work\\event-viewer\\vite.config.ts',
  vite:config     mode: 'test',
  vite:config     plugins: [
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object], [Object],
  vite:config       [Object]
  vite:config     ]
  vite:config   },
  vite:config   rawBase: '/',
  vite:config   publicDir: 'C:\\Users\\kgetz\\Work\\event-viewer\\src\\public',
  vite:config   command: 'serve',
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   isProduction: false,
  vite:config   preview: {
  vite:config     port: undefined,
  vite:config     strictPort: undefined,
  vite:config     host: undefined,
  vite:config     https: undefined,
  vite:config     open: false,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   envDir: 'C:/Users/kgetz/Work/event-viewer/src',
  vite:config   env: { BASE_URL: '/', MODE: 'test', DEV: true, PROD: false },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(2) {
  vite:config     'fnpd_C:/Users/kgetz/Work/event-viewer' => {
  vite:config       dir: 'C:\\Users\\kgetz\\Work\\event-viewer',
  vite:config       data: [Object],
  vite:config       hasSideEffects: [Function: hasSideEffects],
  vite:config       webResolvedImports: {},
  vite:config       nodeResolvedImports: {},
  vite:config       setResolvedCache: [Function: setResolvedCache],
  vite:config       getResolvedCache: [Function: getResolvedCache]
  vite:config     },
  vite:config     'fnpd_C:/Users/kgetz/Work/event-viewer/src' => {
  vite:config       dir: 'C:\\Users\\kgetz\\Work\\event-viewer',
  vite:config       data: [Object],
  vite:config       hasSideEffects: [Function: hasSideEffects],
  vite:config       webResolvedImports: {},
  vite:config       nodeResolvedImports: {},
  vite:config       setResolvedCache: [Function: setResolvedCache],
  vite:config       getResolvedCache: [Function: getResolvedCache]
  vite:config     },
  vite:config     set: [Function (anonymous)]
  vite:config   },
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       'vite:optimized-deps',
  vite:config       'vite:watch-package-data',
  vite:config       'vite:pre-alias',
  vite:config       'alias',
  vite:config       'vite:modulepreload-polyfill',
  vite:config       'vite:resolve',
  vite:config       'vite:html-inline-proxy',
  vite:config       'vite:css',
  vite:config       'vite:esbuild',
  vite:config       'vite:json',
  vite:config       'vite:wasm-helper',
  vite:config       'vite:worker',
  vite:config       'vite:asset',
  vite:config       'vite:wasm-fallback',
  vite:config       'vite:define',
  vite:config       'vite:css-post',
  vite:config       'vite:worker-import-meta-url',
  vite:config       'vite:asset-import-meta-url',
  vite:config       'vite:dynamic-import-vars',
  vite:config       'vite:import-glob',
  vite:config       'vite:client-inject',
  vite:config       'vite:import-analysis'
  vite:config     ],
  vite:config     rollupOptions: {},
  vite:config     getSortedPlugins: [Function: getSortedPlugins],
  vite:config     getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config   },
  vite:config   appType: 'spa',
  vite:config   experimental: { importGlobRestoreExtension: false, hmrPartialAccept: false },
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config } +25ms
  ```
</details>

**Comment by sheremet-va** [comment] 2023-12-15 10:06
```
vite:config     'vite:react-babel',
vite:config     'vite:react-refresh',
```

It's known that these two can cause severe performance regression because it can fallback to using babel. Try disabling them since Vitest supports JSX out of the box with esbuild.

**Comment by owanturist** [comment] 2023-12-15 11:09
Hey @sheremet-va 

Thanks for the advice to disable the `testTransformMode` ssr transform - it busts the test speed!

But I am struggling to understand how exactly one would disable `vite:react-babel` and `vite:react-refresh`? I can only disable them if I call `react({ babelrc: false })` but then my entire build does not work. Let me know if you need any additional details 🙏

**Comment by sheremet-va** [comment] 2023-12-15 11:25
> Hey @sheremet-va
> 
> Thanks for the advice to disable the `testTransformMode` ssr transform - it busts the test speed!
> 
> But I am struggling to understand how exactly one would disable `vite:react-babel` and `vite:react-refresh`? I can only disable them if I call `react({ babelrc: false })` but then my entire build does not work. Let me know if you need any additional details 🙏

Vitest passes down `mode` as `test`, and also sets `VITEST` env variable, so you can conditionally remove it:

```ts
export default defineConfig(({ mode }) => {
  return {
    plugins: mode === 'test' ? [] : [react()]
  }
})
```

**Comment by kaiyoma** [comment] 2023-12-15 18:45
@sheremet-va This fix does not work for us. If I add the conditional logic above (for the React plugin) and disable the `ssr` setting, then my unit test performance regresses, and they take 3x as long, as I reported before. It would seem that the `ssr` setting is required for getting normal performance now.

**Comment by sheremet-va** [comment] 2024-01-04 16:41
This should be fixed in Vitest 1.1.2.

**Closed** 2024-01-04 16:40 UTC
Labels: bug, performance, mode: web, p4-important :exclamation:

**Comment by yannick-aivayan** [comment] 2024-01-12 16:18
@sheremet-va It works amazingly well!
Thanks and congrats!

**Comment by SergioMorchon** [comment] 2024-01-12 17:02
I've upgraded vitest to the latest version and I can also confirm that ghe fix works, thank you so much for the effort!
