### ISSUE TITLE
Typescript classes don't behave like in node

### ISSUE THREAD

**Issue by lukasholzer** [vitest-dev/vitest#1167] opened 2022-04-19 10:13 UTC
### Describe the bug

Following code works when executed with ts-node but not with vitest:

It seems like a problem while running javascript

```typescript
export class Base {
  static create<I extends typeof Base>(this: I): InstanceType<I> {
    const configInstance: any = new this();

    return configInstance as InstanceType<I>;
  }

  get _keys(): string[] {
    return Object.keys(this).filter((key) => !key.startsWith('_'));
  }
}

export class TestInstance extends Base {
  someProp?: boolean;
}

export const config = TestInstance.create();

// run with: node --no-warnings --loader ts-node/esm ./test.ts
// should print ['someProp']
console.log(config._keys);
```

### Reproduction

See reproducible example:
https://stackblitz.com/edit/node-wxnagn?file=issue.test.ts

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.45 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.2
  npmPackages:
    vite: ^2.8.0 => 2.8.6
    vitest: ~0.9.3 => 0.9.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by crjm** [comment] 2022-04-19 15:01
It looks like node-ts and Vitest treat uninitialized properties differently. When creating a new instance, ts-node assigns the property as undefined, whereas Vite doesn't even assign it to the class instance.

For these tests to pass we must assign a value to the property either trough a constructor or a simple value assignment after the class is instantiated.

https://stackblitz.com/edit/node-duzur9?file=test.ts

At first I thought it had something to do with optional properties, but after changing the _strictPropertyInitialization_ config option to _false_ and making the property non-optional, the result was the same:

https://stackblitz.com/edit/node-fntq1b?file=issue.test.ts

**Comment by sheremet-va** [comment] 2022-04-19 15:13
Vitest doesn't perform any transformations on its own. We use Vite transform pipeline for that. If this is an issue with how Vite handles it, maybe it's better to open an issue there.

If it is not reproducible with Vite alone, we can try digging deeper. For example, does this code work correctly?
```ts
import { createServer } from 'vite'
const server = await createServer({})
server.ssrLoadModule('./test.ts')
```

**Comment by sheremet-va** [comment] 2022-04-19 15:44
> @sheremet-va it's not connected to typescript at all. When removing the syntax sugar of javascript and pasting the code inside the browser console it works as well

Yes, that is what I said in my last sentence. Please, reread it. 

I gave example with Vite server processing the file, and it logged an empty array. Please, open an issue at Vite repo, Vitest has nothing to do with how the code is transformed.

**Comment by lukasholzer** [comment] 2022-04-19 15:46
@sheremet-va oh sorry 🙈 Will do :)

**Comment by crjm** [comment] 2022-04-19 16:31
Yes, it's weird indeed. After fiddling a bit, I can see that optional uninitialized properties are omitted, whereas initialized properties are placed inside the constructor.
On the other hand, typeless code considers uninitialized properties as instance properties.

```
export class Base {
  constructor() {
    this.baseProp = void 0;
    this.baseProp2 = true;
  }
  static create() {
    const configInstance = new this();
    return configInstance;
  }
  get _keys() {
    return Object.keys(this).filter((key) => !key.startsWith("_"));
  }
}
export class TestInstance extends Base {
  constructor() {
    super(...arguments);
    this.someProp2 = true;
    this.someProp3 = true;
  }
}
export const config = TestInstance.create();
console.log(config._keys);
```
Source:
https://stackblitz.com/edit/node-1zzdce?file=test.ts

BTW really cool to use transformRequest for debugging.

**Comment by antfu** [comment] 2022-04-19 17:04
Looks like it's an esbuild bug

[playground](https://esbuild.egoist.sh/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImV4cG9ydCBjbGFzcyBCYXNlIHtcbiAgc3RhdGljIGNyZWF0ZTxJIGV4dGVuZHMgdHlwZW9mIEJhc2U+KHRoaXM6IEkpOiBJbnN0YW5jZVR5cGU8ST4ge1xuICAgIGNvbnN0IGNvbmZpZ0luc3RhbmNlOiBhbnkgPSBuZXcgdGhpcygpO1xuXG4gICAgcmV0dXJuIGNvbmZpZ0luc3RhbmNlIGFzIEluc3RhbmNlVHlwZTxJPjtcbiAgfVxuXG4gIGdldCBfa2V5cygpOiBzdHJpbmdbXSB7XG4gICAgcmV0dXJuIE9iamVjdC5rZXlzKHRoaXMpLmZpbHRlcigoa2V5KSA9PiAha2V5LnN0YXJ0c1dpdGgoJ18nKSk7XG4gIH1cbn1cblxuZXhwb3J0IGNsYXNzIFRlc3RJbnN0YW5jZSBleHRlbmRzIEJhc2Uge1xuICBzb21lUHJvcD86IGJvb2xlYW47XG59XG5cbmV4cG9ydCBjb25zdCBjb25maWcgPSBUZXN0SW5zdGFuY2UuY3JlYXRlKCk7XG5cbi8vIHJ1biB3aXRoOiBub2RlIC0tbm8td2FybmluZ3MgLS1sb2FkZXIgdHMtbm9kZS9lc20gLi90ZXN0LnRzXG4vLyBzaG91bGQgcHJpbnQgWydzb21lUHJvcCddXG5jb25zb2xlLmxvZyhjb25maWcuX2tleXMpOyJ9XSxbImVzYnVpbGQuY29uZmlnLmpzb24iLHsiY29udGVudCI6IntcbiAgXCJmb3JtYXRcIjogXCJjanNcIixcbiAgXCJjZG5VcmxcIjogXCJodHRwczovL2Nkbi5za3lwYWNrLmRldlwiXG59In1dLFsic3VtLnRzIix7ImNvbnRlbnQiOiJleHBvcnQgY29uc3Qgc3VtID0gKGE6IG51bWJlciwgYjogbnVtYmVyKSA9PiBhICsgYiJ9XV0=)

**Comment by sheremet-va** [comment] 2022-05-01 14:07
According to https://github.com/evanw/esbuild/issues/2195#issuecomment-1103925306 , it's by "design".  Use `useDefineForClassFields: true` in your config.

**Closed by sheremet-va** 2022-05-01 14:07 UTC
Labels: upstream
