### ISSUE TITLE
Vitest searches for non-existent file typescript.js.map and explodes

### ISSUE THREAD

**Issue by aabmets** [vitest-dev/vitest#6835] opened 2024-11-01 06:42 UTC
### Describe the bug

Running `vitest` in my project causes the following error to be thrown:
![image](https://github.com/user-attachments/assets/79124c6b-a371-46ef-8465-688a93caec0c)

Here's my [package.json](https://github.com/user-attachments/files/17596903/package.json) if you need to see dependencies.

BTW, this `vitest.config.ts` does not affect the error:
```typescript
import { defineConfig } from 'vitest/config';

export default defineConfig({
   test: {
      server: {
         sourcemap: false
      }
   },
})

```

### Reproduction

No idea how to reproduce, just install dependencies and run `vitest`

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1270P
    Memory: 18.47 GB / 31.67 GB
  Binaries:
    Node: 22.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
    bun: 1.1.31 - C:\Bin\bun.EXE
  Browsers:
    Edge: Chromium (130.0.2849.52)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vite: ^5.4.10 => 5.4.10 
    vitest: ^2.1.4 => 2.1.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment] 2024-11-01 06:45
This is a duplicate of https://github.com/vitest-dev/vitest/issues/6806 It's happening since last release v2.1.4. The fix is planned and see the linked issue for workaround https://github.com/vitest-dev/vitest/issues/6806#issuecomment-2443205856.

**Closed by hi-ogawa** 2024-11-01 06:45 UTC
Labels: pending triage
