### ISSUE TITLE
Error running vitest if my components app uses a component from an external lib that does not expose ESM

### ISSUE THREAD

**Issue by t1fmarin** [vitest-dev/vitest#4002] opened 2023-08-22 15:49 UTC
### Describe the bug

I have a React application with Vitest and I have the problem that when I use a component from an external lib that does not use ESM, the tests do not run but if I remove it they do.

I get this error: SyntaxError: Cannot use import statement outside a module

I have tried installing vite plugins that support commonjs but they don't work and I really don't know why.

Also test: // vitest.config.js
export default {
  test: {
    server: {
      deps: {
        inline: [
          "{{private dependency}}"
        ]
      }
    }
  }
}

and it doesn't work, what am I missing or is it really a vitest bug?

@antfu 

### Reproduction

I can't provide it's an internal project

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 279.61 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Edge: 116.0.1938.54
    Firefox: 115.0.3
    Safari: 16.6
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4 
    @vitest/coverage-istanbul: ^0.30.1 => 0.30.1 
    @vitest/ui: latest => 0.34.2 
    vite: ^4.4.9 => 4.4.9 
    vitest: ^0.34.1 => 0.34.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-08-22 23:40
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-08-22 23:40 UTC
Labels: pending triage
