### ISSUE TITLE
Error when importing a module created by wasm-pack

### ISSUE THREAD

**Issue by albrow** [vitest-dev/vitest#2910] opened 2023-02-23 23:34 UTC
### Describe the bug

I'm getting the following error when using Vitest and importing a module created by wasm-pack:

```
 FAIL  web/test.ts [ web/test.ts ]
 FAIL  web/main.ts [ web/main.ts ]
Error: Failed to resolve entry for package "/Users/alex/programming/rust/vitest-wasm-pack-error-repro/math-lib/pkg". The package may have incorrect main/module/exports specified in its package.json.
 ❯ packageEntryFailure node_modules/vite/dist/node/chunks/dep-5605cfa4.js:34107:11
 ❯ resolvePackageEntry node_modules/vite/dist/node/chunks/dep-5605cfa4.js:34104:5
 ❯ tryResolveFile node_modules/vite/dist/node/chunks/dep-5605cfa4.js:33717:38
 ❯ tryFsResolve node_modules/vite/dist/node/chunks/dep-5605cfa4.js:33699:16
 ❯ Context.resolveId node_modules/vite/dist/node/chunks/dep-5605cfa4.js:33544:28
 ❯ Object.resolveId node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40462:46
 ❯ TransformContext.resolve node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40227:23
 ❯ normalizeUrl node_modules/vite/dist/node/chunks/dep-5605cfa4.js:37137:34
 ❯ TransformContext.transform node_modules/vite/dist/node/chunks/dep-5605cfa4.js:37278:47
```

I have spent a few hours reading through documentation and trying various workarounds and configuration options but I haven't been able to resolve the issue.

I'm using the [vite-plugin-wasm-pack](https://github.com/nshen/vite-plugin-wasm-pack) plugin. Note that the application builds and runs fine; this appears to be only a problem with the tests. I would expect that if Vite is able to build the application then Vitest should also work, but maybe I'm missing something?

### Reproduction

I created this repository with what I believe is a minimal reproduction: https://github.com/albrow/vitest-wasm-pack-error-repro. Just follow the instructions in the README.

In case it is relevant, here is a link to the actual repository where I originally encountered this issue: https://github.com/albrow/elara/tree/vitest-error-example. I created a new branch called `vitest-error-example` which showcases the issue.

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 146.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.18.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 109.0.1
    Safari: 16.1
  npmPackages:
    @vitejs/plugin-react: ^2.1.0 => 2.2.0
    vite: ^3.1.7 => 3.2.5
    vitest: ^0.26.3 => 0.26.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment] 2024-01-23 05:23
Hi, thanks for providing a concise reproduction. This issue is quite old one and you might have already figured it out, but I think such usage of wasm-bindgen/wasm-pack is a reasonably common setup but with some pitfalls, so let me answer this.

First of all, I don't think this is a bug in Vitest. I have a few wasm-bindgen based projects on my own also with Vitest and I haven't hit this issue. For example, my usual vitest setup looks like this https://github.com/hi-ogawa/argon2-wasm-bindgen/blob/main/test/basic.test.ts#L11

I provided a concrete code with a few comments to explain the issue in your repository's PR.
I'll close this issue for now, but feel free to continue comment if you have further problem with wasm-bindgen + vitest setup.

**Closed** 2024-01-23 05:24 UTC
Labels: pending triage
