### ISSUE TITLE
unstable results

### ISSUE THREAD

**Issue by Sepush** [vitest-dev/vitest#1814] opened 2022-08-07 06:35 UTC
### Describe the bug

I try to migrate naive-ui test from jest to vitest
now I can run pnpm test for every single component and won't get error
but If i run `pnpm test`  for the whole project will get V8 error
```
#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 000000F96E0FE360
 1: 00007FF687FE7B7F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114079
 2: 00007FF687F025AF std::basic_ostream<char,std::char_traits<char> >::operator<<+65023
 3: 00007FF688BE2772 V8_Fatal+162
 4: 00007FF68864DAED v8::internal::BackingStore::Reallocate+637
 5: 00007FF688897269 v8::ArrayBuffer::GetBackingStore+137
 6: 00007FF687E33C6D std::vector<v8::internal::compiler::MoveOperands * ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * ptr64> >::empty+92797
 7: 00007FF687F9021E v8::internal::Malloced::operator delete+5118
 8: 00007FF688865C76 v8::internal::Builtins::code_handle+172790
 9: 00007FF688865869 v8::internal::Builtins::code_handle+171753
10: 00007FF688865B2C v8::internal::Builtins::code_handle+172460
11: 00007FF688865990 v8::internal::Builtins::code_handle+172048
12: 00007FF688939091 v8::internal::SetupIsolateDelegate::SetupHeap+494673
13: 000002836E23AE4B
```
if I run `pnpm test:update` for the whole project it won't get error
<img width="559" alt="vitest-naive" src="https://user-images.githubusercontent.com/39197136/183278408-adbe59a8-d74e-46d6-917a-94c69a08231d.png">

on my friend m1 pro max mbp run all test for the project it sometimes pass sometimes  V8 error
the results is so Inconsistent.
I think there are something wrong with tiny pool.
and on the ci It will report a error
```
Serialized Error: {
  "errors": [
    [AssertionError: expected "spy" to be called at least once],
  ],
}
```
https://github.com/TuSimple/naive-ui/runs/7710271807?check_suite_focus=true
It's too confusing so I try to looking for help.

### Reproduction

https://github.com/Sepush/naive-ui/tree/vi

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 833.58 MB / 7.89 GB
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\fnm_multishells\6948_1659584657685\node.EXE
    Yarn: 1.22.15 - ~\AppData\Local\fnm_multishells\6948_1659584657685\yarn.CMD
    npm: 8.3.1 - ~\AppData\Local\fnm_multishells\6948_1659584657685\npm.CMD
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
  npmPackages:
    vitest: ^0.20.3 => 0.20.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-08-07 06:36
Duplicate of https://github.com/vitest-dev/vitest/issues/1191

**Closed by sheremet-va** 2022-08-07 06:36 UTC

**Comment by Sepush** [comment] 2022-08-07 06:54
> Duplicate of #1191

for the crash it's duplicate.
but how about the error have in ci but did not happen when I run test for every single component on my computer.
It made me unable to debug for this.

**Comment by Sepush** [comment] 2022-08-07 07:59
@sheremet-va I use node 18.7.0 on my computer It works all test pass 
but on the ci still get an error and did not figure out Which test file test case failed
It's hard to debug I think this is something need improve

https://github.com/TuSimple/naive-ui/runs/7710763851?check_suite_focus=true
![image](https://user-images.githubusercontent.com/39197136/183281250-dffcb191-28bd-4c88-9aca-91c44f854a6b.png)

**Comment by sheremet-va** [comment] 2022-08-07 11:27
> but on the ci still get an error and did not figure out Which test file test case failed

Next version will show full stack trace.
