### ISSUE TITLE
Cannot run tests with yarn pnp

### ISSUE THREAD

**Issue by elboanas** [vitest-dev/vitest#5340] opened 2024-03-05 10:47 UTC
### Describe the bug

Hello, I am trying to migrate from Jest to Vitest (v1.3.1). When I launch my tests, I get this error:

`Error: p-limit tried to access #async_hooks, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound. Required package: #async_hooks (via "#async_hooks/package.json").
`
After patching the dependency in packageExtensions :

```
packageExtensions:
  "p-limit@*":
    dependencies:
      "#async_hooks": npm:async-hook@1.3.1
```

I still cannot run my tests and I get this new error :

```
SyntaxError: Named export 'AsyncResource' not found. The requested module '#async_hooks' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example, using:
import pkg from '#async_hooks';
const { AsyncResource } = pkg;
```
 When I switch my yarn nodeLinker to node-modules or pnpm, I can successfully execute my tests...

 Has anyone encountered this issue before or can provide any advice on how to resolve these errors? 

### Reproduction

Launch vitest with yarn and pnp mode enabled

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 16.43 GB / 31.67 GB
  Binaries:
    Node: 18.12.1 - ~\AppData\Local\Temp\xfs-9c416c87\node.CMD
    Yarn: 3.2.2 - ~\AppData\Local\Temp\xfs-9c416c87\yarn.CMD
    npm: 9.1.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2024-03-05 11:06
Looks like this is a problem with `p-limit`: https://github.com/sindresorhus/p-limit/issues/76

The code looks correct, I think Yarn PnP is just incorrectly resolves the `#` import without looking at the import map

**Comment by hi-ogawa** [comment] 2024-03-05 23:58
I tested the basic example https://github.com/vitest-dev/vitest/blob/main/examples/README.md with yarn pnp. I couldn't reproduce it in the latest Node 20.11.1 + Yarn 4.1.1, but indeed I get the error if I downgrade to Node: 18.12.1 + Yarn 3.2.2.

Running it with Node 20.11.1 + Yarn 3.2.2 shows a different error, so I suppose this is a Yarn issue fixed somewhere later. I'll close this since there's nothing actionable for Vitest.

**Closed by hi-ogawa** 2024-03-05 23:58 UTC
Labels: pending triage

**Comment by elboanas** [comment] 2024-03-06 11:04
Indeed, just updating Yarn to v4.1.1 with node v18.2.1 resolved the problem.
