### ISSUE TITLE
CLI flag to test given file or file/line instead of filtering by pattern

### ISSUE THREAD

**Issue by LostKobrakai** [vitest-dev/vitest#5986] opened 2024-06-27 15:46 UTC
### Clear and concise description of the problem

Coming from elixir I'm very used to running tests with `mix test path/to/file_test.exs` or `mix test path/to/file_test.exs:20`. That's very convenient to setup with an editor to have keyboard shortcuts to trigger either of them relative to where my cursor currently sits, which allows for a very rapid workflow between making changes and running tests.

vitest currently only offers test filtering by pattern, which doesn't really seem to support this usecase. Manually coming up and typing out the correct filter conditions is much more tedious.

### Suggested solution

Have a CLI frag, which can receives a path. For a directory execute all test files in that directory, for a file path just that single file and potentially also be able to execute just the test at line 12 with `path/to/file.test.js:12`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment] 2024-06-27 16:45
This is a duplicate of https://github.com/vitest-dev/vitest/issues/5445

**Closed by sheremet-va** 2024-06-27 16:45 UTC
Labels: enhancement: pending triage
