### ISSUE TITLE
Types are not actually Jest compatible

### ISSUE THREAD

**Issue by TimothyJones** [vitest-dev/vitest#3146] opened 2023-04-07 06:14 UTC
### Describe the bug

On the front page of the documentation, it says that it's "Jest Compatible". 

However, the type for a vitest `TestFunction` is `() => Awaitable<void>`. 

But, in Jest the corresponding part of their `ProvidesCallback` type is `() => Promise<unknown>`.

This matters in `beforeEach` and `afterEach`, where you might quite reasonably [call a setup promise which happens to return a value that you don't care about](https://github.com/pact-foundation/pact-js/issues/965#issuecomment-1348185596).

I think there are two possible fixes:

* Widen the type to include `Awaitable<unknown>`
* Update the [migration guide](https://vitest.dev/guide/migration.html#migrating-from-jest) to mention this issue

(side note: I think the note on the front page suggests that it would be fully jest compatible with no changes).

### Reproduction

```
describe("a test that doesn't compile", ()=> {
  it("won't compile",() => {
     return Promise.resolve(2);
  });

  beforeEach(() => {
    // neither will this
    return Promise.resolve("Some setup promise that happens to return a value")
  });
})
```

### System Info

```shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-04-07 06:58
"Hooks" section in migration guide literally  mentions what you need to do in this case.

**Comment by sheremet-va** [comment] 2023-04-07 07:00
It was also changed quite some time ago not to throw an error if something either than a function is returned. I don't see the Vitest version in your issue template (which is actually required).

**Comment by sheremet-va** [comment] 2023-04-07 07:13
Just now understood what the issue is talking about 🤦‍♂️

Changing the type to `unknown` should be fine.

**Comment by TimothyJones** [comment] 2023-04-07 09:05
Apologies, perhaps I wasn't clear with the way I worded the description.

I'm reporting it on behalf of another user (see linked issue), but I checked the source and it seems current, so I guess 0.29.8. Apologies for not including this.

I don't see the issue I'm asking about mentioned in the hooks section [here](https://vitest.dev/guide/migration.html#migrating-from-jest) - but that might have been before you realised what I was asking.

I'd be happy to send a PR updating the type.

**Comment by TimothyJones** [comment] 2023-04-07 10:10
Raised #3147

**Comment by sheremet-va** [comment] 2024-10-01 13:52
This was resolved by https://github.com/vitest-dev/vitest/pull/6393

**Closed by sheremet-va** 2024-10-01 13:52 UTC
Labels: pr welcome, types

**Comment by TimothyJones** [comment] 2024-10-01 17:25
Fantastic, thanks so much!
