### ISSUE TITLE
run test report an error

### ISSUE THREAD

**Issue by Duo-Huang** [vitest-dev/vitest#1876] opened 2022-08-18 13:31 UTC
### Describe the bug

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/50909268/185533658-cc2cc987-2548-4211-a904-6ac860b16039.png">

### Reproduction

https://github.com/Duo-Huang/demo-app

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 143.34 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.6
  npmPackages:
    @vitejs/plugin-vue: ^3.0.2 => 3.0.2 
    vite: ^3.0.6 => 3.0.6 
    vitest: ^0.21.1 => 0.21.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Duo-Huang** [comment] 2022-08-19 03:01
https://github.com/nodejs/node/issues/6899#issuecomment-1179984325, I found that vitest is also mentioned in this question

**Comment by sheremet-va** [comment] 2022-08-19 05:31
Update Node to 16.17.0.

**Comment by sheremet-va** [comment] 2022-08-19 05:32
Duplicate of https://github.com/vitest-dev/vitest/issues/1191

**Closed by sheremet-va** 2022-08-19 05:32 UTC
