### ISSUE TITLE
Check failed: node->IsInUse(). Crash in watch mode

### ISSUE THREAD

**Issue by danilofuchs** [vitest-dev/vitest#5037] opened 2024-01-23 17:06 UTC
### Describe the bug

Native Node.js crash when running in watch mode, using Prisma client

```
#
# Fatal error in , line 0
# Check failed: node->IsInUse().
#
#
#
#FailureMessage Object: 0x731febdf69d0
----- Native stack trace -----

 1: 0xd20211  [node (vitest)]
 2: 0x2118e21 V8_Fatal(char const*, ...) [node (vitest)]
 3: 0x106de89 v8::internal::GlobalHandles::Destroy(unsigned long*) [node (vitest)]
 4: 0x732557a54152 init(v8::Local<v8::Object>) [/home/project/node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node]
 5: 0xc6a52c  [node (vitest)]
 6: 0xc1a14e node::Environment::TryLoadAddon(char const*, int, std::function<bool (node::binding::DLib*)> const&) [node (vitest)]
 7: 0xc697e9 node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [node (vitest)]
 8: 0xf324bf v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [node (vitest)]
 9: 0xf32d2d  [node (vitest)]
10: 0xf331f5 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node (vitest)]
11: 0x193cdf6  [node (vitest)]
Illegal instruction (core dumped)
```

### Reproduction

vitest.config.ts:
```
import swc from "unplugin-swc";
import { defineConfig } from "vitest/config";

// https://vitejs.dev/config/
export default defineConfig({
  test: {
    globals: true,
    setupFiles: ["./test/setup.ts"],
    sequence: {
      hooks: "list",
    },
    env: {
      TZ: "utc",
    },
    include: ["./src/**/*.spec.ts", "./test/**/*.spec.ts"],
    reporters: ["dot", "hanging-process"],
    isolate: false,
    fileParallelism: false,
    pool: "threads",
    maxConcurrency: 1,
    maxWorkers: 1,
  },
  plugins: [swc.vite()],
  resolve: {
    alias: {
      "~/": new URL("./src/", import.meta.url).pathname,
      "test/": new URL("./test/", import.meta.url).pathname,
    },
  },
});
```

Prisma client is shared between tests (isolate: false)

Before each test, the HTTP server is started.

After each test, we truncate all tables and close the server.

### System Info

```shell
System:
    OS: Linux 6.6 Pop!_OS 22.04 LTS
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 16.86 GB / 31.09 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/n/bin/node
    Yarn: 1.22.19 - ~/n/bin/yarn
    npm: 10.2.4 - ~/n/bin/npm
    pnpm: 8.12.1 - ~/n/bin/pnpm
    bun: 1.0.16 - ~/.bun/bin/bun
  npmPackages:
    @vitest/coverage-v8: ^1.2.1 => 1.2.1 
    @vitest/ui: ^1.2.1 => 1.2.1 
    vitest: ^1.2.1 => 1.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment] 2024-01-23 18:53
Duplicate of https://github.com/vitest-dev/vitest/issues/3106, known issue of Prisma.

**Closed by AriPerkkio** 2024-01-23 18:53 UTC
Labels: pending triage
