### ISSUE TITLE
Support for workers in Vite app?

### ISSUE THREAD

**Issue by rowanwins** [vitest-dev/vitest#722] opened 2022-02-10 01:34 UTC
### Describe the bug

Currently when running a test on an ES6 classes that utilises a worker I get 
````
ReferenceError: Worker is not defined
````
I'm running jsdom as my test environment. Through some googling I noticed that there are some libraries out there like [jsdom-worker](https://www.npmjs.com/package/jsdom-worker) that add supposedly support however I couldn't get them to make any difference.

Any advice welcome :) 

### Reproduction

https://stackblitz.com/edit/node-clgka9?devtoolsheight=33&file=test/basic.test.ts

### System Info

```shell
`
  System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
    Memory: 89.86 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 98.1.35.100
    Safari: 14.1
  npmPackages:
    @vitejs/plugin-vue: ^2.0.0 => 2.0.1
    vite: ^2.7.2 => 2.7.13
    vitest: ^0.2.8 => 0.2.8
````
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-02-10 07:18
I've managed to make `jsdom-worker` work with a lot of workarounds: https://stackblitz.com/edit/node-z93utd?file=test/basic.test.ts

I think maybe since Vite supports Worker out of the box, we should too, will look into it

**Comment by jmarcosfer** [comment] 2022-02-11 11:49
Hi! New to vitest. I'm also interested in having workers support, so thanks for opening the PR @sheremet-va. Sadly I couldn't get your `jsdom-worker` solution to work. Since the PR is not merged yet, I've clone your fork, built from your PR branch and linked the package, but that didn't work. What's the best way to get this feature asap?

Thanks!

**Comment by sheremet-va** [comment] 2022-02-11 13:56
> Hi! New to vitest. I'm also interested in having workers support, so thanks for opening the PR @sheremet-va. Sadly I couldn't get your `jsdom-worker` solution to work. Since the PR is not merged yet, I've clone your fork, built from your PR branch and linked the package, but that didn't work. What's the best way to get this feature asap?
> 
> 
> 
> Thanks!

What error do you get, if any? 
If possible, reproduction will be handy

**Comment by jmarcosfer** [comment] 2022-02-14 17:34
My bad, I wasn't using any of those DOM environments. The worker `ReferenceError` disappeared, thanks! 

However, now I'm getting an error saying that `window.AudioContext` is not a constructor. Neither happy-dom nor jsdom seem to implement this API, so I guess I'll have to test this on an actual browser using something like Cypress.

**Closed** 2022-03-16 22:58 UTC
