### ISSUE TITLE
expect(x).toBeTruthy() should properly narrow typescript types to be non-falsy

### ISSUE THREAD

**Issue by NateRadebaugh** [vitest-dev/vitest#2883] opened 2023-02-17 13:17 UTC
### Clear and concise description of the problem

Currently, my tests must look like the following:

```ts
const bearerTokenApi1 = new BearerTokenApi(getApiConfig());
let response: GetTokenResponse | undefined;
try {
  response = await bearerTokenApi1.bearerTokenRequestToken({
    requestTokenRequest: {
      userName: env.TOKEN_USERNAME,
      password: env.TOKEN_PASSWORD,
    },
  });
} catch (error: unknown) {
  const errorMessage = await getErrorMessage(error);
  expect(errorMessage).toBe(undefined);
}

// Focus on these lines:
expect(response).toBeTruthy();
invariant(response);
```

The "invariant" function from [tiny-invariant](https://github.com/alexreardon/tiny-invariant/blob/master/src/tiny-invariant.ts) throws when falsy, similar to the `.toBeTruthy()` but has proper type narrowing.

I believe `expect(response).toBeTruthy()` should apply some sort of "asserts" to properly type narrow.

### Suggested solution

```ts
expect(response).toBeTruthy();
invariant(response);
```

should become

```ts
expect(response).toBeTruthy();
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by NateRadebaugh** [comment] 2023-02-17 13:24
I'm not a typescript wizard but this is my best effort and I'm not sure if it's even possible in typescript:

![image](https://user-images.githubusercontent.com/130445/219664336-4f39323d-f85a-43d4-85bc-f644ffc5a5e5.png)

**Comment by gregor-mueller** [comment] 2023-09-15 07:07
This would be so great! 👍 

## Problem



### Workararounds

Right now we need to do one of the following (maybe there are other workarounds out there):

#### 1. using non-null assertions

```ts
// ...
expect(foo).toBeDefined()
expect(foo!.bar).toBeDefined() // ouch, the linter cries and if we remove the line above, the test will crash
expect(foo!.bar!.baz).toBe(1337) // ouch, the linter cries and if we remove the line 2 lines above, the test will crash
// ...
```

#### 2. returning after each assertion

```ts
// ...
expect(foo).toBeDefined()
if(!foo) return // satisfy TS - but will never be reached
expect(foo.bar).toBeDefined()
if(!foo.bar) return // satisfy TS - but will never be reached
expect(foo.bar.baz).toBe(1337)
if(!foo.bar.baz) return // satisfy TS - but will never be reached
// ...
```

#### 3. throwing after each assertion

```ts
// ...
expect(foo).toBeDefined()
if(!foo) throw new Error('satisfy TS - but will never be reached')
expect(foo.bar).toBeDefined()
if(!foo.bar) throw new Error('satisfy TS - but will never be reached')
expect(foo.bar.baz).toBe(1337)
if(!foo.bar.baz) throw new Error('satisfy TS - but will never be reached')
// ...
```

#### 4. writing our own assert functions


```ts
function expectToBeDefined<T>(val?: T): asserts val is NonNullable<T> {
  expect(val).toBeDefined()
}

export function expectToBe<T>(val?: unknown, compareVal?: T): asserts val is T {
  expect(val).toBe(compareVal)
}

// ...
expectToBeDefined(foo)
expectToBeDefined(foo.bar)
expectToBe(foo.bar.baz, 1337)
// ...
```

## Proposed Solution

It would be awesome, if `expect` would directly assert the types of the checked element.
I figure, it might not be trivial for some of the assertions, but at least the checks for `undefined`, `null`, etc. could be done.
I'd love to support this endeavour but it's not easy for me to find time to work on a PR.

I tried to figure out where vitest gets the types from and searched for similar issues/prs in Jest ([issue](https://github.com/jestjs/jest/issues/10094)) and DefinitelyTyped ([issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41179), [PR (was reverted)](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41616)). So maybe the PR should be done in one of those packages, but I'm not really sure right now.

Hope this helps! Thanks for the awesome package! ❤️

**Comment by stabai** [comment] 2023-09-19 17:51
@gregor-mueller it looks like the typings for this are part of vitest, if you're willing to see if a PR would be accepted:
https://github.com/vitest-dev/vitest/blob/c21c0efacef7c0ea2c5a33470f62236059900be6/packages/expect/src/types.ts#L102-L147

I agree that there are a lot of great assertions that would be ideal here. I constantly have to do stuff like this:
```ts
expect(queryDefinition.kind).toEqual(Kind.OPERATION_DEFINITION);
if (queryDefinition.kind !== Kind.OPERATION_DEFINITION) throw new Error();
```

This should be unnecessary if this:
https://github.com/vitest-dev/vitest/blob/c21c0efacef7c0ea2c5a33470f62236059900be6/packages/expect/src/types.ts#L104
were changed to this:
```ts
toEqual<E extends T>(expected: E): asserts expected is E
```

**Comment by sheremet-va** [comment] 2023-09-20 07:12
> were changed to this

This will break valid code:

```ts
expect(1).toEqual('2')
```

This code throws, but it is expected to throw.

**Comment by gregor-mueller** [comment] 2023-09-20 09:31
> This code throws, but it is expected to throw. 

Not sure if I understand correctly. The proposed changes would not change whether it throws or not. It would just make TypeScript understand that after successfully executing the function (in case it does not throw, so basically in the next line), what type the parameter has.

`...some time later:`

Having looked deeper into the issue, it seems that this is not really possible right now. `expect` would have to be changed as well, because something like `toBeDefined` does not take in any arguments (will throw [`TS2776: Assertions require the call target to be an identifier or qualified name.`](https://github.com/microsoft/TypeScript/issues/36931)), and we would want to assert the type of the argument for `expect`.

I found a related TypeScript issue here:
https://github.com/microsoft/TypeScript/issues/40562

**Comment by sheremet-va** [comment] 2023-09-20 09:34
> Not sure if I understand correctly. The proposed changes would not change whether it throws or not. It would just make TypeScript understand that after successfully executing the function (in case it does not throw, so basically in the next line), what type the parameter has.

Throwing an error here is expected behavior. TypeScript should not fail here. But it will because `E extends T` which limits what you can put in `toEqual`.

**Comment by gregor-mueller** [comment] 2023-09-20 09:40
> But it will because `E extends T` which limits what you can put in toEqual.

Yes, I see. That's what I was going for simpler examples like `.toBeFalsy`, `.toBeTruthy`, `.toBeDefined`, etc...

Something like this _would_ be needed:

```ts
toEqual<E>(expected: E): asserts T is E // not possible
```
or
```ts
toEqual<E>(expected: E): asserts this is E // assuming 'this' would be the argument of 'expect()'
```

Looks like it is just not possible right now, because of the limitations mentioned in the linked TS issues.

**Comment by sheremet-va** [comment] 2023-09-20 09:40
In short, what I am trying to say is that TypeScript will show an error in this example, but as a developer I expect this code to fail, so I don't need TypeScript interfering. 

Vitest also provides `assert` API from chai. If people want this kind of functionality, it might be better to implement it there.

**Comment by stabai** [comment] 2023-09-20 16:37
That makes sense, I got mixed up on the assertion needing to be on the *actual* value that isn't an argument to the expect method.

It looks like the types for Chai assertions come from here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b950930e2d11584030da2b1a685c4733626b01b7/types/chai/index.d.ts#L405

They do look like they'd get around the linked TS issues to me.

**Comment by UncleSamSwiss** [comment] 2024-01-18 06:47
It would be awesome to have this directly in the built-in type definitions.

For now I use the following helper function:

```ts
export function expectToBeDefined<T>(
  value: T | null | undefined
): asserts value is T {
  expect(value).toBeDefined();
}
```

**Comment by sheremet-va** [comment] 2024-06-18 13:01
The team doesn't think this is something that we want to pursue in the Vitest core due to the edge case that will be introduced with this change (see https://github.com/oven-sh/bun/issues/6934).

`expect` types are also provided in a way when it is currently impossible to implement type assertions because the argument is in another function. Having a helper `expectToBeDefined` is a valid user-land solution.

**Closed by sheremet-va** 2024-06-18 13:01 UTC
