### ISSUE TITLE
Errors when using @storybook/testing-react on Windows

### ISSUE THREAD

**Issue by robcaldecott** [vitest-dev/vitest#472] opened 2022-01-07 12:43 UTC
### Describe the bug

When using the `@storybook/testing-react` package to import stories for use as tests on Windows, the following error will occur:

```
TypeError: Cannot set property 'wrap' of undefined
 ❯ node_modules/regenerator-runtime/runtime.js:49:16
     47|     return generator;
     48|   }
     49|   exports.wrap = wrap;
       |                ^
     50| 
     51|   // Try/catch helper to minimize deoptimizations. Returns a completion
```

This error does not occur on my Macbook (a colleague has been trying to help debug this for me.)

This issue also blocks https://github.com/vitest-dev/vitest/pull/470 as the Windows tests are failing.

### Reproduction

The following repo exhibits the issue when running `npm test` on a Windows PC:

https://github.com/robcaldecott/vitest-windows-issue

The sample test looks like this:

```tsx
import { it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import { composeStories } from "@storybook/testing-react";
import * as stories from "./Example.stories";

const { Default } = composeStories(stories);

it("renders", () => {
  render(<Default />);
  expect(
    screen.getByRole("heading", { name: /hello, world!/i, level: 1 })
  ).toBeDefined();
});
```

Adding `@storybook/testing-react` to `deps.inline` does not address the issue and the same test will work using `jest`.

### System Info

```shell
System:
    OS: Windows 10 10.0.16299
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 3.26 GB / 15.85 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Spartan (41.16299.1480.0)
    Internet Explorer: 11.0.16299.371
  npmPackages:
    @vitejs/plugin-react: ^1.0.7 => 1.1.4 
    vite: ^2.7.2 => 2.7.10 
    vitest: 0.0.136 => 0.0.136
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-01-07 12:48
Probably duplicate of #379

Try this in `test` config:

```
deps: {
  external: [/@storybook\/testing-react/],
},
```

**Comment by robcaldecott** [comment] 2022-01-07 12:53
> Probably duplicate of #379
> 
> Try this in `test` config:
> 
> ```
> deps: {
>   external: [/@storybook\/testing-react/],
> },
> ```

This gives the following error on my Mac:

```
(node:87087) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
 ❯ src/Example.test.tsx (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/Example.test.tsx [ src/Example.test.tsx ]
SyntaxError: Cannot use import statement outside a module
 ❯ wrapSafe internal/modules/cjs/loader.js:984:16
 ❯ Module._compile internal/modules/cjs/loader.js:1032:27
 ❯ Object.Module._extensions..js internal/modules/cjs/loader.js:1097:10
 ❯ Module.load internal/modules/cjs/loader.js:933:32
 ❯ Function.Module._load internal/modules/cjs/loader.js:774:14
 ❯ ModuleWrap.<anonymous> internal/modules/esm/translators.js:199:29
 ❯ ModuleJob.run internal/modules/esm/module_job.js:152:23
 ❯ async Loader.import internal/modules/esm/loader.js:177:24
 ❯ async src/Example.test.tsx:6:31
      4| import * as stories from "./Example.stories";
      5| 
      6| const { Default } = composeStories(stories);
       |                               ^
      7| 
      8| it("renders", () => {

Module /Users/caldecor/Projects/vitest-windows-issue/node_modules/@storybook/testing-react/dist/testing-react.esm.js:1 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "@storybook/testing-react" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:

// vitest.config.js
export default {
  test: {
    deps: {
      inline: [
        "@storybook/testing-react"
      ]
    }
  }
}
```

**Comment by sheremet-va** [comment] 2022-01-07 13:29
Can you try this?

```ts
// vite.config.ts
{
   resolve: {
     mainFields: []
   }
}
```

**Comment by sheremet-va** [comment] 2022-01-07 13:38
Or better update to the latest version and try again 👀 
We did a thing 👀

**Comment by robcaldecott** [comment] 2022-01-07 13:46
Boom! Success!!! Wow, you fixed that pretty quickly. I'll get my PR into shape now.

**Comment by sheremet-va** [comment] 2022-01-07 13:49
We had a known issue with importing `esm`. @antfu fixed it with a line of code

**Comment by robcaldecott** [comment] 2022-01-07 13:52
`whatwg-fetch` giving me issues in another repo now since this change. I'll investigate.

**Comment by sheremet-va** [comment] 2022-01-07 13:53
Maybe you have it in `deps`. It is not required anymore

**Comment by robcaldecott** [comment] 2022-01-07 14:00
I have removed it from `deps` and I get this:

```
TypeError: Cannot set property Headers of #<Object> which has only a getter
 ❯ node_modules/whatwg-fetch/dist/fetch.umd.js:608:20
    606|   if (!global.fetch) {
    607|     global.fetch = fetch;
    608|     global.Headers = Headers;
       |                    ^
    609|     global.Request = Request;
    610|     global.Response = Response;
```

Adding it to `deps.inline` or `deps.external` does not work.

**Comment by sheremet-va** [comment] 2022-01-07 14:07
Hope fixed in https://github.com/vitest-dev/vitest/commit/2004ecbfdb5696cdb37e546635e44a325776a0e5

Today should be the next release

**Comment by robcaldecott** [comment] 2022-01-07 14:25
@sheremet-va I hacked the `node_modules/vitest/dist/entry.js` code in one of my repos to add `writable` as an experiment:

```js
for (const key of keys) {
      Object.defineProperty(global, key, {
        get() {
          return dom.window[key];
        },
        configurable: true,
        writable: true
      });
    }
```

But then I get:

```
(node:89467) UnhandledPromiseRejectionWarning: TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
    at Function.defineProperty (<anonymous>)
    at Object.setup (/Users/caldecor/Projects/vite-kitchen-sink/node_modules/vitest/dist/entry.js:337:14)
    at async withEnv (/Users/caldecor/Projects/vite-kitchen-sink/node_modules/vitest/dist/entry.js:1403:15)
    at async run (/Users/caldecor/Projects/vite-kitchen-sink/node_modules/vitest/dist/entry.js:1722:5)
    at async file:///Users/caldecor/Projects/vite-kitchen-sink/node_modules/tinypool/dist/esm/worker.js:96:20
```

But maybe I hacked the wrong code. Looks like the `jsdom` env stuff though.

**Comment by sheremet-va** [comment] 2022-01-07 14:27
Yeah, I forgot about that nuance, and the main is broken rn 👀

**Comment by sheremet-va** [comment] 2022-01-07 15:39
Can you confirm it still errors in the latest version?

**Comment by robcaldecott** [comment] 2022-01-07 15:55
I can confirm the `whatwg-fetch` issue is now resolved. 🕺 

I was hoping my PR would work but it looks like the `eslint` rules have been changed.

**Closed** 2022-01-07 16:05 UTC
Labels: duplicate, upstream
