### ISSUE TITLE
Vitest crashing in Yarn PnP mode when using happy-dom or jsdom environment and Yarn workspaces

### ISSUE THREAD

**Issue by wojtekmaj** [vitest-dev/vitest#4413] opened 2023-10-31 14:47 UTC
### Describe the bug

When running a really basic test (irrelevant to reproduction), when using happy-dom or jsdom environment and Yarn workspaces, the following error appears:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }

```

I dug down the issue and actually caught it in `tinypool` `catch`:

<img width="704" alt="image" src="https://github.com/vitest-dev/vitest/assets/5426427/4c4b8297-a22c-44b1-ac44-010838e5270d">

And now we got somewhere:

```
ERROR Error: local-pkg tried to access happy-dom, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: happy-dom (via "happy-dom/package.json")
Required by: local-pkg@npm:0.4.3 (via /Users/wmaj/.yarn/berry/cache/local-pkg-npm-0.4.3-de61dda1fd-10c0.zip/node_modules/local-pkg/index.mjs)

    at makeError (/Users/wmaj/Projekty/vitest-pnp/.pnp.cjs:16978:34)
    at resolveToUnqualified (/Users/wmaj/Projekty/vitest-pnp/.pnp.cjs:18648:21)
    at Object.resolveToUnqualified (/Users/wmaj/Projekty/vitest-pnp/pnp.cjs:18828:26)
    at resolve$1 (file:///Users/wmaj/Projekty/vitest-pnp/.pnp.loader.mjs:1985:31)
    at nextResolve (node:internal/modules/esm/hooks:833:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:278:30)
    at handleMessage (node:internal/modules/esm/worker:168:24)
    at checkForMessages (node:internal/modules/esm/worker:117:28)
    at process.<anonymous> (node:internal/modules/esm/worker:136:5)
    at process.emit (node:events:514:28)
```

I tracked down the issue to `ensurePackageInstalled` function, and here's the full trace that leads to the issue above:

```
Trace
    at ensurePackageInstalled (file:///Users/wmaj/Projekty/vitest-pnp/.yarn/unplugged/vitest-virtual-4272a18581/node_modules/vitest/dist/vendor-node.a7c48fe1.js:153:13)
    at startVitest (file:///Users/wmaj/Projekty/vitest-pnp/.yarn/unplugged/vitest-virtual-4272a18581/node_modules/vitest/dist/vendor-node.a7c48fe1.js:21194:13)
    at async start (file:///Users/wmaj/Projekty/vitest-pnp/.yarn/unplugged/vitest-virtual-4272a18581/node_modules/vitest/dist/cli.js:135:17)
    at async CAC.run (file:///Users/wmaj/Projekty/vitest-pnp/.yarn/unplugged/vitest-virtual-4272a18581/node_modules/vitest/dist/cli.js:99:3)
```

and further to:

https://github.com/antfu/local-pkg/issues/2

I worked around this issue by quickly patching `ensurePackageInstalled`:

```diff
async function ensurePackageInstalled(dependency, root) {
+  if (process.versions.pnp) {
+    // Better than crashing I guess
+    return true;
+  }
```

But this didn't make the error go away 🫠 _Another_ issue causing the same `{ type: 'Unhandled Error', stacks: [] }` output appeared.

I again tracked it down, this time to `importModule` call, also from `local-pkg`.

When patched like so:

```ts
function importModulePnp(request) {
  if (process.versions.pnp) {
    return import(request);
  }

  return importModule(request);
}
```

the tests went all green. PHEW!

### Reproduction

[vitest-pnp.zip](https://github.com/vitest-dev/vitest/files/13217252/vitest-pnp.zip)

Unzip
```
yarn
cd submodule
yarn vitest run
```

What I found especially surprising is that without `submodule` thing, installing and calling `vitest` on the root level, it doesn't break.

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M2
    Memory: 21.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - /private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-9f5c4b9a/node
  Browsers:
    Edge: 118.0.2088.76
    Safari: 17.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-10-31 14:55
Looks like this is a duplicate of #899

**Comment by wojtekmaj** [comment] 2023-10-31 14:57
Shoot! It looks like one indeed. I hope however that the research, workarounds, and reproducible repo will come in handy.

**Comment by sheremet-va** [comment] 2023-11-01 18:06
This is because node‘s URL is overriden by jsdom URL

**Comment by robinelvin** [comment] 2023-11-02 08:09
> This is because node‘s URL is overriden by jsdom URL

Ok, so is there a fix or workaround?

**Comment by sheremet-va** [comment] 2023-11-02 08:10
You can override URL in setup files:

```ts
import { URL } from 'node:url'
globalThis.URL = URL
```

This might break _some_ JSDOM API.

**Comment by robinelvin** [comment] 2023-11-02 08:54
@sheremet-va Unfortunately this doesn't work. vitest crashes with the error before the setup files are executed. Additionally, it can't be added to the global setup or the vitest config.

I don't quite understand why this hack is required since it works perfectly well if using the normal `node_modules` mode.

**Comment by sheremet-va** [comment] 2023-11-02 08:57
I guess it uses global URL which is overriden by jsdom and incompatible with "path" module (url parser was updated in Node bot so long ago)

**Comment by robinelvin** [comment] 2023-11-02 09:15
Contrary to what this ticket is about I have switched to `happy-dom` by defining the dependency in `.yarnrc.yml` and changing the test file comment header. My tests now work.

```yaml
packageExtensions:
  local-pkg@*:
    peerDependencies:
      "happy-dom": "*"

```

**Comment by randompixel** [comment] 2023-11-17 11:24
I am getting the same error as https://github.com/vitest-dev/vitest/issues/4413#issuecomment-1789382163 
```
 FAIL  tests/unit/services/browserCheck.test.js [ tests/unit/services/browserCheck.test.js ]
Error: The "path" argument must be of type string or an instance of URL. Received an instance of URL
 ❯ makeError .pnp.cjs:25457:34
 ❯ applyNodeExportsResolution .pnp.cjs:26789:13
 ❯ resolveUnqualifiedExport .pnp.cjs:27175:35
 ❯ resolveRequest .pnp.cjs:27260:106
 ❯ Object.resolveRequest .pnp.cjs:27317:26
 ❯ resolve$1 .pnp.loader.mjs:2019:21

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_INVALID_ARG_TYPE', pnpCode: 'EXPORTS_RESOLUTION_FAILED', data: { unqualifiedPath:
....
```

However this appears to only affect `0.34.6`. If I downgrade to vitest `0.34.5` then the tests work fine.

Using Yarn 4.0.2 with PNP. Vite 4.5.0

**Comment by Michle99** [comment] 2023-12-12 23:55
I am getting the same error as https://github.com/vitest-dev/vitest/issues/4413#issuecomment-1789382163

```
 FAIL  src/__tests__/App.test.tsx [ src/__tests__/App.test.tsx ]
Error: The "path" argument must be of type string or an instance of URL. Received an instance of URL
 ❯ makeError .pnp.cjs:14195:34
 ❯ applyNodeExportsResolution .pnp.cjs:15527:13
 ❯ resolveUnqualifiedExport .pnp.cjs:15913:35
 ❯ resolveRequest .pnp.cjs:15998:106
 ❯ Object.resolveRequest .pnp.cjs:16055:26
 ❯ resolve$1 .pnp.loader.mjs:2019:21

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_INVALID_ARG_TYPE', pnpCode: 'EXPORTS_RESOLUTION_FAILED', data: { unqualifiedPath: 
...
```
Using Yarn 4.0.2 with PnP, Vite 5.0.0, Vitest 1.0.4, jsdom 23.0.1.
Is there a fix for this issue?

**Comment by llowrey** [comment] 2023-12-21 16:03
I created a yarn pull request to resolve this: https://github.com/yarnpkg/berry/pull/6030

The issue appears to be that somewhere, `global.URL` is being replaced, perhaps by an implementation that's meant to be browser compatible. Since the `URL` instances are not those generated by the node `url` package calls to `url.isURL()` fail and a number of calls made inside `.pnp.cjs` therefore fail. The PR explicitly imports `URL` from `url` in order to ensure that all ops in `.pnp.cjs` use proper `URL` objects.

A quick fix is to replace all occurrences of `new URL(` with `new url.URL(` in `.pnp.cjs`. This can be achieved via:
```
sed -i 's/new URL/new url.URL/' .pnp.cjs
```

**Comment by DiFuks** [comment] 2023-12-27 12:41
In my case, it works on Node.js 20, but I encounter the same error on version 18

```
Error: The "path" argument must be of type string or an instance of URL. Received an instance of URL
```

yarn 4.0.2, vite 5.0.10, vitest 1.0.2

**Closed** 2023-12-28 12:43 UTC
Labels: bug, p3-minor-bug :hammer:

**Comment by wojtekmaj** [comment] 2023-12-31 21:12
Thrilled to confirm version 1.1.1 fixed this issue for me!

**Comment by PilotConway** [comment] 2024-01-05 13:34
I'm still having this issue with version 1.1.2. If I run at the monorepo root I still get `{ type: 'Unhandled Error', stacks: [] }` and when I run in a specific package in my monorepo, I'm still seeing more detailed: 
```
Error: The "path" argument must be of type string or an instance of URL. Received an instance of URL
Require stack:
- /Project/Path/.yarn/cache/aria-query-npm-5.3.0-76575ac83b-305bd73c76.zip/node_modules/aria-query/lib/elementRoleMap.js
- ...
```

I upgraded from 0.34 which was the last version that was working for us.

**Comment by sheremet-va** [comment] 2024-01-05 13:36
> I'm still having this issue with version 1.1.2. If I run at the monorepo root I still get `{ type: 'Unhandled Error', stacks: [] }` and when I run in a specific package in my monorepo, I'm still seeing more detailed

This error has nothing to do with this issue. Yarn uses a global URL which is replaced when using `jsdom` or `happy-dom` environment. Yarn should use `URL` from `node:url` module.

**Comment by PilotConway** [comment] 2024-01-05 15:58
Ok, I can open another ticket then. We are using jsdom though.
