### ISSUE TITLE
Regression: Junit reporter does not escape all XML tags

### ISSUE THREAD

**Issue by flunderpero** [vitest-dev/vitest#2140] opened 2022-10-12 15:54 UTC
### Describe the bug

This seems to be a regression of #1823 
With the latest version of vitest, stacktraces are not escaped properly.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-b4w9ta?file=test/basic.test.ts

I inject the string "\<anonymous>" into the error's stacktrace and it is not escaped in the Junit-XML output.

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 99.88 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 3.1.0 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox: 105.0.1
    Safari: 15.6.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-01-01 14:18
Cannot reproduce with the latest version. I will close the issue. If you think there is still a problem, feel free to let me know.

**Closed by sheremet-va** 2023-01-01 14:18 UTC
Labels: bug, good first issue
