### ISSUE TITLE
--watch throws "address already in use" error

### ISSUE THREAD

**Issue by dionsaur84** [vitest-dev/vitest#2587] opened 2022-12-31 15:31 UTC
### Describe the bug

I'm trying to use vite for frontend and vite-node for backend

In dev, I would like:

- vite to watch files and rebuild the frontend on changes
- vite-node to watch files and restart the server on changes

For example, here is my `dev` script inside of `package.json`: 

```json
"scripts": {
    "dev": "vite build --watch && vite-node ./src/entries/server.js --watch"
},
```

Here is my `vite.config.js` file:

```javascript
import reactPlugin from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

export default defineConfig({
    build: {
        rollupOptions: {
            input: './src/entries/client.jsx',
            output: {
                entryFileNames: '[name].js',
                assetFileNames: '[name].[ext]',
            },
        },
        outDir: './public/dist',
    },
    publicDir: false,
    plugins: [
        reactPlugin(),
    ],
})
```

The `./src/entries/server.js` file just starts an express server:

```javascript
import app from '../lib/app'
import env from '../lib/env'

app.listen(env.APP_PORT, function () {
    console.log(`app listening on http://localhost:${env.APP_PORT}`)
})
```

Ideally I would like HMR to work with this as well. Perhaps I am doing this the wrong way, but right now, when I run the dev command and edit a file, `vite-node` gives the following error:

```console
[vite-node] Failed to execute file: 
 Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1468:16)
    at listenInCluster (node:net:1516:12)
    at Server.listen (node:net:1604:7)
    at Function.listen (/Users/dionsaur84/Sites/dio-framework/node_modules/express/lib/application.js:635:24)
    at /Users/dionsaur84/Sites/dio-framework/src/entries/server.js:10:5
    at ViteNodeRunner.directRequest (file:///Users/dionsaur84/Sites/dio-framework/node_modules/vite-node/dist/client.mjs:289:5)
    at ViteNodeRunner.cachedRequest (file:///Users/dionsaur84/Sites/dio-framework/node_modules/vite-node/dist/client.mjs:149:14)
    at ViteNodeRunner.executeFile (file:///Users/dionsaur84/Sites/dio-framework/node_modules/vite-node/dist/client.mjs:126:12)
    at CAC.run (file:///Users/dionsaur84/Sites/dio-framework/node_modules/vite-node/dist/cli.mjs:678:5) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5000
}
```

### Reproduction

Please see description.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 517.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /opt/homebrew/bin/node
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-12-31 15:36
Duplicate of https://github.com/vitest-dev/vitest/issues/2334

**Closed by sheremet-va** 2022-12-31 15:36 UTC

**Comment by dionsaur84** [comment] 2022-12-31 15:42
my bad, thank you
