### ISSUE TITLE
`projects` support like `jest`?

### ISSUE THREAD

**Issue by JounQin** [vitest-dev/vitest#1744] opened 2022-07-30 09:36 UTC
### Clear and concise description of the problem

For example, I want to test browser and node entry at the same time with correct coverage

### Suggested solution

As title

### Alternative

For now, I'm using

```json
{
  "test": "run-p test:*",
  "test:browser": "vitest run --coverage",
  "test:node": "cross-env TEST_ENV=node vitest run --coverage"
}
```

This works, but the coverage is partial

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment] 2022-07-31 05:39
Duplicate of https://github.com/vitest-dev/vitest/issues/256

**Closed by sheremet-va** 2022-07-31 05:39 UTC

**Comment by JounQin** [comment] 2022-07-31 05:47
@sheremet-va I think they are not the same? The issue you linked is related to monorepo, this one is not, but for different environments.

**Comment by JounQin** [comment] 2022-07-31 05:47
@sheremet-va I think they are not the same? The issue you linked is related to monorepo, this one is not, but for different environments.

**Comment by sheremet-va** [comment] 2022-07-31 06:40
It's the same implementation.

**Comment by JounQin** [comment] 2022-07-31 07:11
> It's the same implementation.

But you closed this issue as not-planned? And the linked issue's title can be updated IMO.
