### ISSUE TITLE
Vue 3 + @vitest/ui not working [stackblitz]

### ISSUE THREAD

**Issue by erwanv** [vitest-dev/vitest#1169] opened 2022-04-19 10:41 UTC
### Describe the bug

When trying to use Vue 3 + @vitest/ui we get ther following errors with the example:

_TypeError: __vite_ssr_import_1__.defineComponent is not a function_

### Reproduction

```
{
  "name": "@vitest/test-vue",
  "private": true,
  "scripts": {
    "test": "vitest --ui",
    "coverage": "vitest run --coverage"
  },
  "dependencies": {
    "vue": "^3.2.32"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "latest",
    "@vitest/ui": "latest",
    "@vue/test-utils": "latest",
    "jsdom": "latest",
    "vitest": "latest"
  },
  "stackblitz": {
    "startCommand": "npm run test"
  }
}

```

### System Info

```shell
Stackblitz
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2022-04-19 12:58
Duplicate of #553. Update Vite and Vitest to the latest versions.

**Closed by sheremet-va** 2022-04-19 12:58 UTC
