### ISSUE TITLE
Test options on `describe` is not propagating to nested `describe`s

### ISSUE THREAD

**Issue by xsjcTony** [vitest-dev/vitest#3467] opened 2023-05-30 06:25 UTC
### Describe the bug

Test options defined in OUTER `describe` only propagate to INNER `test`s, but not INNER `describe`s

This seems only fixes for `test`, but not `describe`: https://github.com/vitest-dev/vitest/pull/2025

And to be said, seems `test options` are not documented at all.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-cj4eas?file=test%2Fbug.test.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 9.07 GB / 31.69 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-react-swc: ^3.3.1 => 3.3.1
    @vitest/coverage-c8: ^0.31.1 => 0.31.1
    @vitest/coverage-istanbul: ^0.31.1 => 0.31.1
    @vitest/ui: ^0.31.1 => 0.31.1
    vite: ^4.3.9 => 4.3.9
    vitest: ^0.31.1 => 0.31.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment] 2023-05-30 07:03
Duplicate of #3454

**Comment by xsjcTony** [comment] 2023-05-30 07:12
@sheremet-va Sorry, I don't think it's a duplication. Please refer to my newly updated reproduction: https://stackblitz.com/edit/vitest-dev-vitest-cj4eas?file=test%2Ftimeout.test.ts
---

The issue #3454 is complaining about missing propagation of `timeout` to `test`s in `describe`
But I'm reporting that ALL options are not propagating from `describe` to nested `describe`s.

And I don't see anywhere fixing the issue I'm reporting in #3455

---
code: 
```ts
import { describe, expect, it } from 'vitest';

describe(
  'suite name',
  () => {
    // this won't work
    it('should timeout', async () => {
      await new Promise((resolve) => void setTimeout(resolve, 1000));
    });

    // this will work
    it(
      'should timeout',
      async () => {
        await new Promise((resolve) => void setTimeout(resolve, 1000));
      },
      { timeout: 100 }
    );

    // this won't work either
    describe('nested', () => {
      it('should timeout', async () => {
        await new Promise((resolve) => void setTimeout(resolve, 1000));
      });
    });
  },
  { timeout: 100 }
);
```

**Comment by xsjcTony** [comment] 2023-05-30 07:19
Alright, that might turns out I'm a dumb, but I'd like to keep this open and I'll give it a try whenever next release or nightly build is ready. If that resolves the issue I'll close this one.

**Comment by xsjcTony** [comment] 2023-05-31 00:01
@sheremet-va I've given it a try for `v0.31.2`, turns out it's definitely a different issue.

Turns out we should agree with this question first:

## Should test options in `describe` propagate to nested `describe`s as well or just `test`s?

If it's `yes` to this question (and I think it should be a yes), then there's a bug, if no, then leave it alone.

**Closed** 2023-05-31 14:12 UTC
Labels: bug, pr welcome
