### ISSUE TITLE
Leak detection with `--detectLeaks`

### ISSUE THREAD

**Issue by enisdenjo** [vitest-dev/vitest#2823] opened 2023-02-07 10:55 UTC
### Clear and concise description of the problem

[Jest](https://jestjs.io/) has an option (`--detectLeaks`) which will let you know if your internal environment instance is leaked after a test execution.

This option is experimental though, but can prove very valuable still.

Read more: https://jestjs.io/blog/2017/12/18/jest-22#experimental-leak-detection.

### Suggested solution

Experimental `--detectLeaks` option for object GC checks. Optionally [`jest-leak-detector`](https://www.npmjs.com/package/jest-leak-detector) itself can be used as a module in vitest to mirror the behaviour.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment] 2023-02-07 11:09
Vitest doesn't have the same concept of a "test environment", tests are running inside workers. I am not sure what it should check for leaks and how?

**Comment by sheremet-va** [comment] 2024-01-19 19:37
#3119 is a duplicate of this one, but it has more comments, so let's close this one in favor of #3119

**Closed by sheremet-va** 2024-01-19 19:37 UTC
