### ISSUE TITLE
Vitest@0.29.8 can not genetate the coverage report

### ISSUE THREAD

**Issue by CherishTheYouth** [vitest-dev/vitest#3125] opened 2023-04-03 12:24 UTC
### Describe the bug

When use Vitest@0.29.8 to run script `vitest run coverage`, it can not generate the coverage report.
Either use 'istanbul' or 'c8'.

### Reproduction

Just have a try, it is easy to recurrence。

### System Info

```shell
vitest@0.22.0 - vitest@0.29.7 runs well, vitest@0.29.8 can not generate lcov info.
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by gdams** [comment] 2023-04-03 12:53
I'm seeing this error:

```
> vitest run --coverage

TypeError: coverageModule.getProvider is not a function
    at getCoverageProvider (file:///home/runner/work/adoptium.net/adoptium.net/node_modules/vitest/dist/chunk-integrations-coverage.e0a6acd2.js:26:2[7](https://github.com/adoptium/adoptium.net/actions/runs/4544594155/jobs/8017776233?pr=1637#step:5:8))
    at async Vitest.initCoverageProvider (file:///home/runner/work/adoptium.net/adoptium.net/node_modules/vitest/dist/chunk-node-pkg.f9696901.js:15174:29)
    at async Vitest.start (file:///home/runner/work/adoptium.net/adoptium.net/node_modules/vitest/dist/chunk-node-pkg.f9696901.js:15273:7)
    at async startVitest (file:///home/runner/work/adoptium.net/adoptium.net/node_modules/vitest/dist/chunk-node-pkg.f9696901.js:22440:5)
    at async start (file:///home/runner/work/adoptium.net/adoptium.net/node_modules/vitest/dist/cli.js:105:17)
    at async CAC.run (file:///home/runner/work/adoptium.net/adoptium.net/node_modules/vitest/dist/cli.js:7[8](https://github.com/adoptium/adoptium.net/actions/runs/4544594155/jobs/8017776233?pr=1637#step:5:9):3)
```

**Comment by AriPerkkio** [comment] 2023-04-03 12:55
Likely duplicate of https://github.com/vitest-dev/vitest/issues/3118.

@gdams your stack trace indicates that you are using `vitest@0.29.7`. Please install the latest `0.29.8`.

@CherishTheYouth I'm unable to reproduce you issue without this information.

**Closed** 2023-04-03 14:05 UTC
Labels: need reproduction
