### ISSUE TITLE
Import of library is undefined in browser mode

### ISSUE THREAD

**Issue by apdrsn** [vitest-dev/vitest#4505] opened 2023-11-15 13:31 UTC
### Describe the bug

Hi team! Thanks for the great work on Vitest! 🙏
When running a test with browser mode enabled (using Playwright), my third party library `lcid` is undefined, and test will fail. 
If I try with browser mode disabled, `lcid` is available and test passes. 
See github repo example for reproduction. (could not get browsers to work in stackblitz)

### Reproduction

https://github.com/apdrsn/vitest-import-bug

Run:
```yarn playwright install```
```yarn playwright install-deps```
```yarn test```

### System Info

```shell
System:
  OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
  CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  Memory: 4.60 GB / 15.30 GB
  Container: Yes
  Shell: 5.8 - /usr/bin/zsh
Binaries:
  Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
  npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
Browsers:
  Chrome: 116.0.5845.96
npmPackages:
  @vitejs/plugin-react-swc: ^3.4.1 => 3.4.1
  @vitest/browser: 0.34.6 => 0.34.6
  vite: ^4.5.0 => 4.5.0
  vitest: 0.34.6 => 0.34.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment] 2023-12-06 08:13
I think this was a duplicate of https://github.com/vitest-dev/vitest/issues/4264 and the issue seems to be `slowHijackESM: true` which was the default before https://github.com/vitest-dev/vitest/pull/4414/.
You can either manually set it to `slowHijackESM: false` or upgrade Vitest v1 so that it's `false` by default.

**Closed** 2024-01-03 18:01 UTC
Labels: pending triage
